// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"opl-cloud/services/ledger/ent/hold"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HoldCreate is the builder for creating a Hold entity.
type HoldCreate struct {
	config
	mutation *HoldMutation
	hooks    []Hook
}

// SetAccountID sets the "account_id" field.
func (hc *HoldCreate) SetAccountID(s string) *HoldCreate {
	hc.mutation.SetAccountID(s)
	return hc
}

// SetWorkspaceID sets the "workspace_id" field.
func (hc *HoldCreate) SetWorkspaceID(s string) *HoldCreate {
	hc.mutation.SetWorkspaceID(s)
	return hc
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (hc *HoldCreate) SetNillableWorkspaceID(s *string) *HoldCreate {
	if s != nil {
		hc.SetWorkspaceID(*s)
	}
	return hc
}

// SetResourceType sets the "resource_type" field.
func (hc *HoldCreate) SetResourceType(s string) *HoldCreate {
	hc.mutation.SetResourceType(s)
	return hc
}

// SetResourceID sets the "resource_id" field.
func (hc *HoldCreate) SetResourceID(s string) *HoldCreate {
	hc.mutation.SetResourceID(s)
	return hc
}

// SetAmountCents sets the "amount_cents" field.
func (hc *HoldCreate) SetAmountCents(i int64) *HoldCreate {
	hc.mutation.SetAmountCents(i)
	return hc
}

// SetCurrency sets the "currency" field.
func (hc *HoldCreate) SetCurrency(s string) *HoldCreate {
	hc.mutation.SetCurrency(s)
	return hc
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (hc *HoldCreate) SetNillableCurrency(s *string) *HoldCreate {
	if s != nil {
		hc.SetCurrency(*s)
	}
	return hc
}

// SetStatus sets the "status" field.
func (hc *HoldCreate) SetStatus(s string) *HoldCreate {
	hc.mutation.SetStatus(s)
	return hc
}

// SetLedgerEntryID sets the "ledger_entry_id" field.
func (hc *HoldCreate) SetLedgerEntryID(s string) *HoldCreate {
	hc.mutation.SetLedgerEntryID(s)
	return hc
}

// SetWalletTransactionID sets the "wallet_transaction_id" field.
func (hc *HoldCreate) SetWalletTransactionID(s string) *HoldCreate {
	hc.mutation.SetWalletTransactionID(s)
	return hc
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (hc *HoldCreate) SetIdempotencyKey(s string) *HoldCreate {
	hc.mutation.SetIdempotencyKey(s)
	return hc
}

// SetRequestHash sets the "request_hash" field.
func (hc *HoldCreate) SetRequestHash(s string) *HoldCreate {
	hc.mutation.SetRequestHash(s)
	return hc
}

// SetCreatedAt sets the "created_at" field.
func (hc *HoldCreate) SetCreatedAt(t time.Time) *HoldCreate {
	hc.mutation.SetCreatedAt(t)
	return hc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (hc *HoldCreate) SetNillableCreatedAt(t *time.Time) *HoldCreate {
	if t != nil {
		hc.SetCreatedAt(*t)
	}
	return hc
}

// SetID sets the "id" field.
func (hc *HoldCreate) SetID(s string) *HoldCreate {
	hc.mutation.SetID(s)
	return hc
}

// Mutation returns the HoldMutation object of the builder.
func (hc *HoldCreate) Mutation() *HoldMutation {
	return hc.mutation
}

// Save creates the Hold in the database.
func (hc *HoldCreate) Save(ctx context.Context) (*Hold, error) {
	hc.defaults()
	return withHooks(ctx, hc.sqlSave, hc.mutation, hc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (hc *HoldCreate) SaveX(ctx context.Context) *Hold {
	v, err := hc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (hc *HoldCreate) Exec(ctx context.Context) error {
	_, err := hc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hc *HoldCreate) ExecX(ctx context.Context) {
	if err := hc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (hc *HoldCreate) defaults() {
	if _, ok := hc.mutation.WorkspaceID(); !ok {
		v := hold.DefaultWorkspaceID
		hc.mutation.SetWorkspaceID(v)
	}
	if _, ok := hc.mutation.Currency(); !ok {
		v := hold.DefaultCurrency
		hc.mutation.SetCurrency(v)
	}
	if _, ok := hc.mutation.CreatedAt(); !ok {
		v := hold.DefaultCreatedAt()
		hc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (hc *HoldCreate) check() error {
	if _, ok := hc.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "Hold.account_id"`)}
	}
	if v, ok := hc.mutation.AccountID(); ok {
		if err := hold.AccountIDValidator(v); err != nil {
			return &ValidationError{Name: "account_id", err: fmt.Errorf(`ent: validator failed for field "Hold.account_id": %w`, err)}
		}
	}
	if _, ok := hc.mutation.WorkspaceID(); !ok {
		return &ValidationError{Name: "workspace_id", err: errors.New(`ent: missing required field "Hold.workspace_id"`)}
	}
	if _, ok := hc.mutation.ResourceType(); !ok {
		return &ValidationError{Name: "resource_type", err: errors.New(`ent: missing required field "Hold.resource_type"`)}
	}
	if v, ok := hc.mutation.ResourceType(); ok {
		if err := hold.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "Hold.resource_type": %w`, err)}
		}
	}
	if _, ok := hc.mutation.ResourceID(); !ok {
		return &ValidationError{Name: "resource_id", err: errors.New(`ent: missing required field "Hold.resource_id"`)}
	}
	if v, ok := hc.mutation.ResourceID(); ok {
		if err := hold.ResourceIDValidator(v); err != nil {
			return &ValidationError{Name: "resource_id", err: fmt.Errorf(`ent: validator failed for field "Hold.resource_id": %w`, err)}
		}
	}
	if _, ok := hc.mutation.AmountCents(); !ok {
		return &ValidationError{Name: "amount_cents", err: errors.New(`ent: missing required field "Hold.amount_cents"`)}
	}
	if _, ok := hc.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "Hold.currency"`)}
	}
	if _, ok := hc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Hold.status"`)}
	}
	if v, ok := hc.mutation.Status(); ok {
		if err := hold.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Hold.status": %w`, err)}
		}
	}
	if _, ok := hc.mutation.LedgerEntryID(); !ok {
		return &ValidationError{Name: "ledger_entry_id", err: errors.New(`ent: missing required field "Hold.ledger_entry_id"`)}
	}
	if v, ok := hc.mutation.LedgerEntryID(); ok {
		if err := hold.LedgerEntryIDValidator(v); err != nil {
			return &ValidationError{Name: "ledger_entry_id", err: fmt.Errorf(`ent: validator failed for field "Hold.ledger_entry_id": %w`, err)}
		}
	}
	if _, ok := hc.mutation.WalletTransactionID(); !ok {
		return &ValidationError{Name: "wallet_transaction_id", err: errors.New(`ent: missing required field "Hold.wallet_transaction_id"`)}
	}
	if v, ok := hc.mutation.WalletTransactionID(); ok {
		if err := hold.WalletTransactionIDValidator(v); err != nil {
			return &ValidationError{Name: "wallet_transaction_id", err: fmt.Errorf(`ent: validator failed for field "Hold.wallet_transaction_id": %w`, err)}
		}
	}
	if _, ok := hc.mutation.IdempotencyKey(); !ok {
		return &ValidationError{Name: "idempotency_key", err: errors.New(`ent: missing required field "Hold.idempotency_key"`)}
	}
	if v, ok := hc.mutation.IdempotencyKey(); ok {
		if err := hold.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "Hold.idempotency_key": %w`, err)}
		}
	}
	if _, ok := hc.mutation.RequestHash(); !ok {
		return &ValidationError{Name: "request_hash", err: errors.New(`ent: missing required field "Hold.request_hash"`)}
	}
	if v, ok := hc.mutation.RequestHash(); ok {
		if err := hold.RequestHashValidator(v); err != nil {
			return &ValidationError{Name: "request_hash", err: fmt.Errorf(`ent: validator failed for field "Hold.request_hash": %w`, err)}
		}
	}
	if _, ok := hc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Hold.created_at"`)}
	}
	if v, ok := hc.mutation.ID(); ok {
		if err := hold.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Hold.id": %w`, err)}
		}
	}
	return nil
}

func (hc *HoldCreate) sqlSave(ctx context.Context) (*Hold, error) {
	if err := hc.check(); err != nil {
		return nil, err
	}
	_node, _spec := hc.createSpec()
	if err := sqlgraph.CreateNode(ctx, hc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Hold.ID type: %T", _spec.ID.Value)
		}
	}
	hc.mutation.id = &_node.ID
	hc.mutation.done = true
	return _node, nil
}

func (hc *HoldCreate) createSpec() (*Hold, *sqlgraph.CreateSpec) {
	var (
		_node = &Hold{config: hc.config}
		_spec = sqlgraph.NewCreateSpec(hold.Table, sqlgraph.NewFieldSpec(hold.FieldID, field.TypeString))
	)
	if id, ok := hc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := hc.mutation.AccountID(); ok {
		_spec.SetField(hold.FieldAccountID, field.TypeString, value)
		_node.AccountID = value
	}
	if value, ok := hc.mutation.WorkspaceID(); ok {
		_spec.SetField(hold.FieldWorkspaceID, field.TypeString, value)
		_node.WorkspaceID = value
	}
	if value, ok := hc.mutation.ResourceType(); ok {
		_spec.SetField(hold.FieldResourceType, field.TypeString, value)
		_node.ResourceType = value
	}
	if value, ok := hc.mutation.ResourceID(); ok {
		_spec.SetField(hold.FieldResourceID, field.TypeString, value)
		_node.ResourceID = value
	}
	if value, ok := hc.mutation.AmountCents(); ok {
		_spec.SetField(hold.FieldAmountCents, field.TypeInt64, value)
		_node.AmountCents = value
	}
	if value, ok := hc.mutation.Currency(); ok {
		_spec.SetField(hold.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := hc.mutation.Status(); ok {
		_spec.SetField(hold.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := hc.mutation.LedgerEntryID(); ok {
		_spec.SetField(hold.FieldLedgerEntryID, field.TypeString, value)
		_node.LedgerEntryID = value
	}
	if value, ok := hc.mutation.WalletTransactionID(); ok {
		_spec.SetField(hold.FieldWalletTransactionID, field.TypeString, value)
		_node.WalletTransactionID = value
	}
	if value, ok := hc.mutation.IdempotencyKey(); ok {
		_spec.SetField(hold.FieldIdempotencyKey, field.TypeString, value)
		_node.IdempotencyKey = value
	}
	if value, ok := hc.mutation.RequestHash(); ok {
		_spec.SetField(hold.FieldRequestHash, field.TypeString, value)
		_node.RequestHash = value
	}
	if value, ok := hc.mutation.CreatedAt(); ok {
		_spec.SetField(hold.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// HoldCreateBulk is the builder for creating many Hold entities in bulk.
type HoldCreateBulk struct {
	config
	err      error
	builders []*HoldCreate
}

// Save creates the Hold entities in the database.
func (hcb *HoldCreateBulk) Save(ctx context.Context) ([]*Hold, error) {
	if hcb.err != nil {
		return nil, hcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(hcb.builders))
	nodes := make([]*Hold, len(hcb.builders))
	mutators := make([]Mutator, len(hcb.builders))
	for i := range hcb.builders {
		func(i int, root context.Context) {
			builder := hcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HoldMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, hcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, hcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, hcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (hcb *HoldCreateBulk) SaveX(ctx context.Context) []*Hold {
	v, err := hcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (hcb *HoldCreateBulk) Exec(ctx context.Context) error {
	_, err := hcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hcb *HoldCreateBulk) ExecX(ctx context.Context) {
	if err := hcb.Exec(ctx); err != nil {
		panic(err)
	}
}
