// Code generated by ent, DO NOT EDIT.

package storagevolume

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the storagevolume type in the database.
	Label = "storage_volume"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldOwnerUserID holds the string denoting the owner_user_id field in the database.
	FieldOwnerUserID = "owner_user_id"
	// FieldWorkspaceID holds the string denoting the workspace_id field in the database.
	FieldWorkspaceID = "workspace_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldPackageID holds the string denoting the package_id field in the database.
	FieldPackageID = "package_id"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldProviderResourceID holds the string denoting the provider_resource_id field in the database.
	FieldProviderResourceID = "provider_resource_id"
	// FieldProviderRequestID holds the string denoting the provider_request_id field in the database.
	FieldProviderRequestID = "provider_request_id"
	// FieldOperationID holds the string denoting the operation_id field in the database.
	FieldOperationID = "operation_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldDesiredStatus holds the string denoting the desired_status field in the database.
	FieldDesiredStatus = "desired_status"
	// FieldProviderStatus holds the string denoting the provider_status field in the database.
	FieldProviderStatus = "provider_status"
	// FieldLastProviderSyncAt holds the string denoting the last_provider_sync_at field in the database.
	FieldLastProviderSyncAt = "last_provider_sync_at"
	// FieldLastProviderSyncError holds the string denoting the last_provider_sync_error field in the database.
	FieldLastProviderSyncError = "last_provider_sync_error"
	// FieldExternalDeletedAt holds the string denoting the external_deleted_at field in the database.
	FieldExternalDeletedAt = "external_deleted_at"
	// FieldBillingStatus holds the string denoting the billing_status field in the database.
	FieldBillingStatus = "billing_status"
	// FieldPricingVersion holds the string denoting the pricing_version field in the database.
	FieldPricingVersion = "pricing_version"
	// FieldBillingOperationID holds the string denoting the billing_operation_id field in the database.
	FieldBillingOperationID = "billing_operation_id"
	// FieldBillingStateJSON holds the string denoting the billing_state_json field in the database.
	FieldBillingStateJSON = "billing_state_json"
	// FieldMountPath holds the string denoting the mount_path field in the database.
	FieldMountPath = "mount_path"
	// FieldSizeGB holds the string denoting the size_gb field in the database.
	FieldSizeGB = "size_gb"
	// Table holds the table name of the storagevolume in the database.
	Table = "control_plane_storage_volumes"
)

// Columns holds all SQL columns for storagevolume fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldAccountID,
	FieldOwnerUserID,
	FieldWorkspaceID,
	FieldName,
	FieldPackageID,
	FieldProvider,
	FieldProviderResourceID,
	FieldProviderRequestID,
	FieldOperationID,
	FieldStatus,
	FieldDesiredStatus,
	FieldProviderStatus,
	FieldLastProviderSyncAt,
	FieldLastProviderSyncError,
	FieldExternalDeletedAt,
	FieldBillingStatus,
	FieldPricingVersion,
	FieldBillingOperationID,
	FieldBillingStateJSON,
	FieldMountPath,
	FieldSizeGB,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// AccountIDValidator is a validator for the "account_id" field. It is called by the builders before save.
	AccountIDValidator func(string) error
	// DefaultOwnerUserID holds the default value on creation for the "owner_user_id" field.
	DefaultOwnerUserID string
	// DefaultWorkspaceID holds the default value on creation for the "workspace_id" field.
	DefaultWorkspaceID string
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
	// DefaultPackageID holds the default value on creation for the "package_id" field.
	DefaultPackageID string
	// DefaultProvider holds the default value on creation for the "provider" field.
	DefaultProvider string
	// DefaultProviderResourceID holds the default value on creation for the "provider_resource_id" field.
	DefaultProviderResourceID string
	// DefaultProviderRequestID holds the default value on creation for the "provider_request_id" field.
	DefaultProviderRequestID string
	// DefaultOperationID holds the default value on creation for the "operation_id" field.
	DefaultOperationID string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultDesiredStatus holds the default value on creation for the "desired_status" field.
	DefaultDesiredStatus string
	// DefaultProviderStatus holds the default value on creation for the "provider_status" field.
	DefaultProviderStatus string
	// DefaultLastProviderSyncAt holds the default value on creation for the "last_provider_sync_at" field.
	DefaultLastProviderSyncAt string
	// DefaultLastProviderSyncError holds the default value on creation for the "last_provider_sync_error" field.
	DefaultLastProviderSyncError string
	// DefaultExternalDeletedAt holds the default value on creation for the "external_deleted_at" field.
	DefaultExternalDeletedAt string
	// DefaultBillingStatus holds the default value on creation for the "billing_status" field.
	DefaultBillingStatus string
	// DefaultPricingVersion holds the default value on creation for the "pricing_version" field.
	DefaultPricingVersion string
	// DefaultBillingOperationID holds the default value on creation for the "billing_operation_id" field.
	DefaultBillingOperationID string
	// DefaultBillingStateJSON holds the default value on creation for the "billing_state_json" field.
	DefaultBillingStateJSON string
	// DefaultMountPath holds the default value on creation for the "mount_path" field.
	DefaultMountPath string
	// DefaultSizeGB holds the default value on creation for the "size_gb" field.
	DefaultSizeGB float64
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the StorageVolume queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByOwnerUserID orders the results by the owner_user_id field.
func ByOwnerUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerUserID, opts...).ToFunc()
}

// ByWorkspaceID orders the results by the workspace_id field.
func ByWorkspaceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkspaceID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByPackageID orders the results by the package_id field.
func ByPackageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPackageID, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByProviderResourceID orders the results by the provider_resource_id field.
func ByProviderResourceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderResourceID, opts...).ToFunc()
}

// ByProviderRequestID orders the results by the provider_request_id field.
func ByProviderRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderRequestID, opts...).ToFunc()
}

// ByOperationID orders the results by the operation_id field.
func ByOperationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperationID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByDesiredStatus orders the results by the desired_status field.
func ByDesiredStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDesiredStatus, opts...).ToFunc()
}

// ByProviderStatus orders the results by the provider_status field.
func ByProviderStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderStatus, opts...).ToFunc()
}

// ByLastProviderSyncAt orders the results by the last_provider_sync_at field.
func ByLastProviderSyncAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastProviderSyncAt, opts...).ToFunc()
}

// ByLastProviderSyncError orders the results by the last_provider_sync_error field.
func ByLastProviderSyncError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastProviderSyncError, opts...).ToFunc()
}

// ByExternalDeletedAt orders the results by the external_deleted_at field.
func ByExternalDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExternalDeletedAt, opts...).ToFunc()
}

// ByBillingStatus orders the results by the billing_status field.
func ByBillingStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBillingStatus, opts...).ToFunc()
}

// ByPricingVersion orders the results by the pricing_version field.
func ByPricingVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPricingVersion, opts...).ToFunc()
}

// ByBillingOperationID orders the results by the billing_operation_id field.
func ByBillingOperationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBillingOperationID, opts...).ToFunc()
}

// ByBillingStateJSON orders the results by the billing_state_json field.
func ByBillingStateJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBillingStateJSON, opts...).ToFunc()
}

// ByMountPath orders the results by the mount_path field.
func ByMountPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMountPath, opts...).ToFunc()
}

// BySizeGB orders the results by the size_gb field.
func BySizeGB(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSizeGB, opts...).ToFunc()
}
