// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"opl-cloud/services/control-plane/ent/adminauditevent"
	"opl-cloud/services/control-plane/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AdminAuditEventQuery is the builder for querying AdminAuditEvent entities.
type AdminAuditEventQuery struct {
	config
	ctx        *QueryContext
	order      []adminauditevent.OrderOption
	inters     []Interceptor
	predicates []predicate.AdminAuditEvent
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AdminAuditEventQuery builder.
func (aaeq *AdminAuditEventQuery) Where(ps ...predicate.AdminAuditEvent) *AdminAuditEventQuery {
	aaeq.predicates = append(aaeq.predicates, ps...)
	return aaeq
}

// Limit the number of records to be returned by this query.
func (aaeq *AdminAuditEventQuery) Limit(limit int) *AdminAuditEventQuery {
	aaeq.ctx.Limit = &limit
	return aaeq
}

// Offset to start from.
func (aaeq *AdminAuditEventQuery) Offset(offset int) *AdminAuditEventQuery {
	aaeq.ctx.Offset = &offset
	return aaeq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (aaeq *AdminAuditEventQuery) Unique(unique bool) *AdminAuditEventQuery {
	aaeq.ctx.Unique = &unique
	return aaeq
}

// Order specifies how the records should be ordered.
func (aaeq *AdminAuditEventQuery) Order(o ...adminauditevent.OrderOption) *AdminAuditEventQuery {
	aaeq.order = append(aaeq.order, o...)
	return aaeq
}

// First returns the first AdminAuditEvent entity from the query.
// Returns a *NotFoundError when no AdminAuditEvent was found.
func (aaeq *AdminAuditEventQuery) First(ctx context.Context) (*AdminAuditEvent, error) {
	nodes, err := aaeq.Limit(1).All(setContextOp(ctx, aaeq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{adminauditevent.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (aaeq *AdminAuditEventQuery) FirstX(ctx context.Context) *AdminAuditEvent {
	node, err := aaeq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AdminAuditEvent ID from the query.
// Returns a *NotFoundError when no AdminAuditEvent ID was found.
func (aaeq *AdminAuditEventQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = aaeq.Limit(1).IDs(setContextOp(ctx, aaeq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{adminauditevent.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (aaeq *AdminAuditEventQuery) FirstIDX(ctx context.Context) string {
	id, err := aaeq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AdminAuditEvent entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AdminAuditEvent entity is found.
// Returns a *NotFoundError when no AdminAuditEvent entities are found.
func (aaeq *AdminAuditEventQuery) Only(ctx context.Context) (*AdminAuditEvent, error) {
	nodes, err := aaeq.Limit(2).All(setContextOp(ctx, aaeq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{adminauditevent.Label}
	default:
		return nil, &NotSingularError{adminauditevent.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (aaeq *AdminAuditEventQuery) OnlyX(ctx context.Context) *AdminAuditEvent {
	node, err := aaeq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AdminAuditEvent ID in the query.
// Returns a *NotSingularError when more than one AdminAuditEvent ID is found.
// Returns a *NotFoundError when no entities are found.
func (aaeq *AdminAuditEventQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = aaeq.Limit(2).IDs(setContextOp(ctx, aaeq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{adminauditevent.Label}
	default:
		err = &NotSingularError{adminauditevent.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (aaeq *AdminAuditEventQuery) OnlyIDX(ctx context.Context) string {
	id, err := aaeq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AdminAuditEvents.
func (aaeq *AdminAuditEventQuery) All(ctx context.Context) ([]*AdminAuditEvent, error) {
	ctx = setContextOp(ctx, aaeq.ctx, "All")
	if err := aaeq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AdminAuditEvent, *AdminAuditEventQuery]()
	return withInterceptors[[]*AdminAuditEvent](ctx, aaeq, qr, aaeq.inters)
}

// AllX is like All, but panics if an error occurs.
func (aaeq *AdminAuditEventQuery) AllX(ctx context.Context) []*AdminAuditEvent {
	nodes, err := aaeq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AdminAuditEvent IDs.
func (aaeq *AdminAuditEventQuery) IDs(ctx context.Context) (ids []string, err error) {
	if aaeq.ctx.Unique == nil && aaeq.path != nil {
		aaeq.Unique(true)
	}
	ctx = setContextOp(ctx, aaeq.ctx, "IDs")
	if err = aaeq.Select(adminauditevent.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (aaeq *AdminAuditEventQuery) IDsX(ctx context.Context) []string {
	ids, err := aaeq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (aaeq *AdminAuditEventQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, aaeq.ctx, "Count")
	if err := aaeq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, aaeq, querierCount[*AdminAuditEventQuery](), aaeq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (aaeq *AdminAuditEventQuery) CountX(ctx context.Context) int {
	count, err := aaeq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (aaeq *AdminAuditEventQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, aaeq.ctx, "Exist")
	switch _, err := aaeq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (aaeq *AdminAuditEventQuery) ExistX(ctx context.Context) bool {
	exist, err := aaeq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AdminAuditEventQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (aaeq *AdminAuditEventQuery) Clone() *AdminAuditEventQuery {
	if aaeq == nil {
		return nil
	}
	return &AdminAuditEventQuery{
		config:     aaeq.config,
		ctx:        aaeq.ctx.Clone(),
		order:      append([]adminauditevent.OrderOption{}, aaeq.order...),
		inters:     append([]Interceptor{}, aaeq.inters...),
		predicates: append([]predicate.AdminAuditEvent{}, aaeq.predicates...),
		// clone intermediate query.
		sql:  aaeq.sql.Clone(),
		path: aaeq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AdminAuditEvent.Query().
//		GroupBy(adminauditevent.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (aaeq *AdminAuditEventQuery) GroupBy(field string, fields ...string) *AdminAuditEventGroupBy {
	aaeq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AdminAuditEventGroupBy{build: aaeq}
	grbuild.flds = &aaeq.ctx.Fields
	grbuild.label = adminauditevent.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.AdminAuditEvent.Query().
//		Select(adminauditevent.FieldCreatedAt).
//		Scan(ctx, &v)
func (aaeq *AdminAuditEventQuery) Select(fields ...string) *AdminAuditEventSelect {
	aaeq.ctx.Fields = append(aaeq.ctx.Fields, fields...)
	sbuild := &AdminAuditEventSelect{AdminAuditEventQuery: aaeq}
	sbuild.label = adminauditevent.Label
	sbuild.flds, sbuild.scan = &aaeq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AdminAuditEventSelect configured with the given aggregations.
func (aaeq *AdminAuditEventQuery) Aggregate(fns ...AggregateFunc) *AdminAuditEventSelect {
	return aaeq.Select().Aggregate(fns...)
}

func (aaeq *AdminAuditEventQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range aaeq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, aaeq); err != nil {
				return err
			}
		}
	}
	for _, f := range aaeq.ctx.Fields {
		if !adminauditevent.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if aaeq.path != nil {
		prev, err := aaeq.path(ctx)
		if err != nil {
			return err
		}
		aaeq.sql = prev
	}
	return nil
}

func (aaeq *AdminAuditEventQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AdminAuditEvent, error) {
	var (
		nodes = []*AdminAuditEvent{}
		_spec = aaeq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AdminAuditEvent).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AdminAuditEvent{config: aaeq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, aaeq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (aaeq *AdminAuditEventQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := aaeq.querySpec()
	_spec.Node.Columns = aaeq.ctx.Fields
	if len(aaeq.ctx.Fields) > 0 {
		_spec.Unique = aaeq.ctx.Unique != nil && *aaeq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, aaeq.driver, _spec)
}

func (aaeq *AdminAuditEventQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(adminauditevent.Table, adminauditevent.Columns, sqlgraph.NewFieldSpec(adminauditevent.FieldID, field.TypeString))
	_spec.From = aaeq.sql
	if unique := aaeq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if aaeq.path != nil {
		_spec.Unique = true
	}
	if fields := aaeq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, adminauditevent.FieldID)
		for i := range fields {
			if fields[i] != adminauditevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := aaeq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := aaeq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := aaeq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := aaeq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (aaeq *AdminAuditEventQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(aaeq.driver.Dialect())
	t1 := builder.Table(adminauditevent.Table)
	columns := aaeq.ctx.Fields
	if len(columns) == 0 {
		columns = adminauditevent.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if aaeq.sql != nil {
		selector = aaeq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if aaeq.ctx.Unique != nil && *aaeq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range aaeq.predicates {
		p(selector)
	}
	for _, p := range aaeq.order {
		p(selector)
	}
	if offset := aaeq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := aaeq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AdminAuditEventGroupBy is the group-by builder for AdminAuditEvent entities.
type AdminAuditEventGroupBy struct {
	selector
	build *AdminAuditEventQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (aaegb *AdminAuditEventGroupBy) Aggregate(fns ...AggregateFunc) *AdminAuditEventGroupBy {
	aaegb.fns = append(aaegb.fns, fns...)
	return aaegb
}

// Scan applies the selector query and scans the result into the given value.
func (aaegb *AdminAuditEventGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, aaegb.build.ctx, "GroupBy")
	if err := aaegb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AdminAuditEventQuery, *AdminAuditEventGroupBy](ctx, aaegb.build, aaegb, aaegb.build.inters, v)
}

func (aaegb *AdminAuditEventGroupBy) sqlScan(ctx context.Context, root *AdminAuditEventQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(aaegb.fns))
	for _, fn := range aaegb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*aaegb.flds)+len(aaegb.fns))
		for _, f := range *aaegb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*aaegb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := aaegb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AdminAuditEventSelect is the builder for selecting fields of AdminAuditEvent entities.
type AdminAuditEventSelect struct {
	*AdminAuditEventQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (aaes *AdminAuditEventSelect) Aggregate(fns ...AggregateFunc) *AdminAuditEventSelect {
	aaes.fns = append(aaes.fns, fns...)
	return aaes
}

// Scan applies the selector query and scans the result into the given value.
func (aaes *AdminAuditEventSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, aaes.ctx, "Select")
	if err := aaes.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AdminAuditEventQuery, *AdminAuditEventSelect](ctx, aaes.AdminAuditEventQuery, aaes, aaes.inters, v)
}

func (aaes *AdminAuditEventSelect) sqlScan(ctx context.Context, root *AdminAuditEventQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(aaes.fns))
	for _, fn := range aaes.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*aaes.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := aaes.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
