// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"opl-cloud/services/control-plane/ent/archivedworkspace"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ArchivedWorkspace is the model entity for the ArchivedWorkspace schema.
type ArchivedWorkspace struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID string `json:"account_id,omitempty"`
	// WorkspaceID holds the value of the "workspace_id" field.
	WorkspaceID string `json:"workspace_id,omitempty"`
	// ResourceID holds the value of the "resource_id" field.
	ResourceID string `json:"resource_id,omitempty"`
	// ResourceKind holds the value of the "resource_kind" field.
	ResourceKind string `json:"resource_kind,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason string `json:"reason,omitempty"`
	// ArchivedAt holds the value of the "archived_at" field.
	ArchivedAt   *time.Time `json:"archived_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ArchivedWorkspace) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case archivedworkspace.FieldID, archivedworkspace.FieldAccountID, archivedworkspace.FieldWorkspaceID, archivedworkspace.FieldResourceID, archivedworkspace.FieldResourceKind, archivedworkspace.FieldName, archivedworkspace.FieldStatus, archivedworkspace.FieldReason:
			values[i] = new(sql.NullString)
		case archivedworkspace.FieldCreatedAt, archivedworkspace.FieldUpdatedAt, archivedworkspace.FieldArchivedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ArchivedWorkspace fields.
func (aw *ArchivedWorkspace) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case archivedworkspace.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				aw.ID = value.String
			}
		case archivedworkspace.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				aw.CreatedAt = value.Time
			}
		case archivedworkspace.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				aw.UpdatedAt = value.Time
			}
		case archivedworkspace.FieldAccountID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				aw.AccountID = value.String
			}
		case archivedworkspace.FieldWorkspaceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field workspace_id", values[i])
			} else if value.Valid {
				aw.WorkspaceID = value.String
			}
		case archivedworkspace.FieldResourceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resource_id", values[i])
			} else if value.Valid {
				aw.ResourceID = value.String
			}
		case archivedworkspace.FieldResourceKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resource_kind", values[i])
			} else if value.Valid {
				aw.ResourceKind = value.String
			}
		case archivedworkspace.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				aw.Name = value.String
			}
		case archivedworkspace.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				aw.Status = value.String
			}
		case archivedworkspace.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				aw.Reason = value.String
			}
		case archivedworkspace.FieldArchivedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field archived_at", values[i])
			} else if value.Valid {
				aw.ArchivedAt = new(time.Time)
				*aw.ArchivedAt = value.Time
			}
		default:
			aw.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ArchivedWorkspace.
// This includes values selected through modifiers, order, etc.
func (aw *ArchivedWorkspace) Value(name string) (ent.Value, error) {
	return aw.selectValues.Get(name)
}

// Update returns a builder for updating this ArchivedWorkspace.
// Note that you need to call ArchivedWorkspace.Unwrap() before calling this method if this ArchivedWorkspace
// was returned from a transaction, and the transaction was committed or rolled back.
func (aw *ArchivedWorkspace) Update() *ArchivedWorkspaceUpdateOne {
	return NewArchivedWorkspaceClient(aw.config).UpdateOne(aw)
}

// Unwrap unwraps the ArchivedWorkspace entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (aw *ArchivedWorkspace) Unwrap() *ArchivedWorkspace {
	_tx, ok := aw.config.driver.(*txDriver)
	if !ok {
		panic("ent: ArchivedWorkspace is not a transactional entity")
	}
	aw.config.driver = _tx.drv
	return aw
}

// String implements the fmt.Stringer.
func (aw *ArchivedWorkspace) String() string {
	var builder strings.Builder
	builder.WriteString("ArchivedWorkspace(")
	builder.WriteString(fmt.Sprintf("id=%v, ", aw.ID))
	builder.WriteString("created_at=")
	builder.WriteString(aw.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(aw.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(aw.AccountID)
	builder.WriteString(", ")
	builder.WriteString("workspace_id=")
	builder.WriteString(aw.WorkspaceID)
	builder.WriteString(", ")
	builder.WriteString("resource_id=")
	builder.WriteString(aw.ResourceID)
	builder.WriteString(", ")
	builder.WriteString("resource_kind=")
	builder.WriteString(aw.ResourceKind)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(aw.Name)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(aw.Status)
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(aw.Reason)
	builder.WriteString(", ")
	if v := aw.ArchivedAt; v != nil {
		builder.WriteString("archived_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ArchivedWorkspaces is a parsable slice of ArchivedWorkspace.
type ArchivedWorkspaces []*ArchivedWorkspace
