// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"opl-cloud/services/control-plane/ent/computeallocation"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ComputeAllocationCreate is the builder for creating a ComputeAllocation entity.
type ComputeAllocationCreate struct {
	config
	mutation *ComputeAllocationMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (cac *ComputeAllocationCreate) SetCreatedAt(t time.Time) *ComputeAllocationCreate {
	cac.mutation.SetCreatedAt(t)
	return cac
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cac *ComputeAllocationCreate) SetNillableCreatedAt(t *time.Time) *ComputeAllocationCreate {
	if t != nil {
		cac.SetCreatedAt(*t)
	}
	return cac
}

// SetUpdatedAt sets the "updated_at" field.
func (cac *ComputeAllocationCreate) SetUpdatedAt(t time.Time) *ComputeAllocationCreate {
	cac.mutation.SetUpdatedAt(t)
	return cac
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (cac *ComputeAllocationCreate) SetNillableUpdatedAt(t *time.Time) *ComputeAllocationCreate {
	if t != nil {
		cac.SetUpdatedAt(*t)
	}
	return cac
}

// SetAccountID sets the "account_id" field.
func (cac *ComputeAllocationCreate) SetAccountID(s string) *ComputeAllocationCreate {
	cac.mutation.SetAccountID(s)
	return cac
}

// SetOwnerUserID sets the "owner_user_id" field.
func (cac *ComputeAllocationCreate) SetOwnerUserID(s string) *ComputeAllocationCreate {
	cac.mutation.SetOwnerUserID(s)
	return cac
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (cac *ComputeAllocationCreate) SetNillableOwnerUserID(s *string) *ComputeAllocationCreate {
	if s != nil {
		cac.SetOwnerUserID(*s)
	}
	return cac
}

// SetWorkspaceID sets the "workspace_id" field.
func (cac *ComputeAllocationCreate) SetWorkspaceID(s string) *ComputeAllocationCreate {
	cac.mutation.SetWorkspaceID(s)
	return cac
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (cac *ComputeAllocationCreate) SetNillableWorkspaceID(s *string) *ComputeAllocationCreate {
	if s != nil {
		cac.SetWorkspaceID(*s)
	}
	return cac
}

// SetName sets the "name" field.
func (cac *ComputeAllocationCreate) SetName(s string) *ComputeAllocationCreate {
	cac.mutation.SetName(s)
	return cac
}

// SetNillableName sets the "name" field if the given value is not nil.
func (cac *ComputeAllocationCreate) SetNillableName(s *string) *ComputeAllocationCreate {
	if s != nil {
		cac.SetName(*s)
	}
	return cac
}

// SetPackageID sets the "package_id" field.
func (cac *ComputeAllocationCreate) SetPackageID(s string) *ComputeAllocationCreate {
	cac.mutation.SetPackageID(s)
	return cac
}

// SetNillablePackageID sets the "package_id" field if the given value is not nil.
func (cac *ComputeAllocationCreate) SetNillablePackageID(s *string) *ComputeAllocationCreate {
	if s != nil {
		cac.SetPackageID(*s)
	}
	return cac
}

// SetProvider sets the "provider" field.
func (cac *ComputeAllocationCreate) SetProvider(s string) *ComputeAllocationCreate {
	cac.mutation.SetProvider(s)
	return cac
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (cac *ComputeAllocationCreate) SetNillableProvider(s *string) *ComputeAllocationCreate {
	if s != nil {
		cac.SetProvider(*s)
	}
	return cac
}

// SetProviderResourceID sets the "provider_resource_id" field.
func (cac *ComputeAllocationCreate) SetProviderResourceID(s string) *ComputeAllocationCreate {
	cac.mutation.SetProviderResourceID(s)
	return cac
}

// SetNillableProviderResourceID sets the "provider_resource_id" field if the given value is not nil.
func (cac *ComputeAllocationCreate) SetNillableProviderResourceID(s *string) *ComputeAllocationCreate {
	if s != nil {
		cac.SetProviderResourceID(*s)
	}
	return cac
}

// SetProviderRequestID sets the "provider_request_id" field.
func (cac *ComputeAllocationCreate) SetProviderRequestID(s string) *ComputeAllocationCreate {
	cac.mutation.SetProviderRequestID(s)
	return cac
}

// SetNillableProviderRequestID sets the "provider_request_id" field if the given value is not nil.
func (cac *ComputeAllocationCreate) SetNillableProviderRequestID(s *string) *ComputeAllocationCreate {
	if s != nil {
		cac.SetProviderRequestID(*s)
	}
	return cac
}

// SetOperationID sets the "operation_id" field.
func (cac *ComputeAllocationCreate) SetOperationID(s string) *ComputeAllocationCreate {
	cac.mutation.SetOperationID(s)
	return cac
}

// SetNillableOperationID sets the "operation_id" field if the given value is not nil.
func (cac *ComputeAllocationCreate) SetNillableOperationID(s *string) *ComputeAllocationCreate {
	if s != nil {
		cac.SetOperationID(*s)
	}
	return cac
}

// SetStatus sets the "status" field.
func (cac *ComputeAllocationCreate) SetStatus(s string) *ComputeAllocationCreate {
	cac.mutation.SetStatus(s)
	return cac
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (cac *ComputeAllocationCreate) SetNillableStatus(s *string) *ComputeAllocationCreate {
	if s != nil {
		cac.SetStatus(*s)
	}
	return cac
}

// SetDesiredStatus sets the "desired_status" field.
func (cac *ComputeAllocationCreate) SetDesiredStatus(s string) *ComputeAllocationCreate {
	cac.mutation.SetDesiredStatus(s)
	return cac
}

// SetNillableDesiredStatus sets the "desired_status" field if the given value is not nil.
func (cac *ComputeAllocationCreate) SetNillableDesiredStatus(s *string) *ComputeAllocationCreate {
	if s != nil {
		cac.SetDesiredStatus(*s)
	}
	return cac
}

// SetProviderStatus sets the "provider_status" field.
func (cac *ComputeAllocationCreate) SetProviderStatus(s string) *ComputeAllocationCreate {
	cac.mutation.SetProviderStatus(s)
	return cac
}

// SetNillableProviderStatus sets the "provider_status" field if the given value is not nil.
func (cac *ComputeAllocationCreate) SetNillableProviderStatus(s *string) *ComputeAllocationCreate {
	if s != nil {
		cac.SetProviderStatus(*s)
	}
	return cac
}

// SetLastProviderSyncAt sets the "last_provider_sync_at" field.
func (cac *ComputeAllocationCreate) SetLastProviderSyncAt(s string) *ComputeAllocationCreate {
	cac.mutation.SetLastProviderSyncAt(s)
	return cac
}

// SetNillableLastProviderSyncAt sets the "last_provider_sync_at" field if the given value is not nil.
func (cac *ComputeAllocationCreate) SetNillableLastProviderSyncAt(s *string) *ComputeAllocationCreate {
	if s != nil {
		cac.SetLastProviderSyncAt(*s)
	}
	return cac
}

// SetLastProviderSyncError sets the "last_provider_sync_error" field.
func (cac *ComputeAllocationCreate) SetLastProviderSyncError(s string) *ComputeAllocationCreate {
	cac.mutation.SetLastProviderSyncError(s)
	return cac
}

// SetNillableLastProviderSyncError sets the "last_provider_sync_error" field if the given value is not nil.
func (cac *ComputeAllocationCreate) SetNillableLastProviderSyncError(s *string) *ComputeAllocationCreate {
	if s != nil {
		cac.SetLastProviderSyncError(*s)
	}
	return cac
}

// SetExternalDeletedAt sets the "external_deleted_at" field.
func (cac *ComputeAllocationCreate) SetExternalDeletedAt(s string) *ComputeAllocationCreate {
	cac.mutation.SetExternalDeletedAt(s)
	return cac
}

// SetNillableExternalDeletedAt sets the "external_deleted_at" field if the given value is not nil.
func (cac *ComputeAllocationCreate) SetNillableExternalDeletedAt(s *string) *ComputeAllocationCreate {
	if s != nil {
		cac.SetExternalDeletedAt(*s)
	}
	return cac
}

// SetBillingStatus sets the "billing_status" field.
func (cac *ComputeAllocationCreate) SetBillingStatus(s string) *ComputeAllocationCreate {
	cac.mutation.SetBillingStatus(s)
	return cac
}

// SetNillableBillingStatus sets the "billing_status" field if the given value is not nil.
func (cac *ComputeAllocationCreate) SetNillableBillingStatus(s *string) *ComputeAllocationCreate {
	if s != nil {
		cac.SetBillingStatus(*s)
	}
	return cac
}

// SetPricingVersion sets the "pricing_version" field.
func (cac *ComputeAllocationCreate) SetPricingVersion(s string) *ComputeAllocationCreate {
	cac.mutation.SetPricingVersion(s)
	return cac
}

// SetNillablePricingVersion sets the "pricing_version" field if the given value is not nil.
func (cac *ComputeAllocationCreate) SetNillablePricingVersion(s *string) *ComputeAllocationCreate {
	if s != nil {
		cac.SetPricingVersion(*s)
	}
	return cac
}

// SetBillingOperationID sets the "billing_operation_id" field.
func (cac *ComputeAllocationCreate) SetBillingOperationID(s string) *ComputeAllocationCreate {
	cac.mutation.SetBillingOperationID(s)
	return cac
}

// SetNillableBillingOperationID sets the "billing_operation_id" field if the given value is not nil.
func (cac *ComputeAllocationCreate) SetNillableBillingOperationID(s *string) *ComputeAllocationCreate {
	if s != nil {
		cac.SetBillingOperationID(*s)
	}
	return cac
}

// SetBillingStateJSON sets the "billing_state_json" field.
func (cac *ComputeAllocationCreate) SetBillingStateJSON(s string) *ComputeAllocationCreate {
	cac.mutation.SetBillingStateJSON(s)
	return cac
}

// SetNillableBillingStateJSON sets the "billing_state_json" field if the given value is not nil.
func (cac *ComputeAllocationCreate) SetNillableBillingStateJSON(s *string) *ComputeAllocationCreate {
	if s != nil {
		cac.SetBillingStateJSON(*s)
	}
	return cac
}

// SetEvidenceID sets the "evidence_id" field.
func (cac *ComputeAllocationCreate) SetEvidenceID(s string) *ComputeAllocationCreate {
	cac.mutation.SetEvidenceID(s)
	return cac
}

// SetNillableEvidenceID sets the "evidence_id" field if the given value is not nil.
func (cac *ComputeAllocationCreate) SetNillableEvidenceID(s *string) *ComputeAllocationCreate {
	if s != nil {
		cac.SetEvidenceID(*s)
	}
	return cac
}

// SetCvmInstanceID sets the "cvm_instance_id" field.
func (cac *ComputeAllocationCreate) SetCvmInstanceID(s string) *ComputeAllocationCreate {
	cac.mutation.SetCvmInstanceID(s)
	return cac
}

// SetNillableCvmInstanceID sets the "cvm_instance_id" field if the given value is not nil.
func (cac *ComputeAllocationCreate) SetNillableCvmInstanceID(s *string) *ComputeAllocationCreate {
	if s != nil {
		cac.SetCvmInstanceID(*s)
	}
	return cac
}

// SetInstanceID sets the "instance_id" field.
func (cac *ComputeAllocationCreate) SetInstanceID(s string) *ComputeAllocationCreate {
	cac.mutation.SetInstanceID(s)
	return cac
}

// SetNillableInstanceID sets the "instance_id" field if the given value is not nil.
func (cac *ComputeAllocationCreate) SetNillableInstanceID(s *string) *ComputeAllocationCreate {
	if s != nil {
		cac.SetInstanceID(*s)
	}
	return cac
}

// SetNodeName sets the "node_name" field.
func (cac *ComputeAllocationCreate) SetNodeName(s string) *ComputeAllocationCreate {
	cac.mutation.SetNodeName(s)
	return cac
}

// SetNillableNodeName sets the "node_name" field if the given value is not nil.
func (cac *ComputeAllocationCreate) SetNillableNodeName(s *string) *ComputeAllocationCreate {
	if s != nil {
		cac.SetNodeName(*s)
	}
	return cac
}

// SetMachineName sets the "machine_name" field.
func (cac *ComputeAllocationCreate) SetMachineName(s string) *ComputeAllocationCreate {
	cac.mutation.SetMachineName(s)
	return cac
}

// SetNillableMachineName sets the "machine_name" field if the given value is not nil.
func (cac *ComputeAllocationCreate) SetNillableMachineName(s *string) *ComputeAllocationCreate {
	if s != nil {
		cac.SetMachineName(*s)
	}
	return cac
}

// SetCPU sets the "cpu" field.
func (cac *ComputeAllocationCreate) SetCPU(f float64) *ComputeAllocationCreate {
	cac.mutation.SetCPU(f)
	return cac
}

// SetNillableCPU sets the "cpu" field if the given value is not nil.
func (cac *ComputeAllocationCreate) SetNillableCPU(f *float64) *ComputeAllocationCreate {
	if f != nil {
		cac.SetCPU(*f)
	}
	return cac
}

// SetMemoryGB sets the "memory_gb" field.
func (cac *ComputeAllocationCreate) SetMemoryGB(f float64) *ComputeAllocationCreate {
	cac.mutation.SetMemoryGB(f)
	return cac
}

// SetNillableMemoryGB sets the "memory_gb" field if the given value is not nil.
func (cac *ComputeAllocationCreate) SetNillableMemoryGB(f *float64) *ComputeAllocationCreate {
	if f != nil {
		cac.SetMemoryGB(*f)
	}
	return cac
}

// SetDiskGB sets the "disk_gb" field.
func (cac *ComputeAllocationCreate) SetDiskGB(f float64) *ComputeAllocationCreate {
	cac.mutation.SetDiskGB(f)
	return cac
}

// SetNillableDiskGB sets the "disk_gb" field if the given value is not nil.
func (cac *ComputeAllocationCreate) SetNillableDiskGB(f *float64) *ComputeAllocationCreate {
	if f != nil {
		cac.SetDiskGB(*f)
	}
	return cac
}

// SetID sets the "id" field.
func (cac *ComputeAllocationCreate) SetID(s string) *ComputeAllocationCreate {
	cac.mutation.SetID(s)
	return cac
}

// Mutation returns the ComputeAllocationMutation object of the builder.
func (cac *ComputeAllocationCreate) Mutation() *ComputeAllocationMutation {
	return cac.mutation
}

// Save creates the ComputeAllocation in the database.
func (cac *ComputeAllocationCreate) Save(ctx context.Context) (*ComputeAllocation, error) {
	cac.defaults()
	return withHooks(ctx, cac.sqlSave, cac.mutation, cac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cac *ComputeAllocationCreate) SaveX(ctx context.Context) *ComputeAllocation {
	v, err := cac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cac *ComputeAllocationCreate) Exec(ctx context.Context) error {
	_, err := cac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cac *ComputeAllocationCreate) ExecX(ctx context.Context) {
	if err := cac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cac *ComputeAllocationCreate) defaults() {
	if _, ok := cac.mutation.CreatedAt(); !ok {
		v := computeallocation.DefaultCreatedAt()
		cac.mutation.SetCreatedAt(v)
	}
	if _, ok := cac.mutation.UpdatedAt(); !ok {
		v := computeallocation.DefaultUpdatedAt()
		cac.mutation.SetUpdatedAt(v)
	}
	if _, ok := cac.mutation.OwnerUserID(); !ok {
		v := computeallocation.DefaultOwnerUserID
		cac.mutation.SetOwnerUserID(v)
	}
	if _, ok := cac.mutation.WorkspaceID(); !ok {
		v := computeallocation.DefaultWorkspaceID
		cac.mutation.SetWorkspaceID(v)
	}
	if _, ok := cac.mutation.Name(); !ok {
		v := computeallocation.DefaultName
		cac.mutation.SetName(v)
	}
	if _, ok := cac.mutation.PackageID(); !ok {
		v := computeallocation.DefaultPackageID
		cac.mutation.SetPackageID(v)
	}
	if _, ok := cac.mutation.Provider(); !ok {
		v := computeallocation.DefaultProvider
		cac.mutation.SetProvider(v)
	}
	if _, ok := cac.mutation.ProviderResourceID(); !ok {
		v := computeallocation.DefaultProviderResourceID
		cac.mutation.SetProviderResourceID(v)
	}
	if _, ok := cac.mutation.ProviderRequestID(); !ok {
		v := computeallocation.DefaultProviderRequestID
		cac.mutation.SetProviderRequestID(v)
	}
	if _, ok := cac.mutation.OperationID(); !ok {
		v := computeallocation.DefaultOperationID
		cac.mutation.SetOperationID(v)
	}
	if _, ok := cac.mutation.Status(); !ok {
		v := computeallocation.DefaultStatus
		cac.mutation.SetStatus(v)
	}
	if _, ok := cac.mutation.DesiredStatus(); !ok {
		v := computeallocation.DefaultDesiredStatus
		cac.mutation.SetDesiredStatus(v)
	}
	if _, ok := cac.mutation.ProviderStatus(); !ok {
		v := computeallocation.DefaultProviderStatus
		cac.mutation.SetProviderStatus(v)
	}
	if _, ok := cac.mutation.LastProviderSyncAt(); !ok {
		v := computeallocation.DefaultLastProviderSyncAt
		cac.mutation.SetLastProviderSyncAt(v)
	}
	if _, ok := cac.mutation.LastProviderSyncError(); !ok {
		v := computeallocation.DefaultLastProviderSyncError
		cac.mutation.SetLastProviderSyncError(v)
	}
	if _, ok := cac.mutation.ExternalDeletedAt(); !ok {
		v := computeallocation.DefaultExternalDeletedAt
		cac.mutation.SetExternalDeletedAt(v)
	}
	if _, ok := cac.mutation.BillingStatus(); !ok {
		v := computeallocation.DefaultBillingStatus
		cac.mutation.SetBillingStatus(v)
	}
	if _, ok := cac.mutation.PricingVersion(); !ok {
		v := computeallocation.DefaultPricingVersion
		cac.mutation.SetPricingVersion(v)
	}
	if _, ok := cac.mutation.BillingOperationID(); !ok {
		v := computeallocation.DefaultBillingOperationID
		cac.mutation.SetBillingOperationID(v)
	}
	if _, ok := cac.mutation.BillingStateJSON(); !ok {
		v := computeallocation.DefaultBillingStateJSON
		cac.mutation.SetBillingStateJSON(v)
	}
	if _, ok := cac.mutation.EvidenceID(); !ok {
		v := computeallocation.DefaultEvidenceID
		cac.mutation.SetEvidenceID(v)
	}
	if _, ok := cac.mutation.CvmInstanceID(); !ok {
		v := computeallocation.DefaultCvmInstanceID
		cac.mutation.SetCvmInstanceID(v)
	}
	if _, ok := cac.mutation.InstanceID(); !ok {
		v := computeallocation.DefaultInstanceID
		cac.mutation.SetInstanceID(v)
	}
	if _, ok := cac.mutation.NodeName(); !ok {
		v := computeallocation.DefaultNodeName
		cac.mutation.SetNodeName(v)
	}
	if _, ok := cac.mutation.MachineName(); !ok {
		v := computeallocation.DefaultMachineName
		cac.mutation.SetMachineName(v)
	}
	if _, ok := cac.mutation.CPU(); !ok {
		v := computeallocation.DefaultCPU
		cac.mutation.SetCPU(v)
	}
	if _, ok := cac.mutation.MemoryGB(); !ok {
		v := computeallocation.DefaultMemoryGB
		cac.mutation.SetMemoryGB(v)
	}
	if _, ok := cac.mutation.DiskGB(); !ok {
		v := computeallocation.DefaultDiskGB
		cac.mutation.SetDiskGB(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cac *ComputeAllocationCreate) check() error {
	if _, ok := cac.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ComputeAllocation.created_at"`)}
	}
	if _, ok := cac.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ComputeAllocation.updated_at"`)}
	}
	if _, ok := cac.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "ComputeAllocation.account_id"`)}
	}
	if v, ok := cac.mutation.AccountID(); ok {
		if err := computeallocation.AccountIDValidator(v); err != nil {
			return &ValidationError{Name: "account_id", err: fmt.Errorf(`ent: validator failed for field "ComputeAllocation.account_id": %w`, err)}
		}
	}
	if _, ok := cac.mutation.OwnerUserID(); !ok {
		return &ValidationError{Name: "owner_user_id", err: errors.New(`ent: missing required field "ComputeAllocation.owner_user_id"`)}
	}
	if _, ok := cac.mutation.WorkspaceID(); !ok {
		return &ValidationError{Name: "workspace_id", err: errors.New(`ent: missing required field "ComputeAllocation.workspace_id"`)}
	}
	if _, ok := cac.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ComputeAllocation.name"`)}
	}
	if _, ok := cac.mutation.PackageID(); !ok {
		return &ValidationError{Name: "package_id", err: errors.New(`ent: missing required field "ComputeAllocation.package_id"`)}
	}
	if _, ok := cac.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "ComputeAllocation.provider"`)}
	}
	if _, ok := cac.mutation.ProviderResourceID(); !ok {
		return &ValidationError{Name: "provider_resource_id", err: errors.New(`ent: missing required field "ComputeAllocation.provider_resource_id"`)}
	}
	if _, ok := cac.mutation.ProviderRequestID(); !ok {
		return &ValidationError{Name: "provider_request_id", err: errors.New(`ent: missing required field "ComputeAllocation.provider_request_id"`)}
	}
	if _, ok := cac.mutation.OperationID(); !ok {
		return &ValidationError{Name: "operation_id", err: errors.New(`ent: missing required field "ComputeAllocation.operation_id"`)}
	}
	if _, ok := cac.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ComputeAllocation.status"`)}
	}
	if _, ok := cac.mutation.DesiredStatus(); !ok {
		return &ValidationError{Name: "desired_status", err: errors.New(`ent: missing required field "ComputeAllocation.desired_status"`)}
	}
	if _, ok := cac.mutation.ProviderStatus(); !ok {
		return &ValidationError{Name: "provider_status", err: errors.New(`ent: missing required field "ComputeAllocation.provider_status"`)}
	}
	if _, ok := cac.mutation.LastProviderSyncAt(); !ok {
		return &ValidationError{Name: "last_provider_sync_at", err: errors.New(`ent: missing required field "ComputeAllocation.last_provider_sync_at"`)}
	}
	if _, ok := cac.mutation.LastProviderSyncError(); !ok {
		return &ValidationError{Name: "last_provider_sync_error", err: errors.New(`ent: missing required field "ComputeAllocation.last_provider_sync_error"`)}
	}
	if _, ok := cac.mutation.ExternalDeletedAt(); !ok {
		return &ValidationError{Name: "external_deleted_at", err: errors.New(`ent: missing required field "ComputeAllocation.external_deleted_at"`)}
	}
	if _, ok := cac.mutation.BillingStatus(); !ok {
		return &ValidationError{Name: "billing_status", err: errors.New(`ent: missing required field "ComputeAllocation.billing_status"`)}
	}
	if _, ok := cac.mutation.PricingVersion(); !ok {
		return &ValidationError{Name: "pricing_version", err: errors.New(`ent: missing required field "ComputeAllocation.pricing_version"`)}
	}
	if _, ok := cac.mutation.BillingOperationID(); !ok {
		return &ValidationError{Name: "billing_operation_id", err: errors.New(`ent: missing required field "ComputeAllocation.billing_operation_id"`)}
	}
	if _, ok := cac.mutation.BillingStateJSON(); !ok {
		return &ValidationError{Name: "billing_state_json", err: errors.New(`ent: missing required field "ComputeAllocation.billing_state_json"`)}
	}
	if _, ok := cac.mutation.EvidenceID(); !ok {
		return &ValidationError{Name: "evidence_id", err: errors.New(`ent: missing required field "ComputeAllocation.evidence_id"`)}
	}
	if _, ok := cac.mutation.CvmInstanceID(); !ok {
		return &ValidationError{Name: "cvm_instance_id", err: errors.New(`ent: missing required field "ComputeAllocation.cvm_instance_id"`)}
	}
	if _, ok := cac.mutation.InstanceID(); !ok {
		return &ValidationError{Name: "instance_id", err: errors.New(`ent: missing required field "ComputeAllocation.instance_id"`)}
	}
	if _, ok := cac.mutation.NodeName(); !ok {
		return &ValidationError{Name: "node_name", err: errors.New(`ent: missing required field "ComputeAllocation.node_name"`)}
	}
	if _, ok := cac.mutation.MachineName(); !ok {
		return &ValidationError{Name: "machine_name", err: errors.New(`ent: missing required field "ComputeAllocation.machine_name"`)}
	}
	if _, ok := cac.mutation.CPU(); !ok {
		return &ValidationError{Name: "cpu", err: errors.New(`ent: missing required field "ComputeAllocation.cpu"`)}
	}
	if _, ok := cac.mutation.MemoryGB(); !ok {
		return &ValidationError{Name: "memory_gb", err: errors.New(`ent: missing required field "ComputeAllocation.memory_gb"`)}
	}
	if _, ok := cac.mutation.DiskGB(); !ok {
		return &ValidationError{Name: "disk_gb", err: errors.New(`ent: missing required field "ComputeAllocation.disk_gb"`)}
	}
	if v, ok := cac.mutation.ID(); ok {
		if err := computeallocation.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "ComputeAllocation.id": %w`, err)}
		}
	}
	return nil
}

func (cac *ComputeAllocationCreate) sqlSave(ctx context.Context) (*ComputeAllocation, error) {
	if err := cac.check(); err != nil {
		return nil, err
	}
	_node, _spec := cac.createSpec()
	if err := sqlgraph.CreateNode(ctx, cac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ComputeAllocation.ID type: %T", _spec.ID.Value)
		}
	}
	cac.mutation.id = &_node.ID
	cac.mutation.done = true
	return _node, nil
}

func (cac *ComputeAllocationCreate) createSpec() (*ComputeAllocation, *sqlgraph.CreateSpec) {
	var (
		_node = &ComputeAllocation{config: cac.config}
		_spec = sqlgraph.NewCreateSpec(computeallocation.Table, sqlgraph.NewFieldSpec(computeallocation.FieldID, field.TypeString))
	)
	if id, ok := cac.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := cac.mutation.CreatedAt(); ok {
		_spec.SetField(computeallocation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := cac.mutation.UpdatedAt(); ok {
		_spec.SetField(computeallocation.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := cac.mutation.AccountID(); ok {
		_spec.SetField(computeallocation.FieldAccountID, field.TypeString, value)
		_node.AccountID = value
	}
	if value, ok := cac.mutation.OwnerUserID(); ok {
		_spec.SetField(computeallocation.FieldOwnerUserID, field.TypeString, value)
		_node.OwnerUserID = value
	}
	if value, ok := cac.mutation.WorkspaceID(); ok {
		_spec.SetField(computeallocation.FieldWorkspaceID, field.TypeString, value)
		_node.WorkspaceID = value
	}
	if value, ok := cac.mutation.Name(); ok {
		_spec.SetField(computeallocation.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := cac.mutation.PackageID(); ok {
		_spec.SetField(computeallocation.FieldPackageID, field.TypeString, value)
		_node.PackageID = value
	}
	if value, ok := cac.mutation.Provider(); ok {
		_spec.SetField(computeallocation.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := cac.mutation.ProviderResourceID(); ok {
		_spec.SetField(computeallocation.FieldProviderResourceID, field.TypeString, value)
		_node.ProviderResourceID = value
	}
	if value, ok := cac.mutation.ProviderRequestID(); ok {
		_spec.SetField(computeallocation.FieldProviderRequestID, field.TypeString, value)
		_node.ProviderRequestID = value
	}
	if value, ok := cac.mutation.OperationID(); ok {
		_spec.SetField(computeallocation.FieldOperationID, field.TypeString, value)
		_node.OperationID = value
	}
	if value, ok := cac.mutation.Status(); ok {
		_spec.SetField(computeallocation.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := cac.mutation.DesiredStatus(); ok {
		_spec.SetField(computeallocation.FieldDesiredStatus, field.TypeString, value)
		_node.DesiredStatus = value
	}
	if value, ok := cac.mutation.ProviderStatus(); ok {
		_spec.SetField(computeallocation.FieldProviderStatus, field.TypeString, value)
		_node.ProviderStatus = value
	}
	if value, ok := cac.mutation.LastProviderSyncAt(); ok {
		_spec.SetField(computeallocation.FieldLastProviderSyncAt, field.TypeString, value)
		_node.LastProviderSyncAt = value
	}
	if value, ok := cac.mutation.LastProviderSyncError(); ok {
		_spec.SetField(computeallocation.FieldLastProviderSyncError, field.TypeString, value)
		_node.LastProviderSyncError = value
	}
	if value, ok := cac.mutation.ExternalDeletedAt(); ok {
		_spec.SetField(computeallocation.FieldExternalDeletedAt, field.TypeString, value)
		_node.ExternalDeletedAt = value
	}
	if value, ok := cac.mutation.BillingStatus(); ok {
		_spec.SetField(computeallocation.FieldBillingStatus, field.TypeString, value)
		_node.BillingStatus = value
	}
	if value, ok := cac.mutation.PricingVersion(); ok {
		_spec.SetField(computeallocation.FieldPricingVersion, field.TypeString, value)
		_node.PricingVersion = value
	}
	if value, ok := cac.mutation.BillingOperationID(); ok {
		_spec.SetField(computeallocation.FieldBillingOperationID, field.TypeString, value)
		_node.BillingOperationID = value
	}
	if value, ok := cac.mutation.BillingStateJSON(); ok {
		_spec.SetField(computeallocation.FieldBillingStateJSON, field.TypeString, value)
		_node.BillingStateJSON = value
	}
	if value, ok := cac.mutation.EvidenceID(); ok {
		_spec.SetField(computeallocation.FieldEvidenceID, field.TypeString, value)
		_node.EvidenceID = value
	}
	if value, ok := cac.mutation.CvmInstanceID(); ok {
		_spec.SetField(computeallocation.FieldCvmInstanceID, field.TypeString, value)
		_node.CvmInstanceID = value
	}
	if value, ok := cac.mutation.InstanceID(); ok {
		_spec.SetField(computeallocation.FieldInstanceID, field.TypeString, value)
		_node.InstanceID = value
	}
	if value, ok := cac.mutation.NodeName(); ok {
		_spec.SetField(computeallocation.FieldNodeName, field.TypeString, value)
		_node.NodeName = value
	}
	if value, ok := cac.mutation.MachineName(); ok {
		_spec.SetField(computeallocation.FieldMachineName, field.TypeString, value)
		_node.MachineName = value
	}
	if value, ok := cac.mutation.CPU(); ok {
		_spec.SetField(computeallocation.FieldCPU, field.TypeFloat64, value)
		_node.CPU = value
	}
	if value, ok := cac.mutation.MemoryGB(); ok {
		_spec.SetField(computeallocation.FieldMemoryGB, field.TypeFloat64, value)
		_node.MemoryGB = value
	}
	if value, ok := cac.mutation.DiskGB(); ok {
		_spec.SetField(computeallocation.FieldDiskGB, field.TypeFloat64, value)
		_node.DiskGB = value
	}
	return _node, _spec
}

// ComputeAllocationCreateBulk is the builder for creating many ComputeAllocation entities in bulk.
type ComputeAllocationCreateBulk struct {
	config
	err      error
	builders []*ComputeAllocationCreate
}

// Save creates the ComputeAllocation entities in the database.
func (cacb *ComputeAllocationCreateBulk) Save(ctx context.Context) ([]*ComputeAllocation, error) {
	if cacb.err != nil {
		return nil, cacb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(cacb.builders))
	nodes := make([]*ComputeAllocation, len(cacb.builders))
	mutators := make([]Mutator, len(cacb.builders))
	for i := range cacb.builders {
		func(i int, root context.Context) {
			builder := cacb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ComputeAllocationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, cacb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, cacb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, cacb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (cacb *ComputeAllocationCreateBulk) SaveX(ctx context.Context) []*ComputeAllocation {
	v, err := cacb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cacb *ComputeAllocationCreateBulk) Exec(ctx context.Context) error {
	_, err := cacb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cacb *ComputeAllocationCreateBulk) ExecX(ctx context.Context) {
	if err := cacb.Exec(ctx); err != nil {
		panic(err)
	}
}
