// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"opl-cloud/services/control-plane/ent/executionrequest"
	"opl-cloud/services/control-plane/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ExecutionRequestQuery is the builder for querying ExecutionRequest entities.
type ExecutionRequestQuery struct {
	config
	ctx        *QueryContext
	order      []executionrequest.OrderOption
	inters     []Interceptor
	predicates []predicate.ExecutionRequest
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ExecutionRequestQuery builder.
func (erq *ExecutionRequestQuery) Where(ps ...predicate.ExecutionRequest) *ExecutionRequestQuery {
	erq.predicates = append(erq.predicates, ps...)
	return erq
}

// Limit the number of records to be returned by this query.
func (erq *ExecutionRequestQuery) Limit(limit int) *ExecutionRequestQuery {
	erq.ctx.Limit = &limit
	return erq
}

// Offset to start from.
func (erq *ExecutionRequestQuery) Offset(offset int) *ExecutionRequestQuery {
	erq.ctx.Offset = &offset
	return erq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (erq *ExecutionRequestQuery) Unique(unique bool) *ExecutionRequestQuery {
	erq.ctx.Unique = &unique
	return erq
}

// Order specifies how the records should be ordered.
func (erq *ExecutionRequestQuery) Order(o ...executionrequest.OrderOption) *ExecutionRequestQuery {
	erq.order = append(erq.order, o...)
	return erq
}

// First returns the first ExecutionRequest entity from the query.
// Returns a *NotFoundError when no ExecutionRequest was found.
func (erq *ExecutionRequestQuery) First(ctx context.Context) (*ExecutionRequest, error) {
	nodes, err := erq.Limit(1).All(setContextOp(ctx, erq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{executionrequest.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (erq *ExecutionRequestQuery) FirstX(ctx context.Context) *ExecutionRequest {
	node, err := erq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ExecutionRequest ID from the query.
// Returns a *NotFoundError when no ExecutionRequest ID was found.
func (erq *ExecutionRequestQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = erq.Limit(1).IDs(setContextOp(ctx, erq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{executionrequest.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (erq *ExecutionRequestQuery) FirstIDX(ctx context.Context) string {
	id, err := erq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ExecutionRequest entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ExecutionRequest entity is found.
// Returns a *NotFoundError when no ExecutionRequest entities are found.
func (erq *ExecutionRequestQuery) Only(ctx context.Context) (*ExecutionRequest, error) {
	nodes, err := erq.Limit(2).All(setContextOp(ctx, erq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{executionrequest.Label}
	default:
		return nil, &NotSingularError{executionrequest.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (erq *ExecutionRequestQuery) OnlyX(ctx context.Context) *ExecutionRequest {
	node, err := erq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ExecutionRequest ID in the query.
// Returns a *NotSingularError when more than one ExecutionRequest ID is found.
// Returns a *NotFoundError when no entities are found.
func (erq *ExecutionRequestQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = erq.Limit(2).IDs(setContextOp(ctx, erq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{executionrequest.Label}
	default:
		err = &NotSingularError{executionrequest.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (erq *ExecutionRequestQuery) OnlyIDX(ctx context.Context) string {
	id, err := erq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ExecutionRequests.
func (erq *ExecutionRequestQuery) All(ctx context.Context) ([]*ExecutionRequest, error) {
	ctx = setContextOp(ctx, erq.ctx, "All")
	if err := erq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ExecutionRequest, *ExecutionRequestQuery]()
	return withInterceptors[[]*ExecutionRequest](ctx, erq, qr, erq.inters)
}

// AllX is like All, but panics if an error occurs.
func (erq *ExecutionRequestQuery) AllX(ctx context.Context) []*ExecutionRequest {
	nodes, err := erq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ExecutionRequest IDs.
func (erq *ExecutionRequestQuery) IDs(ctx context.Context) (ids []string, err error) {
	if erq.ctx.Unique == nil && erq.path != nil {
		erq.Unique(true)
	}
	ctx = setContextOp(ctx, erq.ctx, "IDs")
	if err = erq.Select(executionrequest.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (erq *ExecutionRequestQuery) IDsX(ctx context.Context) []string {
	ids, err := erq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (erq *ExecutionRequestQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, erq.ctx, "Count")
	if err := erq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, erq, querierCount[*ExecutionRequestQuery](), erq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (erq *ExecutionRequestQuery) CountX(ctx context.Context) int {
	count, err := erq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (erq *ExecutionRequestQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, erq.ctx, "Exist")
	switch _, err := erq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (erq *ExecutionRequestQuery) ExistX(ctx context.Context) bool {
	exist, err := erq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ExecutionRequestQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (erq *ExecutionRequestQuery) Clone() *ExecutionRequestQuery {
	if erq == nil {
		return nil
	}
	return &ExecutionRequestQuery{
		config:     erq.config,
		ctx:        erq.ctx.Clone(),
		order:      append([]executionrequest.OrderOption{}, erq.order...),
		inters:     append([]Interceptor{}, erq.inters...),
		predicates: append([]predicate.ExecutionRequest{}, erq.predicates...),
		// clone intermediate query.
		sql:  erq.sql.Clone(),
		path: erq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ExecutionRequest.Query().
//		GroupBy(executionrequest.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (erq *ExecutionRequestQuery) GroupBy(field string, fields ...string) *ExecutionRequestGroupBy {
	erq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ExecutionRequestGroupBy{build: erq}
	grbuild.flds = &erq.ctx.Fields
	grbuild.label = executionrequest.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.ExecutionRequest.Query().
//		Select(executionrequest.FieldCreatedAt).
//		Scan(ctx, &v)
func (erq *ExecutionRequestQuery) Select(fields ...string) *ExecutionRequestSelect {
	erq.ctx.Fields = append(erq.ctx.Fields, fields...)
	sbuild := &ExecutionRequestSelect{ExecutionRequestQuery: erq}
	sbuild.label = executionrequest.Label
	sbuild.flds, sbuild.scan = &erq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ExecutionRequestSelect configured with the given aggregations.
func (erq *ExecutionRequestQuery) Aggregate(fns ...AggregateFunc) *ExecutionRequestSelect {
	return erq.Select().Aggregate(fns...)
}

func (erq *ExecutionRequestQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range erq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, erq); err != nil {
				return err
			}
		}
	}
	for _, f := range erq.ctx.Fields {
		if !executionrequest.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if erq.path != nil {
		prev, err := erq.path(ctx)
		if err != nil {
			return err
		}
		erq.sql = prev
	}
	return nil
}

func (erq *ExecutionRequestQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ExecutionRequest, error) {
	var (
		nodes = []*ExecutionRequest{}
		_spec = erq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ExecutionRequest).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ExecutionRequest{config: erq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, erq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (erq *ExecutionRequestQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := erq.querySpec()
	_spec.Node.Columns = erq.ctx.Fields
	if len(erq.ctx.Fields) > 0 {
		_spec.Unique = erq.ctx.Unique != nil && *erq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, erq.driver, _spec)
}

func (erq *ExecutionRequestQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(executionrequest.Table, executionrequest.Columns, sqlgraph.NewFieldSpec(executionrequest.FieldID, field.TypeString))
	_spec.From = erq.sql
	if unique := erq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if erq.path != nil {
		_spec.Unique = true
	}
	if fields := erq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, executionrequest.FieldID)
		for i := range fields {
			if fields[i] != executionrequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := erq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := erq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := erq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := erq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (erq *ExecutionRequestQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(erq.driver.Dialect())
	t1 := builder.Table(executionrequest.Table)
	columns := erq.ctx.Fields
	if len(columns) == 0 {
		columns = executionrequest.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if erq.sql != nil {
		selector = erq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if erq.ctx.Unique != nil && *erq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range erq.predicates {
		p(selector)
	}
	for _, p := range erq.order {
		p(selector)
	}
	if offset := erq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := erq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ExecutionRequestGroupBy is the group-by builder for ExecutionRequest entities.
type ExecutionRequestGroupBy struct {
	selector
	build *ExecutionRequestQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ergb *ExecutionRequestGroupBy) Aggregate(fns ...AggregateFunc) *ExecutionRequestGroupBy {
	ergb.fns = append(ergb.fns, fns...)
	return ergb
}

// Scan applies the selector query and scans the result into the given value.
func (ergb *ExecutionRequestGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ergb.build.ctx, "GroupBy")
	if err := ergb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ExecutionRequestQuery, *ExecutionRequestGroupBy](ctx, ergb.build, ergb, ergb.build.inters, v)
}

func (ergb *ExecutionRequestGroupBy) sqlScan(ctx context.Context, root *ExecutionRequestQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ergb.fns))
	for _, fn := range ergb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ergb.flds)+len(ergb.fns))
		for _, f := range *ergb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ergb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ergb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ExecutionRequestSelect is the builder for selecting fields of ExecutionRequest entities.
type ExecutionRequestSelect struct {
	*ExecutionRequestQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ers *ExecutionRequestSelect) Aggregate(fns ...AggregateFunc) *ExecutionRequestSelect {
	ers.fns = append(ers.fns, fns...)
	return ers
}

// Scan applies the selector query and scans the result into the given value.
func (ers *ExecutionRequestSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ers.ctx, "Select")
	if err := ers.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ExecutionRequestQuery, *ExecutionRequestSelect](ctx, ers.ExecutionRequestQuery, ers, ers.inters, v)
}

func (ers *ExecutionRequestSelect) sqlScan(ctx context.Context, root *ExecutionRequestQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ers.fns))
	for _, fn := range ers.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ers.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ers.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
