// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"opl-cloud/services/control-plane/ent/ledgerprojection"
	"opl-cloud/services/control-plane/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LedgerProjectionQuery is the builder for querying LedgerProjection entities.
type LedgerProjectionQuery struct {
	config
	ctx        *QueryContext
	order      []ledgerprojection.OrderOption
	inters     []Interceptor
	predicates []predicate.LedgerProjection
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LedgerProjectionQuery builder.
func (lpq *LedgerProjectionQuery) Where(ps ...predicate.LedgerProjection) *LedgerProjectionQuery {
	lpq.predicates = append(lpq.predicates, ps...)
	return lpq
}

// Limit the number of records to be returned by this query.
func (lpq *LedgerProjectionQuery) Limit(limit int) *LedgerProjectionQuery {
	lpq.ctx.Limit = &limit
	return lpq
}

// Offset to start from.
func (lpq *LedgerProjectionQuery) Offset(offset int) *LedgerProjectionQuery {
	lpq.ctx.Offset = &offset
	return lpq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (lpq *LedgerProjectionQuery) Unique(unique bool) *LedgerProjectionQuery {
	lpq.ctx.Unique = &unique
	return lpq
}

// Order specifies how the records should be ordered.
func (lpq *LedgerProjectionQuery) Order(o ...ledgerprojection.OrderOption) *LedgerProjectionQuery {
	lpq.order = append(lpq.order, o...)
	return lpq
}

// First returns the first LedgerProjection entity from the query.
// Returns a *NotFoundError when no LedgerProjection was found.
func (lpq *LedgerProjectionQuery) First(ctx context.Context) (*LedgerProjection, error) {
	nodes, err := lpq.Limit(1).All(setContextOp(ctx, lpq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{ledgerprojection.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (lpq *LedgerProjectionQuery) FirstX(ctx context.Context) *LedgerProjection {
	node, err := lpq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first LedgerProjection ID from the query.
// Returns a *NotFoundError when no LedgerProjection ID was found.
func (lpq *LedgerProjectionQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = lpq.Limit(1).IDs(setContextOp(ctx, lpq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{ledgerprojection.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (lpq *LedgerProjectionQuery) FirstIDX(ctx context.Context) string {
	id, err := lpq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single LedgerProjection entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one LedgerProjection entity is found.
// Returns a *NotFoundError when no LedgerProjection entities are found.
func (lpq *LedgerProjectionQuery) Only(ctx context.Context) (*LedgerProjection, error) {
	nodes, err := lpq.Limit(2).All(setContextOp(ctx, lpq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{ledgerprojection.Label}
	default:
		return nil, &NotSingularError{ledgerprojection.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (lpq *LedgerProjectionQuery) OnlyX(ctx context.Context) *LedgerProjection {
	node, err := lpq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only LedgerProjection ID in the query.
// Returns a *NotSingularError when more than one LedgerProjection ID is found.
// Returns a *NotFoundError when no entities are found.
func (lpq *LedgerProjectionQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = lpq.Limit(2).IDs(setContextOp(ctx, lpq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{ledgerprojection.Label}
	default:
		err = &NotSingularError{ledgerprojection.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (lpq *LedgerProjectionQuery) OnlyIDX(ctx context.Context) string {
	id, err := lpq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of LedgerProjections.
func (lpq *LedgerProjectionQuery) All(ctx context.Context) ([]*LedgerProjection, error) {
	ctx = setContextOp(ctx, lpq.ctx, "All")
	if err := lpq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*LedgerProjection, *LedgerProjectionQuery]()
	return withInterceptors[[]*LedgerProjection](ctx, lpq, qr, lpq.inters)
}

// AllX is like All, but panics if an error occurs.
func (lpq *LedgerProjectionQuery) AllX(ctx context.Context) []*LedgerProjection {
	nodes, err := lpq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of LedgerProjection IDs.
func (lpq *LedgerProjectionQuery) IDs(ctx context.Context) (ids []string, err error) {
	if lpq.ctx.Unique == nil && lpq.path != nil {
		lpq.Unique(true)
	}
	ctx = setContextOp(ctx, lpq.ctx, "IDs")
	if err = lpq.Select(ledgerprojection.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (lpq *LedgerProjectionQuery) IDsX(ctx context.Context) []string {
	ids, err := lpq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (lpq *LedgerProjectionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, lpq.ctx, "Count")
	if err := lpq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, lpq, querierCount[*LedgerProjectionQuery](), lpq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (lpq *LedgerProjectionQuery) CountX(ctx context.Context) int {
	count, err := lpq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (lpq *LedgerProjectionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, lpq.ctx, "Exist")
	switch _, err := lpq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (lpq *LedgerProjectionQuery) ExistX(ctx context.Context) bool {
	exist, err := lpq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LedgerProjectionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (lpq *LedgerProjectionQuery) Clone() *LedgerProjectionQuery {
	if lpq == nil {
		return nil
	}
	return &LedgerProjectionQuery{
		config:     lpq.config,
		ctx:        lpq.ctx.Clone(),
		order:      append([]ledgerprojection.OrderOption{}, lpq.order...),
		inters:     append([]Interceptor{}, lpq.inters...),
		predicates: append([]predicate.LedgerProjection{}, lpq.predicates...),
		// clone intermediate query.
		sql:  lpq.sql.Clone(),
		path: lpq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.LedgerProjection.Query().
//		GroupBy(ledgerprojection.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (lpq *LedgerProjectionQuery) GroupBy(field string, fields ...string) *LedgerProjectionGroupBy {
	lpq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &LedgerProjectionGroupBy{build: lpq}
	grbuild.flds = &lpq.ctx.Fields
	grbuild.label = ledgerprojection.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.LedgerProjection.Query().
//		Select(ledgerprojection.FieldCreatedAt).
//		Scan(ctx, &v)
func (lpq *LedgerProjectionQuery) Select(fields ...string) *LedgerProjectionSelect {
	lpq.ctx.Fields = append(lpq.ctx.Fields, fields...)
	sbuild := &LedgerProjectionSelect{LedgerProjectionQuery: lpq}
	sbuild.label = ledgerprojection.Label
	sbuild.flds, sbuild.scan = &lpq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a LedgerProjectionSelect configured with the given aggregations.
func (lpq *LedgerProjectionQuery) Aggregate(fns ...AggregateFunc) *LedgerProjectionSelect {
	return lpq.Select().Aggregate(fns...)
}

func (lpq *LedgerProjectionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range lpq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, lpq); err != nil {
				return err
			}
		}
	}
	for _, f := range lpq.ctx.Fields {
		if !ledgerprojection.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if lpq.path != nil {
		prev, err := lpq.path(ctx)
		if err != nil {
			return err
		}
		lpq.sql = prev
	}
	return nil
}

func (lpq *LedgerProjectionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*LedgerProjection, error) {
	var (
		nodes = []*LedgerProjection{}
		_spec = lpq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*LedgerProjection).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &LedgerProjection{config: lpq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, lpq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (lpq *LedgerProjectionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := lpq.querySpec()
	_spec.Node.Columns = lpq.ctx.Fields
	if len(lpq.ctx.Fields) > 0 {
		_spec.Unique = lpq.ctx.Unique != nil && *lpq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, lpq.driver, _spec)
}

func (lpq *LedgerProjectionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(ledgerprojection.Table, ledgerprojection.Columns, sqlgraph.NewFieldSpec(ledgerprojection.FieldID, field.TypeString))
	_spec.From = lpq.sql
	if unique := lpq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if lpq.path != nil {
		_spec.Unique = true
	}
	if fields := lpq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ledgerprojection.FieldID)
		for i := range fields {
			if fields[i] != ledgerprojection.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := lpq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := lpq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := lpq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := lpq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (lpq *LedgerProjectionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(lpq.driver.Dialect())
	t1 := builder.Table(ledgerprojection.Table)
	columns := lpq.ctx.Fields
	if len(columns) == 0 {
		columns = ledgerprojection.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if lpq.sql != nil {
		selector = lpq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if lpq.ctx.Unique != nil && *lpq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range lpq.predicates {
		p(selector)
	}
	for _, p := range lpq.order {
		p(selector)
	}
	if offset := lpq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := lpq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LedgerProjectionGroupBy is the group-by builder for LedgerProjection entities.
type LedgerProjectionGroupBy struct {
	selector
	build *LedgerProjectionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (lpgb *LedgerProjectionGroupBy) Aggregate(fns ...AggregateFunc) *LedgerProjectionGroupBy {
	lpgb.fns = append(lpgb.fns, fns...)
	return lpgb
}

// Scan applies the selector query and scans the result into the given value.
func (lpgb *LedgerProjectionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, lpgb.build.ctx, "GroupBy")
	if err := lpgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LedgerProjectionQuery, *LedgerProjectionGroupBy](ctx, lpgb.build, lpgb, lpgb.build.inters, v)
}

func (lpgb *LedgerProjectionGroupBy) sqlScan(ctx context.Context, root *LedgerProjectionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(lpgb.fns))
	for _, fn := range lpgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*lpgb.flds)+len(lpgb.fns))
		for _, f := range *lpgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*lpgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lpgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// LedgerProjectionSelect is the builder for selecting fields of LedgerProjection entities.
type LedgerProjectionSelect struct {
	*LedgerProjectionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (lps *LedgerProjectionSelect) Aggregate(fns ...AggregateFunc) *LedgerProjectionSelect {
	lps.fns = append(lps.fns, fns...)
	return lps
}

// Scan applies the selector query and scans the result into the given value.
func (lps *LedgerProjectionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, lps.ctx, "Select")
	if err := lps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LedgerProjectionQuery, *LedgerProjectionSelect](ctx, lps.LedgerProjectionQuery, lps, lps.inters, v)
}

func (lps *LedgerProjectionSelect) sqlScan(ctx context.Context, root *LedgerProjectionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(lps.fns))
	for _, fn := range lps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*lps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
