// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"opl-cloud/services/control-plane/ent/predicate"
	"opl-cloud/services/control-plane/ent/pricingitem"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PricingItemUpdate is the builder for updating PricingItem entities.
type PricingItemUpdate struct {
	config
	hooks    []Hook
	mutation *PricingItemMutation
}

// Where appends a list predicates to the PricingItemUpdate builder.
func (piu *PricingItemUpdate) Where(ps ...predicate.PricingItem) *PricingItemUpdate {
	piu.mutation.Where(ps...)
	return piu
}

// SetCreatedAt sets the "created_at" field.
func (piu *PricingItemUpdate) SetCreatedAt(t time.Time) *PricingItemUpdate {
	piu.mutation.SetCreatedAt(t)
	return piu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (piu *PricingItemUpdate) SetNillableCreatedAt(t *time.Time) *PricingItemUpdate {
	if t != nil {
		piu.SetCreatedAt(*t)
	}
	return piu
}

// SetUpdatedAt sets the "updated_at" field.
func (piu *PricingItemUpdate) SetUpdatedAt(t time.Time) *PricingItemUpdate {
	piu.mutation.SetUpdatedAt(t)
	return piu
}

// SetCatalogVersion sets the "catalog_version" field.
func (piu *PricingItemUpdate) SetCatalogVersion(s string) *PricingItemUpdate {
	piu.mutation.SetCatalogVersion(s)
	return piu
}

// SetNillableCatalogVersion sets the "catalog_version" field if the given value is not nil.
func (piu *PricingItemUpdate) SetNillableCatalogVersion(s *string) *PricingItemUpdate {
	if s != nil {
		piu.SetCatalogVersion(*s)
	}
	return piu
}

// SetPackageID sets the "package_id" field.
func (piu *PricingItemUpdate) SetPackageID(s string) *PricingItemUpdate {
	piu.mutation.SetPackageID(s)
	return piu
}

// SetNillablePackageID sets the "package_id" field if the given value is not nil.
func (piu *PricingItemUpdate) SetNillablePackageID(s *string) *PricingItemUpdate {
	if s != nil {
		piu.SetPackageID(*s)
	}
	return piu
}

// SetResourceType sets the "resource_type" field.
func (piu *PricingItemUpdate) SetResourceType(s string) *PricingItemUpdate {
	piu.mutation.SetResourceType(s)
	return piu
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (piu *PricingItemUpdate) SetNillableResourceType(s *string) *PricingItemUpdate {
	if s != nil {
		piu.SetResourceType(*s)
	}
	return piu
}

// SetUnit sets the "unit" field.
func (piu *PricingItemUpdate) SetUnit(s string) *PricingItemUpdate {
	piu.mutation.SetUnit(s)
	return piu
}

// SetNillableUnit sets the "unit" field if the given value is not nil.
func (piu *PricingItemUpdate) SetNillableUnit(s *string) *PricingItemUpdate {
	if s != nil {
		piu.SetUnit(*s)
	}
	return piu
}

// SetUnitPrice sets the "unit_price" field.
func (piu *PricingItemUpdate) SetUnitPrice(f float64) *PricingItemUpdate {
	piu.mutation.ResetUnitPrice()
	piu.mutation.SetUnitPrice(f)
	return piu
}

// SetNillableUnitPrice sets the "unit_price" field if the given value is not nil.
func (piu *PricingItemUpdate) SetNillableUnitPrice(f *float64) *PricingItemUpdate {
	if f != nil {
		piu.SetUnitPrice(*f)
	}
	return piu
}

// AddUnitPrice adds f to the "unit_price" field.
func (piu *PricingItemUpdate) AddUnitPrice(f float64) *PricingItemUpdate {
	piu.mutation.AddUnitPrice(f)
	return piu
}

// SetUnitPriceCents sets the "unit_price_cents" field.
func (piu *PricingItemUpdate) SetUnitPriceCents(i int64) *PricingItemUpdate {
	piu.mutation.ResetUnitPriceCents()
	piu.mutation.SetUnitPriceCents(i)
	return piu
}

// SetNillableUnitPriceCents sets the "unit_price_cents" field if the given value is not nil.
func (piu *PricingItemUpdate) SetNillableUnitPriceCents(i *int64) *PricingItemUpdate {
	if i != nil {
		piu.SetUnitPriceCents(*i)
	}
	return piu
}

// AddUnitPriceCents adds i to the "unit_price_cents" field.
func (piu *PricingItemUpdate) AddUnitPriceCents(i int64) *PricingItemUpdate {
	piu.mutation.AddUnitPriceCents(i)
	return piu
}

// SetAvailable sets the "available" field.
func (piu *PricingItemUpdate) SetAvailable(b bool) *PricingItemUpdate {
	piu.mutation.SetAvailable(b)
	return piu
}

// SetNillableAvailable sets the "available" field if the given value is not nil.
func (piu *PricingItemUpdate) SetNillableAvailable(b *bool) *PricingItemUpdate {
	if b != nil {
		piu.SetAvailable(*b)
	}
	return piu
}

// SetName sets the "name" field.
func (piu *PricingItemUpdate) SetName(s string) *PricingItemUpdate {
	piu.mutation.SetName(s)
	return piu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (piu *PricingItemUpdate) SetNillableName(s *string) *PricingItemUpdate {
	if s != nil {
		piu.SetName(*s)
	}
	return piu
}

// SetServer sets the "server" field.
func (piu *PricingItemUpdate) SetServer(s string) *PricingItemUpdate {
	piu.mutation.SetServer(s)
	return piu
}

// SetNillableServer sets the "server" field if the given value is not nil.
func (piu *PricingItemUpdate) SetNillableServer(s *string) *PricingItemUpdate {
	if s != nil {
		piu.SetServer(*s)
	}
	return piu
}

// SetCPU sets the "cpu" field.
func (piu *PricingItemUpdate) SetCPU(f float64) *PricingItemUpdate {
	piu.mutation.ResetCPU()
	piu.mutation.SetCPU(f)
	return piu
}

// SetNillableCPU sets the "cpu" field if the given value is not nil.
func (piu *PricingItemUpdate) SetNillableCPU(f *float64) *PricingItemUpdate {
	if f != nil {
		piu.SetCPU(*f)
	}
	return piu
}

// AddCPU adds f to the "cpu" field.
func (piu *PricingItemUpdate) AddCPU(f float64) *PricingItemUpdate {
	piu.mutation.AddCPU(f)
	return piu
}

// SetMemoryGB sets the "memory_gb" field.
func (piu *PricingItemUpdate) SetMemoryGB(f float64) *PricingItemUpdate {
	piu.mutation.ResetMemoryGB()
	piu.mutation.SetMemoryGB(f)
	return piu
}

// SetNillableMemoryGB sets the "memory_gb" field if the given value is not nil.
func (piu *PricingItemUpdate) SetNillableMemoryGB(f *float64) *PricingItemUpdate {
	if f != nil {
		piu.SetMemoryGB(*f)
	}
	return piu
}

// AddMemoryGB adds f to the "memory_gb" field.
func (piu *PricingItemUpdate) AddMemoryGB(f float64) *PricingItemUpdate {
	piu.mutation.AddMemoryGB(f)
	return piu
}

// SetDiskGB sets the "disk_gb" field.
func (piu *PricingItemUpdate) SetDiskGB(f float64) *PricingItemUpdate {
	piu.mutation.ResetDiskGB()
	piu.mutation.SetDiskGB(f)
	return piu
}

// SetNillableDiskGB sets the "disk_gb" field if the given value is not nil.
func (piu *PricingItemUpdate) SetNillableDiskGB(f *float64) *PricingItemUpdate {
	if f != nil {
		piu.SetDiskGB(*f)
	}
	return piu
}

// AddDiskGB adds f to the "disk_gb" field.
func (piu *PricingItemUpdate) AddDiskGB(f float64) *PricingItemUpdate {
	piu.mutation.AddDiskGB(f)
	return piu
}

// Mutation returns the PricingItemMutation object of the builder.
func (piu *PricingItemUpdate) Mutation() *PricingItemMutation {
	return piu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (piu *PricingItemUpdate) Save(ctx context.Context) (int, error) {
	piu.defaults()
	return withHooks(ctx, piu.sqlSave, piu.mutation, piu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (piu *PricingItemUpdate) SaveX(ctx context.Context) int {
	affected, err := piu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (piu *PricingItemUpdate) Exec(ctx context.Context) error {
	_, err := piu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (piu *PricingItemUpdate) ExecX(ctx context.Context) {
	if err := piu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (piu *PricingItemUpdate) defaults() {
	if _, ok := piu.mutation.UpdatedAt(); !ok {
		v := pricingitem.UpdateDefaultUpdatedAt()
		piu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (piu *PricingItemUpdate) check() error {
	if v, ok := piu.mutation.CatalogVersion(); ok {
		if err := pricingitem.CatalogVersionValidator(v); err != nil {
			return &ValidationError{Name: "catalog_version", err: fmt.Errorf(`ent: validator failed for field "PricingItem.catalog_version": %w`, err)}
		}
	}
	if v, ok := piu.mutation.PackageID(); ok {
		if err := pricingitem.PackageIDValidator(v); err != nil {
			return &ValidationError{Name: "package_id", err: fmt.Errorf(`ent: validator failed for field "PricingItem.package_id": %w`, err)}
		}
	}
	if v, ok := piu.mutation.ResourceType(); ok {
		if err := pricingitem.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "PricingItem.resource_type": %w`, err)}
		}
	}
	if v, ok := piu.mutation.Unit(); ok {
		if err := pricingitem.UnitValidator(v); err != nil {
			return &ValidationError{Name: "unit", err: fmt.Errorf(`ent: validator failed for field "PricingItem.unit": %w`, err)}
		}
	}
	return nil
}

func (piu *PricingItemUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := piu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(pricingitem.Table, pricingitem.Columns, sqlgraph.NewFieldSpec(pricingitem.FieldID, field.TypeString))
	if ps := piu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := piu.mutation.CreatedAt(); ok {
		_spec.SetField(pricingitem.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := piu.mutation.UpdatedAt(); ok {
		_spec.SetField(pricingitem.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := piu.mutation.CatalogVersion(); ok {
		_spec.SetField(pricingitem.FieldCatalogVersion, field.TypeString, value)
	}
	if value, ok := piu.mutation.PackageID(); ok {
		_spec.SetField(pricingitem.FieldPackageID, field.TypeString, value)
	}
	if value, ok := piu.mutation.ResourceType(); ok {
		_spec.SetField(pricingitem.FieldResourceType, field.TypeString, value)
	}
	if value, ok := piu.mutation.Unit(); ok {
		_spec.SetField(pricingitem.FieldUnit, field.TypeString, value)
	}
	if value, ok := piu.mutation.UnitPrice(); ok {
		_spec.SetField(pricingitem.FieldUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := piu.mutation.AddedUnitPrice(); ok {
		_spec.AddField(pricingitem.FieldUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := piu.mutation.UnitPriceCents(); ok {
		_spec.SetField(pricingitem.FieldUnitPriceCents, field.TypeInt64, value)
	}
	if value, ok := piu.mutation.AddedUnitPriceCents(); ok {
		_spec.AddField(pricingitem.FieldUnitPriceCents, field.TypeInt64, value)
	}
	if value, ok := piu.mutation.Available(); ok {
		_spec.SetField(pricingitem.FieldAvailable, field.TypeBool, value)
	}
	if value, ok := piu.mutation.Name(); ok {
		_spec.SetField(pricingitem.FieldName, field.TypeString, value)
	}
	if value, ok := piu.mutation.Server(); ok {
		_spec.SetField(pricingitem.FieldServer, field.TypeString, value)
	}
	if value, ok := piu.mutation.CPU(); ok {
		_spec.SetField(pricingitem.FieldCPU, field.TypeFloat64, value)
	}
	if value, ok := piu.mutation.AddedCPU(); ok {
		_spec.AddField(pricingitem.FieldCPU, field.TypeFloat64, value)
	}
	if value, ok := piu.mutation.MemoryGB(); ok {
		_spec.SetField(pricingitem.FieldMemoryGB, field.TypeFloat64, value)
	}
	if value, ok := piu.mutation.AddedMemoryGB(); ok {
		_spec.AddField(pricingitem.FieldMemoryGB, field.TypeFloat64, value)
	}
	if value, ok := piu.mutation.DiskGB(); ok {
		_spec.SetField(pricingitem.FieldDiskGB, field.TypeFloat64, value)
	}
	if value, ok := piu.mutation.AddedDiskGB(); ok {
		_spec.AddField(pricingitem.FieldDiskGB, field.TypeFloat64, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, piu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pricingitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	piu.mutation.done = true
	return n, nil
}

// PricingItemUpdateOne is the builder for updating a single PricingItem entity.
type PricingItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PricingItemMutation
}

// SetCreatedAt sets the "created_at" field.
func (piuo *PricingItemUpdateOne) SetCreatedAt(t time.Time) *PricingItemUpdateOne {
	piuo.mutation.SetCreatedAt(t)
	return piuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (piuo *PricingItemUpdateOne) SetNillableCreatedAt(t *time.Time) *PricingItemUpdateOne {
	if t != nil {
		piuo.SetCreatedAt(*t)
	}
	return piuo
}

// SetUpdatedAt sets the "updated_at" field.
func (piuo *PricingItemUpdateOne) SetUpdatedAt(t time.Time) *PricingItemUpdateOne {
	piuo.mutation.SetUpdatedAt(t)
	return piuo
}

// SetCatalogVersion sets the "catalog_version" field.
func (piuo *PricingItemUpdateOne) SetCatalogVersion(s string) *PricingItemUpdateOne {
	piuo.mutation.SetCatalogVersion(s)
	return piuo
}

// SetNillableCatalogVersion sets the "catalog_version" field if the given value is not nil.
func (piuo *PricingItemUpdateOne) SetNillableCatalogVersion(s *string) *PricingItemUpdateOne {
	if s != nil {
		piuo.SetCatalogVersion(*s)
	}
	return piuo
}

// SetPackageID sets the "package_id" field.
func (piuo *PricingItemUpdateOne) SetPackageID(s string) *PricingItemUpdateOne {
	piuo.mutation.SetPackageID(s)
	return piuo
}

// SetNillablePackageID sets the "package_id" field if the given value is not nil.
func (piuo *PricingItemUpdateOne) SetNillablePackageID(s *string) *PricingItemUpdateOne {
	if s != nil {
		piuo.SetPackageID(*s)
	}
	return piuo
}

// SetResourceType sets the "resource_type" field.
func (piuo *PricingItemUpdateOne) SetResourceType(s string) *PricingItemUpdateOne {
	piuo.mutation.SetResourceType(s)
	return piuo
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (piuo *PricingItemUpdateOne) SetNillableResourceType(s *string) *PricingItemUpdateOne {
	if s != nil {
		piuo.SetResourceType(*s)
	}
	return piuo
}

// SetUnit sets the "unit" field.
func (piuo *PricingItemUpdateOne) SetUnit(s string) *PricingItemUpdateOne {
	piuo.mutation.SetUnit(s)
	return piuo
}

// SetNillableUnit sets the "unit" field if the given value is not nil.
func (piuo *PricingItemUpdateOne) SetNillableUnit(s *string) *PricingItemUpdateOne {
	if s != nil {
		piuo.SetUnit(*s)
	}
	return piuo
}

// SetUnitPrice sets the "unit_price" field.
func (piuo *PricingItemUpdateOne) SetUnitPrice(f float64) *PricingItemUpdateOne {
	piuo.mutation.ResetUnitPrice()
	piuo.mutation.SetUnitPrice(f)
	return piuo
}

// SetNillableUnitPrice sets the "unit_price" field if the given value is not nil.
func (piuo *PricingItemUpdateOne) SetNillableUnitPrice(f *float64) *PricingItemUpdateOne {
	if f != nil {
		piuo.SetUnitPrice(*f)
	}
	return piuo
}

// AddUnitPrice adds f to the "unit_price" field.
func (piuo *PricingItemUpdateOne) AddUnitPrice(f float64) *PricingItemUpdateOne {
	piuo.mutation.AddUnitPrice(f)
	return piuo
}

// SetUnitPriceCents sets the "unit_price_cents" field.
func (piuo *PricingItemUpdateOne) SetUnitPriceCents(i int64) *PricingItemUpdateOne {
	piuo.mutation.ResetUnitPriceCents()
	piuo.mutation.SetUnitPriceCents(i)
	return piuo
}

// SetNillableUnitPriceCents sets the "unit_price_cents" field if the given value is not nil.
func (piuo *PricingItemUpdateOne) SetNillableUnitPriceCents(i *int64) *PricingItemUpdateOne {
	if i != nil {
		piuo.SetUnitPriceCents(*i)
	}
	return piuo
}

// AddUnitPriceCents adds i to the "unit_price_cents" field.
func (piuo *PricingItemUpdateOne) AddUnitPriceCents(i int64) *PricingItemUpdateOne {
	piuo.mutation.AddUnitPriceCents(i)
	return piuo
}

// SetAvailable sets the "available" field.
func (piuo *PricingItemUpdateOne) SetAvailable(b bool) *PricingItemUpdateOne {
	piuo.mutation.SetAvailable(b)
	return piuo
}

// SetNillableAvailable sets the "available" field if the given value is not nil.
func (piuo *PricingItemUpdateOne) SetNillableAvailable(b *bool) *PricingItemUpdateOne {
	if b != nil {
		piuo.SetAvailable(*b)
	}
	return piuo
}

// SetName sets the "name" field.
func (piuo *PricingItemUpdateOne) SetName(s string) *PricingItemUpdateOne {
	piuo.mutation.SetName(s)
	return piuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (piuo *PricingItemUpdateOne) SetNillableName(s *string) *PricingItemUpdateOne {
	if s != nil {
		piuo.SetName(*s)
	}
	return piuo
}

// SetServer sets the "server" field.
func (piuo *PricingItemUpdateOne) SetServer(s string) *PricingItemUpdateOne {
	piuo.mutation.SetServer(s)
	return piuo
}

// SetNillableServer sets the "server" field if the given value is not nil.
func (piuo *PricingItemUpdateOne) SetNillableServer(s *string) *PricingItemUpdateOne {
	if s != nil {
		piuo.SetServer(*s)
	}
	return piuo
}

// SetCPU sets the "cpu" field.
func (piuo *PricingItemUpdateOne) SetCPU(f float64) *PricingItemUpdateOne {
	piuo.mutation.ResetCPU()
	piuo.mutation.SetCPU(f)
	return piuo
}

// SetNillableCPU sets the "cpu" field if the given value is not nil.
func (piuo *PricingItemUpdateOne) SetNillableCPU(f *float64) *PricingItemUpdateOne {
	if f != nil {
		piuo.SetCPU(*f)
	}
	return piuo
}

// AddCPU adds f to the "cpu" field.
func (piuo *PricingItemUpdateOne) AddCPU(f float64) *PricingItemUpdateOne {
	piuo.mutation.AddCPU(f)
	return piuo
}

// SetMemoryGB sets the "memory_gb" field.
func (piuo *PricingItemUpdateOne) SetMemoryGB(f float64) *PricingItemUpdateOne {
	piuo.mutation.ResetMemoryGB()
	piuo.mutation.SetMemoryGB(f)
	return piuo
}

// SetNillableMemoryGB sets the "memory_gb" field if the given value is not nil.
func (piuo *PricingItemUpdateOne) SetNillableMemoryGB(f *float64) *PricingItemUpdateOne {
	if f != nil {
		piuo.SetMemoryGB(*f)
	}
	return piuo
}

// AddMemoryGB adds f to the "memory_gb" field.
func (piuo *PricingItemUpdateOne) AddMemoryGB(f float64) *PricingItemUpdateOne {
	piuo.mutation.AddMemoryGB(f)
	return piuo
}

// SetDiskGB sets the "disk_gb" field.
func (piuo *PricingItemUpdateOne) SetDiskGB(f float64) *PricingItemUpdateOne {
	piuo.mutation.ResetDiskGB()
	piuo.mutation.SetDiskGB(f)
	return piuo
}

// SetNillableDiskGB sets the "disk_gb" field if the given value is not nil.
func (piuo *PricingItemUpdateOne) SetNillableDiskGB(f *float64) *PricingItemUpdateOne {
	if f != nil {
		piuo.SetDiskGB(*f)
	}
	return piuo
}

// AddDiskGB adds f to the "disk_gb" field.
func (piuo *PricingItemUpdateOne) AddDiskGB(f float64) *PricingItemUpdateOne {
	piuo.mutation.AddDiskGB(f)
	return piuo
}

// Mutation returns the PricingItemMutation object of the builder.
func (piuo *PricingItemUpdateOne) Mutation() *PricingItemMutation {
	return piuo.mutation
}

// Where appends a list predicates to the PricingItemUpdate builder.
func (piuo *PricingItemUpdateOne) Where(ps ...predicate.PricingItem) *PricingItemUpdateOne {
	piuo.mutation.Where(ps...)
	return piuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (piuo *PricingItemUpdateOne) Select(field string, fields ...string) *PricingItemUpdateOne {
	piuo.fields = append([]string{field}, fields...)
	return piuo
}

// Save executes the query and returns the updated PricingItem entity.
func (piuo *PricingItemUpdateOne) Save(ctx context.Context) (*PricingItem, error) {
	piuo.defaults()
	return withHooks(ctx, piuo.sqlSave, piuo.mutation, piuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (piuo *PricingItemUpdateOne) SaveX(ctx context.Context) *PricingItem {
	node, err := piuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (piuo *PricingItemUpdateOne) Exec(ctx context.Context) error {
	_, err := piuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (piuo *PricingItemUpdateOne) ExecX(ctx context.Context) {
	if err := piuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (piuo *PricingItemUpdateOne) defaults() {
	if _, ok := piuo.mutation.UpdatedAt(); !ok {
		v := pricingitem.UpdateDefaultUpdatedAt()
		piuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (piuo *PricingItemUpdateOne) check() error {
	if v, ok := piuo.mutation.CatalogVersion(); ok {
		if err := pricingitem.CatalogVersionValidator(v); err != nil {
			return &ValidationError{Name: "catalog_version", err: fmt.Errorf(`ent: validator failed for field "PricingItem.catalog_version": %w`, err)}
		}
	}
	if v, ok := piuo.mutation.PackageID(); ok {
		if err := pricingitem.PackageIDValidator(v); err != nil {
			return &ValidationError{Name: "package_id", err: fmt.Errorf(`ent: validator failed for field "PricingItem.package_id": %w`, err)}
		}
	}
	if v, ok := piuo.mutation.ResourceType(); ok {
		if err := pricingitem.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "PricingItem.resource_type": %w`, err)}
		}
	}
	if v, ok := piuo.mutation.Unit(); ok {
		if err := pricingitem.UnitValidator(v); err != nil {
			return &ValidationError{Name: "unit", err: fmt.Errorf(`ent: validator failed for field "PricingItem.unit": %w`, err)}
		}
	}
	return nil
}

func (piuo *PricingItemUpdateOne) sqlSave(ctx context.Context) (_node *PricingItem, err error) {
	if err := piuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pricingitem.Table, pricingitem.Columns, sqlgraph.NewFieldSpec(pricingitem.FieldID, field.TypeString))
	id, ok := piuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PricingItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := piuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pricingitem.FieldID)
		for _, f := range fields {
			if !pricingitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pricingitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := piuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := piuo.mutation.CreatedAt(); ok {
		_spec.SetField(pricingitem.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := piuo.mutation.UpdatedAt(); ok {
		_spec.SetField(pricingitem.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := piuo.mutation.CatalogVersion(); ok {
		_spec.SetField(pricingitem.FieldCatalogVersion, field.TypeString, value)
	}
	if value, ok := piuo.mutation.PackageID(); ok {
		_spec.SetField(pricingitem.FieldPackageID, field.TypeString, value)
	}
	if value, ok := piuo.mutation.ResourceType(); ok {
		_spec.SetField(pricingitem.FieldResourceType, field.TypeString, value)
	}
	if value, ok := piuo.mutation.Unit(); ok {
		_spec.SetField(pricingitem.FieldUnit, field.TypeString, value)
	}
	if value, ok := piuo.mutation.UnitPrice(); ok {
		_spec.SetField(pricingitem.FieldUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := piuo.mutation.AddedUnitPrice(); ok {
		_spec.AddField(pricingitem.FieldUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := piuo.mutation.UnitPriceCents(); ok {
		_spec.SetField(pricingitem.FieldUnitPriceCents, field.TypeInt64, value)
	}
	if value, ok := piuo.mutation.AddedUnitPriceCents(); ok {
		_spec.AddField(pricingitem.FieldUnitPriceCents, field.TypeInt64, value)
	}
	if value, ok := piuo.mutation.Available(); ok {
		_spec.SetField(pricingitem.FieldAvailable, field.TypeBool, value)
	}
	if value, ok := piuo.mutation.Name(); ok {
		_spec.SetField(pricingitem.FieldName, field.TypeString, value)
	}
	if value, ok := piuo.mutation.Server(); ok {
		_spec.SetField(pricingitem.FieldServer, field.TypeString, value)
	}
	if value, ok := piuo.mutation.CPU(); ok {
		_spec.SetField(pricingitem.FieldCPU, field.TypeFloat64, value)
	}
	if value, ok := piuo.mutation.AddedCPU(); ok {
		_spec.AddField(pricingitem.FieldCPU, field.TypeFloat64, value)
	}
	if value, ok := piuo.mutation.MemoryGB(); ok {
		_spec.SetField(pricingitem.FieldMemoryGB, field.TypeFloat64, value)
	}
	if value, ok := piuo.mutation.AddedMemoryGB(); ok {
		_spec.AddField(pricingitem.FieldMemoryGB, field.TypeFloat64, value)
	}
	if value, ok := piuo.mutation.DiskGB(); ok {
		_spec.SetField(pricingitem.FieldDiskGB, field.TypeFloat64, value)
	}
	if value, ok := piuo.mutation.AddedDiskGB(); ok {
		_spec.AddField(pricingitem.FieldDiskGB, field.TypeFloat64, value)
	}
	_node = &PricingItem{config: piuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, piuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pricingitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	piuo.mutation.done = true
	return _node, nil
}
