// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"opl-cloud/services/control-plane/ent/productione2erecord"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ProductionE2ERecord is the model entity for the ProductionE2ERecord schema.
type ProductionE2ERecord struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID string `json:"account_id,omitempty"`
	// WorkspaceID holds the value of the "workspace_id" field.
	WorkspaceID string `json:"workspace_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Result holds the value of the "result" field.
	Result string `json:"result,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason string `json:"reason,omitempty"`
	// URL holds the value of the "url" field.
	URL          string `json:"url,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProductionE2ERecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case productione2erecord.FieldID, productione2erecord.FieldAccountID, productione2erecord.FieldWorkspaceID, productione2erecord.FieldStatus, productione2erecord.FieldResult, productione2erecord.FieldReason, productione2erecord.FieldURL:
			values[i] = new(sql.NullString)
		case productione2erecord.FieldCreatedAt, productione2erecord.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProductionE2ERecord fields.
func (per *ProductionE2ERecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case productione2erecord.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				per.ID = value.String
			}
		case productione2erecord.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				per.CreatedAt = value.Time
			}
		case productione2erecord.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				per.UpdatedAt = value.Time
			}
		case productione2erecord.FieldAccountID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				per.AccountID = value.String
			}
		case productione2erecord.FieldWorkspaceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field workspace_id", values[i])
			} else if value.Valid {
				per.WorkspaceID = value.String
			}
		case productione2erecord.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				per.Status = value.String
			}
		case productione2erecord.FieldResult:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field result", values[i])
			} else if value.Valid {
				per.Result = value.String
			}
		case productione2erecord.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				per.Reason = value.String
			}
		case productione2erecord.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				per.URL = value.String
			}
		default:
			per.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProductionE2ERecord.
// This includes values selected through modifiers, order, etc.
func (per *ProductionE2ERecord) Value(name string) (ent.Value, error) {
	return per.selectValues.Get(name)
}

// Update returns a builder for updating this ProductionE2ERecord.
// Note that you need to call ProductionE2ERecord.Unwrap() before calling this method if this ProductionE2ERecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (per *ProductionE2ERecord) Update() *ProductionE2ERecordUpdateOne {
	return NewProductionE2ERecordClient(per.config).UpdateOne(per)
}

// Unwrap unwraps the ProductionE2ERecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (per *ProductionE2ERecord) Unwrap() *ProductionE2ERecord {
	_tx, ok := per.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProductionE2ERecord is not a transactional entity")
	}
	per.config.driver = _tx.drv
	return per
}

// String implements the fmt.Stringer.
func (per *ProductionE2ERecord) String() string {
	var builder strings.Builder
	builder.WriteString("ProductionE2ERecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", per.ID))
	builder.WriteString("created_at=")
	builder.WriteString(per.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(per.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(per.AccountID)
	builder.WriteString(", ")
	builder.WriteString("workspace_id=")
	builder.WriteString(per.WorkspaceID)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(per.Status)
	builder.WriteString(", ")
	builder.WriteString("result=")
	builder.WriteString(per.Result)
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(per.Reason)
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(per.URL)
	builder.WriteByte(')')
	return builder.String()
}

// ProductionE2ERecords is a parsable slice of ProductionE2ERecord.
type ProductionE2ERecords []*ProductionE2ERecord
