// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"opl-cloud/services/control-plane/ent/predicate"
	"opl-cloud/services/control-plane/ent/productione2erecord"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProductionE2ERecordQuery is the builder for querying ProductionE2ERecord entities.
type ProductionE2ERecordQuery struct {
	config
	ctx        *QueryContext
	order      []productione2erecord.OrderOption
	inters     []Interceptor
	predicates []predicate.ProductionE2ERecord
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProductionE2ERecordQuery builder.
func (perq *ProductionE2ERecordQuery) Where(ps ...predicate.ProductionE2ERecord) *ProductionE2ERecordQuery {
	perq.predicates = append(perq.predicates, ps...)
	return perq
}

// Limit the number of records to be returned by this query.
func (perq *ProductionE2ERecordQuery) Limit(limit int) *ProductionE2ERecordQuery {
	perq.ctx.Limit = &limit
	return perq
}

// Offset to start from.
func (perq *ProductionE2ERecordQuery) Offset(offset int) *ProductionE2ERecordQuery {
	perq.ctx.Offset = &offset
	return perq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (perq *ProductionE2ERecordQuery) Unique(unique bool) *ProductionE2ERecordQuery {
	perq.ctx.Unique = &unique
	return perq
}

// Order specifies how the records should be ordered.
func (perq *ProductionE2ERecordQuery) Order(o ...productione2erecord.OrderOption) *ProductionE2ERecordQuery {
	perq.order = append(perq.order, o...)
	return perq
}

// First returns the first ProductionE2ERecord entity from the query.
// Returns a *NotFoundError when no ProductionE2ERecord was found.
func (perq *ProductionE2ERecordQuery) First(ctx context.Context) (*ProductionE2ERecord, error) {
	nodes, err := perq.Limit(1).All(setContextOp(ctx, perq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{productione2erecord.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (perq *ProductionE2ERecordQuery) FirstX(ctx context.Context) *ProductionE2ERecord {
	node, err := perq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProductionE2ERecord ID from the query.
// Returns a *NotFoundError when no ProductionE2ERecord ID was found.
func (perq *ProductionE2ERecordQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = perq.Limit(1).IDs(setContextOp(ctx, perq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{productione2erecord.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (perq *ProductionE2ERecordQuery) FirstIDX(ctx context.Context) string {
	id, err := perq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProductionE2ERecord entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ProductionE2ERecord entity is found.
// Returns a *NotFoundError when no ProductionE2ERecord entities are found.
func (perq *ProductionE2ERecordQuery) Only(ctx context.Context) (*ProductionE2ERecord, error) {
	nodes, err := perq.Limit(2).All(setContextOp(ctx, perq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{productione2erecord.Label}
	default:
		return nil, &NotSingularError{productione2erecord.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (perq *ProductionE2ERecordQuery) OnlyX(ctx context.Context) *ProductionE2ERecord {
	node, err := perq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProductionE2ERecord ID in the query.
// Returns a *NotSingularError when more than one ProductionE2ERecord ID is found.
// Returns a *NotFoundError when no entities are found.
func (perq *ProductionE2ERecordQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = perq.Limit(2).IDs(setContextOp(ctx, perq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{productione2erecord.Label}
	default:
		err = &NotSingularError{productione2erecord.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (perq *ProductionE2ERecordQuery) OnlyIDX(ctx context.Context) string {
	id, err := perq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProductionE2ERecords.
func (perq *ProductionE2ERecordQuery) All(ctx context.Context) ([]*ProductionE2ERecord, error) {
	ctx = setContextOp(ctx, perq.ctx, "All")
	if err := perq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ProductionE2ERecord, *ProductionE2ERecordQuery]()
	return withInterceptors[[]*ProductionE2ERecord](ctx, perq, qr, perq.inters)
}

// AllX is like All, but panics if an error occurs.
func (perq *ProductionE2ERecordQuery) AllX(ctx context.Context) []*ProductionE2ERecord {
	nodes, err := perq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProductionE2ERecord IDs.
func (perq *ProductionE2ERecordQuery) IDs(ctx context.Context) (ids []string, err error) {
	if perq.ctx.Unique == nil && perq.path != nil {
		perq.Unique(true)
	}
	ctx = setContextOp(ctx, perq.ctx, "IDs")
	if err = perq.Select(productione2erecord.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (perq *ProductionE2ERecordQuery) IDsX(ctx context.Context) []string {
	ids, err := perq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (perq *ProductionE2ERecordQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, perq.ctx, "Count")
	if err := perq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, perq, querierCount[*ProductionE2ERecordQuery](), perq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (perq *ProductionE2ERecordQuery) CountX(ctx context.Context) int {
	count, err := perq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (perq *ProductionE2ERecordQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, perq.ctx, "Exist")
	switch _, err := perq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (perq *ProductionE2ERecordQuery) ExistX(ctx context.Context) bool {
	exist, err := perq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProductionE2ERecordQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (perq *ProductionE2ERecordQuery) Clone() *ProductionE2ERecordQuery {
	if perq == nil {
		return nil
	}
	return &ProductionE2ERecordQuery{
		config:     perq.config,
		ctx:        perq.ctx.Clone(),
		order:      append([]productione2erecord.OrderOption{}, perq.order...),
		inters:     append([]Interceptor{}, perq.inters...),
		predicates: append([]predicate.ProductionE2ERecord{}, perq.predicates...),
		// clone intermediate query.
		sql:  perq.sql.Clone(),
		path: perq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ProductionE2ERecord.Query().
//		GroupBy(productione2erecord.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (perq *ProductionE2ERecordQuery) GroupBy(field string, fields ...string) *ProductionE2ERecordGroupBy {
	perq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ProductionE2ERecordGroupBy{build: perq}
	grbuild.flds = &perq.ctx.Fields
	grbuild.label = productione2erecord.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.ProductionE2ERecord.Query().
//		Select(productione2erecord.FieldCreatedAt).
//		Scan(ctx, &v)
func (perq *ProductionE2ERecordQuery) Select(fields ...string) *ProductionE2ERecordSelect {
	perq.ctx.Fields = append(perq.ctx.Fields, fields...)
	sbuild := &ProductionE2ERecordSelect{ProductionE2ERecordQuery: perq}
	sbuild.label = productione2erecord.Label
	sbuild.flds, sbuild.scan = &perq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ProductionE2ERecordSelect configured with the given aggregations.
func (perq *ProductionE2ERecordQuery) Aggregate(fns ...AggregateFunc) *ProductionE2ERecordSelect {
	return perq.Select().Aggregate(fns...)
}

func (perq *ProductionE2ERecordQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range perq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, perq); err != nil {
				return err
			}
		}
	}
	for _, f := range perq.ctx.Fields {
		if !productione2erecord.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if perq.path != nil {
		prev, err := perq.path(ctx)
		if err != nil {
			return err
		}
		perq.sql = prev
	}
	return nil
}

func (perq *ProductionE2ERecordQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ProductionE2ERecord, error) {
	var (
		nodes = []*ProductionE2ERecord{}
		_spec = perq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ProductionE2ERecord).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ProductionE2ERecord{config: perq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, perq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (perq *ProductionE2ERecordQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := perq.querySpec()
	_spec.Node.Columns = perq.ctx.Fields
	if len(perq.ctx.Fields) > 0 {
		_spec.Unique = perq.ctx.Unique != nil && *perq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, perq.driver, _spec)
}

func (perq *ProductionE2ERecordQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(productione2erecord.Table, productione2erecord.Columns, sqlgraph.NewFieldSpec(productione2erecord.FieldID, field.TypeString))
	_spec.From = perq.sql
	if unique := perq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if perq.path != nil {
		_spec.Unique = true
	}
	if fields := perq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, productione2erecord.FieldID)
		for i := range fields {
			if fields[i] != productione2erecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := perq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := perq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := perq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := perq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (perq *ProductionE2ERecordQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(perq.driver.Dialect())
	t1 := builder.Table(productione2erecord.Table)
	columns := perq.ctx.Fields
	if len(columns) == 0 {
		columns = productione2erecord.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if perq.sql != nil {
		selector = perq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if perq.ctx.Unique != nil && *perq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range perq.predicates {
		p(selector)
	}
	for _, p := range perq.order {
		p(selector)
	}
	if offset := perq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := perq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ProductionE2ERecordGroupBy is the group-by builder for ProductionE2ERecord entities.
type ProductionE2ERecordGroupBy struct {
	selector
	build *ProductionE2ERecordQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pergb *ProductionE2ERecordGroupBy) Aggregate(fns ...AggregateFunc) *ProductionE2ERecordGroupBy {
	pergb.fns = append(pergb.fns, fns...)
	return pergb
}

// Scan applies the selector query and scans the result into the given value.
func (pergb *ProductionE2ERecordGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pergb.build.ctx, "GroupBy")
	if err := pergb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProductionE2ERecordQuery, *ProductionE2ERecordGroupBy](ctx, pergb.build, pergb, pergb.build.inters, v)
}

func (pergb *ProductionE2ERecordGroupBy) sqlScan(ctx context.Context, root *ProductionE2ERecordQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pergb.fns))
	for _, fn := range pergb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pergb.flds)+len(pergb.fns))
		for _, f := range *pergb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pergb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pergb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ProductionE2ERecordSelect is the builder for selecting fields of ProductionE2ERecord entities.
type ProductionE2ERecordSelect struct {
	*ProductionE2ERecordQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pers *ProductionE2ERecordSelect) Aggregate(fns ...AggregateFunc) *ProductionE2ERecordSelect {
	pers.fns = append(pers.fns, fns...)
	return pers
}

// Scan applies the selector query and scans the result into the given value.
func (pers *ProductionE2ERecordSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pers.ctx, "Select")
	if err := pers.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProductionE2ERecordQuery, *ProductionE2ERecordSelect](ctx, pers.ProductionE2ERecordQuery, pers, pers.inters, v)
}

func (pers *ProductionE2ERecordSelect) sqlScan(ctx context.Context, root *ProductionE2ERecordQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pers.fns))
	for _, fn := range pers.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pers.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pers.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
