// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"opl-cloud/services/control-plane/ent/projecttasksynchead"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ProjectTaskSyncHead is the model entity for the ProjectTaskSyncHead schema.
type ProjectTaskSyncHead struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind string `json:"kind,omitempty"`
	// OrganizationID holds the value of the "organization_id" field.
	OrganizationID string `json:"organization_id,omitempty"`
	// WorkspaceID holds the value of the "workspace_id" field.
	WorkspaceID string `json:"workspace_id,omitempty"`
	// ProjectID holds the value of the "project_id" field.
	ProjectID string `json:"project_id,omitempty"`
	// LocalAliasID holds the value of the "local_alias_id" field.
	LocalAliasID string `json:"local_alias_id,omitempty"`
	// Version holds the value of the "version" field.
	Version int64 `json:"version,omitempty"`
	// Status holds the value of the "status" field.
	Status       string `json:"status,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProjectTaskSyncHead) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case projecttasksynchead.FieldVersion:
			values[i] = new(sql.NullInt64)
		case projecttasksynchead.FieldID, projecttasksynchead.FieldKind, projecttasksynchead.FieldOrganizationID, projecttasksynchead.FieldWorkspaceID, projecttasksynchead.FieldProjectID, projecttasksynchead.FieldLocalAliasID, projecttasksynchead.FieldStatus:
			values[i] = new(sql.NullString)
		case projecttasksynchead.FieldCreatedAt, projecttasksynchead.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProjectTaskSyncHead fields.
func (ptsh *ProjectTaskSyncHead) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case projecttasksynchead.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				ptsh.ID = value.String
			}
		case projecttasksynchead.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ptsh.CreatedAt = value.Time
			}
		case projecttasksynchead.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				ptsh.UpdatedAt = value.Time
			}
		case projecttasksynchead.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				ptsh.Kind = value.String
			}
		case projecttasksynchead.FieldOrganizationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field organization_id", values[i])
			} else if value.Valid {
				ptsh.OrganizationID = value.String
			}
		case projecttasksynchead.FieldWorkspaceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field workspace_id", values[i])
			} else if value.Valid {
				ptsh.WorkspaceID = value.String
			}
		case projecttasksynchead.FieldProjectID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value.Valid {
				ptsh.ProjectID = value.String
			}
		case projecttasksynchead.FieldLocalAliasID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field local_alias_id", values[i])
			} else if value.Valid {
				ptsh.LocalAliasID = value.String
			}
		case projecttasksynchead.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				ptsh.Version = value.Int64
			}
		case projecttasksynchead.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				ptsh.Status = value.String
			}
		default:
			ptsh.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProjectTaskSyncHead.
// This includes values selected through modifiers, order, etc.
func (ptsh *ProjectTaskSyncHead) Value(name string) (ent.Value, error) {
	return ptsh.selectValues.Get(name)
}

// Update returns a builder for updating this ProjectTaskSyncHead.
// Note that you need to call ProjectTaskSyncHead.Unwrap() before calling this method if this ProjectTaskSyncHead
// was returned from a transaction, and the transaction was committed or rolled back.
func (ptsh *ProjectTaskSyncHead) Update() *ProjectTaskSyncHeadUpdateOne {
	return NewProjectTaskSyncHeadClient(ptsh.config).UpdateOne(ptsh)
}

// Unwrap unwraps the ProjectTaskSyncHead entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ptsh *ProjectTaskSyncHead) Unwrap() *ProjectTaskSyncHead {
	_tx, ok := ptsh.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProjectTaskSyncHead is not a transactional entity")
	}
	ptsh.config.driver = _tx.drv
	return ptsh
}

// String implements the fmt.Stringer.
func (ptsh *ProjectTaskSyncHead) String() string {
	var builder strings.Builder
	builder.WriteString("ProjectTaskSyncHead(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ptsh.ID))
	builder.WriteString("created_at=")
	builder.WriteString(ptsh.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(ptsh.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(ptsh.Kind)
	builder.WriteString(", ")
	builder.WriteString("organization_id=")
	builder.WriteString(ptsh.OrganizationID)
	builder.WriteString(", ")
	builder.WriteString("workspace_id=")
	builder.WriteString(ptsh.WorkspaceID)
	builder.WriteString(", ")
	builder.WriteString("project_id=")
	builder.WriteString(ptsh.ProjectID)
	builder.WriteString(", ")
	builder.WriteString("local_alias_id=")
	builder.WriteString(ptsh.LocalAliasID)
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", ptsh.Version))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(ptsh.Status)
	builder.WriteByte(')')
	return builder.String()
}

// ProjectTaskSyncHeads is a parsable slice of ProjectTaskSyncHead.
type ProjectTaskSyncHeads []*ProjectTaskSyncHead
