// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"opl-cloud/services/control-plane/ent/predicate"
	"opl-cloud/services/control-plane/ent/projecttasksynchead"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProjectTaskSyncHeadUpdate is the builder for updating ProjectTaskSyncHead entities.
type ProjectTaskSyncHeadUpdate struct {
	config
	hooks    []Hook
	mutation *ProjectTaskSyncHeadMutation
}

// Where appends a list predicates to the ProjectTaskSyncHeadUpdate builder.
func (ptshu *ProjectTaskSyncHeadUpdate) Where(ps ...predicate.ProjectTaskSyncHead) *ProjectTaskSyncHeadUpdate {
	ptshu.mutation.Where(ps...)
	return ptshu
}

// SetCreatedAt sets the "created_at" field.
func (ptshu *ProjectTaskSyncHeadUpdate) SetCreatedAt(t time.Time) *ProjectTaskSyncHeadUpdate {
	ptshu.mutation.SetCreatedAt(t)
	return ptshu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ptshu *ProjectTaskSyncHeadUpdate) SetNillableCreatedAt(t *time.Time) *ProjectTaskSyncHeadUpdate {
	if t != nil {
		ptshu.SetCreatedAt(*t)
	}
	return ptshu
}

// SetUpdatedAt sets the "updated_at" field.
func (ptshu *ProjectTaskSyncHeadUpdate) SetUpdatedAt(t time.Time) *ProjectTaskSyncHeadUpdate {
	ptshu.mutation.SetUpdatedAt(t)
	return ptshu
}

// SetKind sets the "kind" field.
func (ptshu *ProjectTaskSyncHeadUpdate) SetKind(s string) *ProjectTaskSyncHeadUpdate {
	ptshu.mutation.SetKind(s)
	return ptshu
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (ptshu *ProjectTaskSyncHeadUpdate) SetNillableKind(s *string) *ProjectTaskSyncHeadUpdate {
	if s != nil {
		ptshu.SetKind(*s)
	}
	return ptshu
}

// SetOrganizationID sets the "organization_id" field.
func (ptshu *ProjectTaskSyncHeadUpdate) SetOrganizationID(s string) *ProjectTaskSyncHeadUpdate {
	ptshu.mutation.SetOrganizationID(s)
	return ptshu
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (ptshu *ProjectTaskSyncHeadUpdate) SetNillableOrganizationID(s *string) *ProjectTaskSyncHeadUpdate {
	if s != nil {
		ptshu.SetOrganizationID(*s)
	}
	return ptshu
}

// SetWorkspaceID sets the "workspace_id" field.
func (ptshu *ProjectTaskSyncHeadUpdate) SetWorkspaceID(s string) *ProjectTaskSyncHeadUpdate {
	ptshu.mutation.SetWorkspaceID(s)
	return ptshu
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (ptshu *ProjectTaskSyncHeadUpdate) SetNillableWorkspaceID(s *string) *ProjectTaskSyncHeadUpdate {
	if s != nil {
		ptshu.SetWorkspaceID(*s)
	}
	return ptshu
}

// SetProjectID sets the "project_id" field.
func (ptshu *ProjectTaskSyncHeadUpdate) SetProjectID(s string) *ProjectTaskSyncHeadUpdate {
	ptshu.mutation.SetProjectID(s)
	return ptshu
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (ptshu *ProjectTaskSyncHeadUpdate) SetNillableProjectID(s *string) *ProjectTaskSyncHeadUpdate {
	if s != nil {
		ptshu.SetProjectID(*s)
	}
	return ptshu
}

// SetLocalAliasID sets the "local_alias_id" field.
func (ptshu *ProjectTaskSyncHeadUpdate) SetLocalAliasID(s string) *ProjectTaskSyncHeadUpdate {
	ptshu.mutation.SetLocalAliasID(s)
	return ptshu
}

// SetNillableLocalAliasID sets the "local_alias_id" field if the given value is not nil.
func (ptshu *ProjectTaskSyncHeadUpdate) SetNillableLocalAliasID(s *string) *ProjectTaskSyncHeadUpdate {
	if s != nil {
		ptshu.SetLocalAliasID(*s)
	}
	return ptshu
}

// SetVersion sets the "version" field.
func (ptshu *ProjectTaskSyncHeadUpdate) SetVersion(i int64) *ProjectTaskSyncHeadUpdate {
	ptshu.mutation.ResetVersion()
	ptshu.mutation.SetVersion(i)
	return ptshu
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (ptshu *ProjectTaskSyncHeadUpdate) SetNillableVersion(i *int64) *ProjectTaskSyncHeadUpdate {
	if i != nil {
		ptshu.SetVersion(*i)
	}
	return ptshu
}

// AddVersion adds i to the "version" field.
func (ptshu *ProjectTaskSyncHeadUpdate) AddVersion(i int64) *ProjectTaskSyncHeadUpdate {
	ptshu.mutation.AddVersion(i)
	return ptshu
}

// SetStatus sets the "status" field.
func (ptshu *ProjectTaskSyncHeadUpdate) SetStatus(s string) *ProjectTaskSyncHeadUpdate {
	ptshu.mutation.SetStatus(s)
	return ptshu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ptshu *ProjectTaskSyncHeadUpdate) SetNillableStatus(s *string) *ProjectTaskSyncHeadUpdate {
	if s != nil {
		ptshu.SetStatus(*s)
	}
	return ptshu
}

// Mutation returns the ProjectTaskSyncHeadMutation object of the builder.
func (ptshu *ProjectTaskSyncHeadUpdate) Mutation() *ProjectTaskSyncHeadMutation {
	return ptshu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ptshu *ProjectTaskSyncHeadUpdate) Save(ctx context.Context) (int, error) {
	ptshu.defaults()
	return withHooks(ctx, ptshu.sqlSave, ptshu.mutation, ptshu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ptshu *ProjectTaskSyncHeadUpdate) SaveX(ctx context.Context) int {
	affected, err := ptshu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ptshu *ProjectTaskSyncHeadUpdate) Exec(ctx context.Context) error {
	_, err := ptshu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ptshu *ProjectTaskSyncHeadUpdate) ExecX(ctx context.Context) {
	if err := ptshu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ptshu *ProjectTaskSyncHeadUpdate) defaults() {
	if _, ok := ptshu.mutation.UpdatedAt(); !ok {
		v := projecttasksynchead.UpdateDefaultUpdatedAt()
		ptshu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ptshu *ProjectTaskSyncHeadUpdate) check() error {
	if v, ok := ptshu.mutation.Kind(); ok {
		if err := projecttasksynchead.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "ProjectTaskSyncHead.kind": %w`, err)}
		}
	}
	if v, ok := ptshu.mutation.OrganizationID(); ok {
		if err := projecttasksynchead.OrganizationIDValidator(v); err != nil {
			return &ValidationError{Name: "organization_id", err: fmt.Errorf(`ent: validator failed for field "ProjectTaskSyncHead.organization_id": %w`, err)}
		}
	}
	if v, ok := ptshu.mutation.WorkspaceID(); ok {
		if err := projecttasksynchead.WorkspaceIDValidator(v); err != nil {
			return &ValidationError{Name: "workspace_id", err: fmt.Errorf(`ent: validator failed for field "ProjectTaskSyncHead.workspace_id": %w`, err)}
		}
	}
	return nil
}

func (ptshu *ProjectTaskSyncHeadUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ptshu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(projecttasksynchead.Table, projecttasksynchead.Columns, sqlgraph.NewFieldSpec(projecttasksynchead.FieldID, field.TypeString))
	if ps := ptshu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ptshu.mutation.CreatedAt(); ok {
		_spec.SetField(projecttasksynchead.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := ptshu.mutation.UpdatedAt(); ok {
		_spec.SetField(projecttasksynchead.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := ptshu.mutation.Kind(); ok {
		_spec.SetField(projecttasksynchead.FieldKind, field.TypeString, value)
	}
	if value, ok := ptshu.mutation.OrganizationID(); ok {
		_spec.SetField(projecttasksynchead.FieldOrganizationID, field.TypeString, value)
	}
	if value, ok := ptshu.mutation.WorkspaceID(); ok {
		_spec.SetField(projecttasksynchead.FieldWorkspaceID, field.TypeString, value)
	}
	if value, ok := ptshu.mutation.ProjectID(); ok {
		_spec.SetField(projecttasksynchead.FieldProjectID, field.TypeString, value)
	}
	if value, ok := ptshu.mutation.LocalAliasID(); ok {
		_spec.SetField(projecttasksynchead.FieldLocalAliasID, field.TypeString, value)
	}
	if value, ok := ptshu.mutation.Version(); ok {
		_spec.SetField(projecttasksynchead.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := ptshu.mutation.AddedVersion(); ok {
		_spec.AddField(projecttasksynchead.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := ptshu.mutation.Status(); ok {
		_spec.SetField(projecttasksynchead.FieldStatus, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ptshu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{projecttasksynchead.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ptshu.mutation.done = true
	return n, nil
}

// ProjectTaskSyncHeadUpdateOne is the builder for updating a single ProjectTaskSyncHead entity.
type ProjectTaskSyncHeadUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProjectTaskSyncHeadMutation
}

// SetCreatedAt sets the "created_at" field.
func (ptshuo *ProjectTaskSyncHeadUpdateOne) SetCreatedAt(t time.Time) *ProjectTaskSyncHeadUpdateOne {
	ptshuo.mutation.SetCreatedAt(t)
	return ptshuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ptshuo *ProjectTaskSyncHeadUpdateOne) SetNillableCreatedAt(t *time.Time) *ProjectTaskSyncHeadUpdateOne {
	if t != nil {
		ptshuo.SetCreatedAt(*t)
	}
	return ptshuo
}

// SetUpdatedAt sets the "updated_at" field.
func (ptshuo *ProjectTaskSyncHeadUpdateOne) SetUpdatedAt(t time.Time) *ProjectTaskSyncHeadUpdateOne {
	ptshuo.mutation.SetUpdatedAt(t)
	return ptshuo
}

// SetKind sets the "kind" field.
func (ptshuo *ProjectTaskSyncHeadUpdateOne) SetKind(s string) *ProjectTaskSyncHeadUpdateOne {
	ptshuo.mutation.SetKind(s)
	return ptshuo
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (ptshuo *ProjectTaskSyncHeadUpdateOne) SetNillableKind(s *string) *ProjectTaskSyncHeadUpdateOne {
	if s != nil {
		ptshuo.SetKind(*s)
	}
	return ptshuo
}

// SetOrganizationID sets the "organization_id" field.
func (ptshuo *ProjectTaskSyncHeadUpdateOne) SetOrganizationID(s string) *ProjectTaskSyncHeadUpdateOne {
	ptshuo.mutation.SetOrganizationID(s)
	return ptshuo
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (ptshuo *ProjectTaskSyncHeadUpdateOne) SetNillableOrganizationID(s *string) *ProjectTaskSyncHeadUpdateOne {
	if s != nil {
		ptshuo.SetOrganizationID(*s)
	}
	return ptshuo
}

// SetWorkspaceID sets the "workspace_id" field.
func (ptshuo *ProjectTaskSyncHeadUpdateOne) SetWorkspaceID(s string) *ProjectTaskSyncHeadUpdateOne {
	ptshuo.mutation.SetWorkspaceID(s)
	return ptshuo
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (ptshuo *ProjectTaskSyncHeadUpdateOne) SetNillableWorkspaceID(s *string) *ProjectTaskSyncHeadUpdateOne {
	if s != nil {
		ptshuo.SetWorkspaceID(*s)
	}
	return ptshuo
}

// SetProjectID sets the "project_id" field.
func (ptshuo *ProjectTaskSyncHeadUpdateOne) SetProjectID(s string) *ProjectTaskSyncHeadUpdateOne {
	ptshuo.mutation.SetProjectID(s)
	return ptshuo
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (ptshuo *ProjectTaskSyncHeadUpdateOne) SetNillableProjectID(s *string) *ProjectTaskSyncHeadUpdateOne {
	if s != nil {
		ptshuo.SetProjectID(*s)
	}
	return ptshuo
}

// SetLocalAliasID sets the "local_alias_id" field.
func (ptshuo *ProjectTaskSyncHeadUpdateOne) SetLocalAliasID(s string) *ProjectTaskSyncHeadUpdateOne {
	ptshuo.mutation.SetLocalAliasID(s)
	return ptshuo
}

// SetNillableLocalAliasID sets the "local_alias_id" field if the given value is not nil.
func (ptshuo *ProjectTaskSyncHeadUpdateOne) SetNillableLocalAliasID(s *string) *ProjectTaskSyncHeadUpdateOne {
	if s != nil {
		ptshuo.SetLocalAliasID(*s)
	}
	return ptshuo
}

// SetVersion sets the "version" field.
func (ptshuo *ProjectTaskSyncHeadUpdateOne) SetVersion(i int64) *ProjectTaskSyncHeadUpdateOne {
	ptshuo.mutation.ResetVersion()
	ptshuo.mutation.SetVersion(i)
	return ptshuo
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (ptshuo *ProjectTaskSyncHeadUpdateOne) SetNillableVersion(i *int64) *ProjectTaskSyncHeadUpdateOne {
	if i != nil {
		ptshuo.SetVersion(*i)
	}
	return ptshuo
}

// AddVersion adds i to the "version" field.
func (ptshuo *ProjectTaskSyncHeadUpdateOne) AddVersion(i int64) *ProjectTaskSyncHeadUpdateOne {
	ptshuo.mutation.AddVersion(i)
	return ptshuo
}

// SetStatus sets the "status" field.
func (ptshuo *ProjectTaskSyncHeadUpdateOne) SetStatus(s string) *ProjectTaskSyncHeadUpdateOne {
	ptshuo.mutation.SetStatus(s)
	return ptshuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ptshuo *ProjectTaskSyncHeadUpdateOne) SetNillableStatus(s *string) *ProjectTaskSyncHeadUpdateOne {
	if s != nil {
		ptshuo.SetStatus(*s)
	}
	return ptshuo
}

// Mutation returns the ProjectTaskSyncHeadMutation object of the builder.
func (ptshuo *ProjectTaskSyncHeadUpdateOne) Mutation() *ProjectTaskSyncHeadMutation {
	return ptshuo.mutation
}

// Where appends a list predicates to the ProjectTaskSyncHeadUpdate builder.
func (ptshuo *ProjectTaskSyncHeadUpdateOne) Where(ps ...predicate.ProjectTaskSyncHead) *ProjectTaskSyncHeadUpdateOne {
	ptshuo.mutation.Where(ps...)
	return ptshuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ptshuo *ProjectTaskSyncHeadUpdateOne) Select(field string, fields ...string) *ProjectTaskSyncHeadUpdateOne {
	ptshuo.fields = append([]string{field}, fields...)
	return ptshuo
}

// Save executes the query and returns the updated ProjectTaskSyncHead entity.
func (ptshuo *ProjectTaskSyncHeadUpdateOne) Save(ctx context.Context) (*ProjectTaskSyncHead, error) {
	ptshuo.defaults()
	return withHooks(ctx, ptshuo.sqlSave, ptshuo.mutation, ptshuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ptshuo *ProjectTaskSyncHeadUpdateOne) SaveX(ctx context.Context) *ProjectTaskSyncHead {
	node, err := ptshuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ptshuo *ProjectTaskSyncHeadUpdateOne) Exec(ctx context.Context) error {
	_, err := ptshuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ptshuo *ProjectTaskSyncHeadUpdateOne) ExecX(ctx context.Context) {
	if err := ptshuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ptshuo *ProjectTaskSyncHeadUpdateOne) defaults() {
	if _, ok := ptshuo.mutation.UpdatedAt(); !ok {
		v := projecttasksynchead.UpdateDefaultUpdatedAt()
		ptshuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ptshuo *ProjectTaskSyncHeadUpdateOne) check() error {
	if v, ok := ptshuo.mutation.Kind(); ok {
		if err := projecttasksynchead.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "ProjectTaskSyncHead.kind": %w`, err)}
		}
	}
	if v, ok := ptshuo.mutation.OrganizationID(); ok {
		if err := projecttasksynchead.OrganizationIDValidator(v); err != nil {
			return &ValidationError{Name: "organization_id", err: fmt.Errorf(`ent: validator failed for field "ProjectTaskSyncHead.organization_id": %w`, err)}
		}
	}
	if v, ok := ptshuo.mutation.WorkspaceID(); ok {
		if err := projecttasksynchead.WorkspaceIDValidator(v); err != nil {
			return &ValidationError{Name: "workspace_id", err: fmt.Errorf(`ent: validator failed for field "ProjectTaskSyncHead.workspace_id": %w`, err)}
		}
	}
	return nil
}

func (ptshuo *ProjectTaskSyncHeadUpdateOne) sqlSave(ctx context.Context) (_node *ProjectTaskSyncHead, err error) {
	if err := ptshuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(projecttasksynchead.Table, projecttasksynchead.Columns, sqlgraph.NewFieldSpec(projecttasksynchead.FieldID, field.TypeString))
	id, ok := ptshuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProjectTaskSyncHead.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ptshuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, projecttasksynchead.FieldID)
		for _, f := range fields {
			if !projecttasksynchead.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != projecttasksynchead.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ptshuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ptshuo.mutation.CreatedAt(); ok {
		_spec.SetField(projecttasksynchead.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := ptshuo.mutation.UpdatedAt(); ok {
		_spec.SetField(projecttasksynchead.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := ptshuo.mutation.Kind(); ok {
		_spec.SetField(projecttasksynchead.FieldKind, field.TypeString, value)
	}
	if value, ok := ptshuo.mutation.OrganizationID(); ok {
		_spec.SetField(projecttasksynchead.FieldOrganizationID, field.TypeString, value)
	}
	if value, ok := ptshuo.mutation.WorkspaceID(); ok {
		_spec.SetField(projecttasksynchead.FieldWorkspaceID, field.TypeString, value)
	}
	if value, ok := ptshuo.mutation.ProjectID(); ok {
		_spec.SetField(projecttasksynchead.FieldProjectID, field.TypeString, value)
	}
	if value, ok := ptshuo.mutation.LocalAliasID(); ok {
		_spec.SetField(projecttasksynchead.FieldLocalAliasID, field.TypeString, value)
	}
	if value, ok := ptshuo.mutation.Version(); ok {
		_spec.SetField(projecttasksynchead.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := ptshuo.mutation.AddedVersion(); ok {
		_spec.AddField(projecttasksynchead.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := ptshuo.mutation.Status(); ok {
		_spec.SetField(projecttasksynchead.FieldStatus, field.TypeString, value)
	}
	_node = &ProjectTaskSyncHead{config: ptshuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ptshuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{projecttasksynchead.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ptshuo.mutation.done = true
	return _node, nil
}
