// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"opl-cloud/services/control-plane/ent/supportticketmapping"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SupportTicketMappingCreate is the builder for creating a SupportTicketMapping entity.
type SupportTicketMappingCreate struct {
	config
	mutation *SupportTicketMappingMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (stmc *SupportTicketMappingCreate) SetCreatedAt(t time.Time) *SupportTicketMappingCreate {
	stmc.mutation.SetCreatedAt(t)
	return stmc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (stmc *SupportTicketMappingCreate) SetNillableCreatedAt(t *time.Time) *SupportTicketMappingCreate {
	if t != nil {
		stmc.SetCreatedAt(*t)
	}
	return stmc
}

// SetUpdatedAt sets the "updated_at" field.
func (stmc *SupportTicketMappingCreate) SetUpdatedAt(t time.Time) *SupportTicketMappingCreate {
	stmc.mutation.SetUpdatedAt(t)
	return stmc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (stmc *SupportTicketMappingCreate) SetNillableUpdatedAt(t *time.Time) *SupportTicketMappingCreate {
	if t != nil {
		stmc.SetUpdatedAt(*t)
	}
	return stmc
}

// SetAccountID sets the "account_id" field.
func (stmc *SupportTicketMappingCreate) SetAccountID(s string) *SupportTicketMappingCreate {
	stmc.mutation.SetAccountID(s)
	return stmc
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (stmc *SupportTicketMappingCreate) SetNillableAccountID(s *string) *SupportTicketMappingCreate {
	if s != nil {
		stmc.SetAccountID(*s)
	}
	return stmc
}

// SetUserID sets the "user_id" field.
func (stmc *SupportTicketMappingCreate) SetUserID(s string) *SupportTicketMappingCreate {
	stmc.mutation.SetUserID(s)
	return stmc
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (stmc *SupportTicketMappingCreate) SetNillableUserID(s *string) *SupportTicketMappingCreate {
	if s != nil {
		stmc.SetUserID(*s)
	}
	return stmc
}

// SetWorkspaceID sets the "workspace_id" field.
func (stmc *SupportTicketMappingCreate) SetWorkspaceID(s string) *SupportTicketMappingCreate {
	stmc.mutation.SetWorkspaceID(s)
	return stmc
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (stmc *SupportTicketMappingCreate) SetNillableWorkspaceID(s *string) *SupportTicketMappingCreate {
	if s != nil {
		stmc.SetWorkspaceID(*s)
	}
	return stmc
}

// SetExternalSystem sets the "external_system" field.
func (stmc *SupportTicketMappingCreate) SetExternalSystem(s string) *SupportTicketMappingCreate {
	stmc.mutation.SetExternalSystem(s)
	return stmc
}

// SetNillableExternalSystem sets the "external_system" field if the given value is not nil.
func (stmc *SupportTicketMappingCreate) SetNillableExternalSystem(s *string) *SupportTicketMappingCreate {
	if s != nil {
		stmc.SetExternalSystem(*s)
	}
	return stmc
}

// SetExternalTicketID sets the "external_ticket_id" field.
func (stmc *SupportTicketMappingCreate) SetExternalTicketID(s string) *SupportTicketMappingCreate {
	stmc.mutation.SetExternalTicketID(s)
	return stmc
}

// SetNillableExternalTicketID sets the "external_ticket_id" field if the given value is not nil.
func (stmc *SupportTicketMappingCreate) SetNillableExternalTicketID(s *string) *SupportTicketMappingCreate {
	if s != nil {
		stmc.SetExternalTicketID(*s)
	}
	return stmc
}

// SetExternalURL sets the "external_url" field.
func (stmc *SupportTicketMappingCreate) SetExternalURL(s string) *SupportTicketMappingCreate {
	stmc.mutation.SetExternalURL(s)
	return stmc
}

// SetNillableExternalURL sets the "external_url" field if the given value is not nil.
func (stmc *SupportTicketMappingCreate) SetNillableExternalURL(s *string) *SupportTicketMappingCreate {
	if s != nil {
		stmc.SetExternalURL(*s)
	}
	return stmc
}

// SetOperationID sets the "operation_id" field.
func (stmc *SupportTicketMappingCreate) SetOperationID(s string) *SupportTicketMappingCreate {
	stmc.mutation.SetOperationID(s)
	return stmc
}

// SetNillableOperationID sets the "operation_id" field if the given value is not nil.
func (stmc *SupportTicketMappingCreate) SetNillableOperationID(s *string) *SupportTicketMappingCreate {
	if s != nil {
		stmc.SetOperationID(*s)
	}
	return stmc
}

// SetResourceID sets the "resource_id" field.
func (stmc *SupportTicketMappingCreate) SetResourceID(s string) *SupportTicketMappingCreate {
	stmc.mutation.SetResourceID(s)
	return stmc
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (stmc *SupportTicketMappingCreate) SetNillableResourceID(s *string) *SupportTicketMappingCreate {
	if s != nil {
		stmc.SetResourceID(*s)
	}
	return stmc
}

// SetResourceKind sets the "resource_kind" field.
func (stmc *SupportTicketMappingCreate) SetResourceKind(s string) *SupportTicketMappingCreate {
	stmc.mutation.SetResourceKind(s)
	return stmc
}

// SetNillableResourceKind sets the "resource_kind" field if the given value is not nil.
func (stmc *SupportTicketMappingCreate) SetNillableResourceKind(s *string) *SupportTicketMappingCreate {
	if s != nil {
		stmc.SetResourceKind(*s)
	}
	return stmc
}

// SetTitle sets the "title" field.
func (stmc *SupportTicketMappingCreate) SetTitle(s string) *SupportTicketMappingCreate {
	stmc.mutation.SetTitle(s)
	return stmc
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (stmc *SupportTicketMappingCreate) SetNillableTitle(s *string) *SupportTicketMappingCreate {
	if s != nil {
		stmc.SetTitle(*s)
	}
	return stmc
}

// SetCategory sets the "category" field.
func (stmc *SupportTicketMappingCreate) SetCategory(s string) *SupportTicketMappingCreate {
	stmc.mutation.SetCategory(s)
	return stmc
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (stmc *SupportTicketMappingCreate) SetNillableCategory(s *string) *SupportTicketMappingCreate {
	if s != nil {
		stmc.SetCategory(*s)
	}
	return stmc
}

// SetPriority sets the "priority" field.
func (stmc *SupportTicketMappingCreate) SetPriority(s string) *SupportTicketMappingCreate {
	stmc.mutation.SetPriority(s)
	return stmc
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (stmc *SupportTicketMappingCreate) SetNillablePriority(s *string) *SupportTicketMappingCreate {
	if s != nil {
		stmc.SetPriority(*s)
	}
	return stmc
}

// SetStatus sets the "status" field.
func (stmc *SupportTicketMappingCreate) SetStatus(s string) *SupportTicketMappingCreate {
	stmc.mutation.SetStatus(s)
	return stmc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (stmc *SupportTicketMappingCreate) SetNillableStatus(s *string) *SupportTicketMappingCreate {
	if s != nil {
		stmc.SetStatus(*s)
	}
	return stmc
}

// SetSource sets the "source" field.
func (stmc *SupportTicketMappingCreate) SetSource(s string) *SupportTicketMappingCreate {
	stmc.mutation.SetSource(s)
	return stmc
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (stmc *SupportTicketMappingCreate) SetNillableSource(s *string) *SupportTicketMappingCreate {
	if s != nil {
		stmc.SetSource(*s)
	}
	return stmc
}

// SetURL sets the "url" field.
func (stmc *SupportTicketMappingCreate) SetURL(s string) *SupportTicketMappingCreate {
	stmc.mutation.SetURL(s)
	return stmc
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (stmc *SupportTicketMappingCreate) SetNillableURL(s *string) *SupportTicketMappingCreate {
	if s != nil {
		stmc.SetURL(*s)
	}
	return stmc
}

// SetReason sets the "reason" field.
func (stmc *SupportTicketMappingCreate) SetReason(s string) *SupportTicketMappingCreate {
	stmc.mutation.SetReason(s)
	return stmc
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (stmc *SupportTicketMappingCreate) SetNillableReason(s *string) *SupportTicketMappingCreate {
	if s != nil {
		stmc.SetReason(*s)
	}
	return stmc
}

// SetID sets the "id" field.
func (stmc *SupportTicketMappingCreate) SetID(s string) *SupportTicketMappingCreate {
	stmc.mutation.SetID(s)
	return stmc
}

// Mutation returns the SupportTicketMappingMutation object of the builder.
func (stmc *SupportTicketMappingCreate) Mutation() *SupportTicketMappingMutation {
	return stmc.mutation
}

// Save creates the SupportTicketMapping in the database.
func (stmc *SupportTicketMappingCreate) Save(ctx context.Context) (*SupportTicketMapping, error) {
	stmc.defaults()
	return withHooks(ctx, stmc.sqlSave, stmc.mutation, stmc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (stmc *SupportTicketMappingCreate) SaveX(ctx context.Context) *SupportTicketMapping {
	v, err := stmc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (stmc *SupportTicketMappingCreate) Exec(ctx context.Context) error {
	_, err := stmc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (stmc *SupportTicketMappingCreate) ExecX(ctx context.Context) {
	if err := stmc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (stmc *SupportTicketMappingCreate) defaults() {
	if _, ok := stmc.mutation.CreatedAt(); !ok {
		v := supportticketmapping.DefaultCreatedAt()
		stmc.mutation.SetCreatedAt(v)
	}
	if _, ok := stmc.mutation.UpdatedAt(); !ok {
		v := supportticketmapping.DefaultUpdatedAt()
		stmc.mutation.SetUpdatedAt(v)
	}
	if _, ok := stmc.mutation.AccountID(); !ok {
		v := supportticketmapping.DefaultAccountID
		stmc.mutation.SetAccountID(v)
	}
	if _, ok := stmc.mutation.UserID(); !ok {
		v := supportticketmapping.DefaultUserID
		stmc.mutation.SetUserID(v)
	}
	if _, ok := stmc.mutation.WorkspaceID(); !ok {
		v := supportticketmapping.DefaultWorkspaceID
		stmc.mutation.SetWorkspaceID(v)
	}
	if _, ok := stmc.mutation.ExternalSystem(); !ok {
		v := supportticketmapping.DefaultExternalSystem
		stmc.mutation.SetExternalSystem(v)
	}
	if _, ok := stmc.mutation.ExternalTicketID(); !ok {
		v := supportticketmapping.DefaultExternalTicketID
		stmc.mutation.SetExternalTicketID(v)
	}
	if _, ok := stmc.mutation.ExternalURL(); !ok {
		v := supportticketmapping.DefaultExternalURL
		stmc.mutation.SetExternalURL(v)
	}
	if _, ok := stmc.mutation.OperationID(); !ok {
		v := supportticketmapping.DefaultOperationID
		stmc.mutation.SetOperationID(v)
	}
	if _, ok := stmc.mutation.ResourceID(); !ok {
		v := supportticketmapping.DefaultResourceID
		stmc.mutation.SetResourceID(v)
	}
	if _, ok := stmc.mutation.ResourceKind(); !ok {
		v := supportticketmapping.DefaultResourceKind
		stmc.mutation.SetResourceKind(v)
	}
	if _, ok := stmc.mutation.Title(); !ok {
		v := supportticketmapping.DefaultTitle
		stmc.mutation.SetTitle(v)
	}
	if _, ok := stmc.mutation.Category(); !ok {
		v := supportticketmapping.DefaultCategory
		stmc.mutation.SetCategory(v)
	}
	if _, ok := stmc.mutation.Priority(); !ok {
		v := supportticketmapping.DefaultPriority
		stmc.mutation.SetPriority(v)
	}
	if _, ok := stmc.mutation.Status(); !ok {
		v := supportticketmapping.DefaultStatus
		stmc.mutation.SetStatus(v)
	}
	if _, ok := stmc.mutation.Source(); !ok {
		v := supportticketmapping.DefaultSource
		stmc.mutation.SetSource(v)
	}
	if _, ok := stmc.mutation.URL(); !ok {
		v := supportticketmapping.DefaultURL
		stmc.mutation.SetURL(v)
	}
	if _, ok := stmc.mutation.Reason(); !ok {
		v := supportticketmapping.DefaultReason
		stmc.mutation.SetReason(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (stmc *SupportTicketMappingCreate) check() error {
	if _, ok := stmc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SupportTicketMapping.created_at"`)}
	}
	if _, ok := stmc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SupportTicketMapping.updated_at"`)}
	}
	if _, ok := stmc.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "SupportTicketMapping.account_id"`)}
	}
	if _, ok := stmc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "SupportTicketMapping.user_id"`)}
	}
	if _, ok := stmc.mutation.WorkspaceID(); !ok {
		return &ValidationError{Name: "workspace_id", err: errors.New(`ent: missing required field "SupportTicketMapping.workspace_id"`)}
	}
	if _, ok := stmc.mutation.ExternalSystem(); !ok {
		return &ValidationError{Name: "external_system", err: errors.New(`ent: missing required field "SupportTicketMapping.external_system"`)}
	}
	if _, ok := stmc.mutation.ExternalTicketID(); !ok {
		return &ValidationError{Name: "external_ticket_id", err: errors.New(`ent: missing required field "SupportTicketMapping.external_ticket_id"`)}
	}
	if _, ok := stmc.mutation.ExternalURL(); !ok {
		return &ValidationError{Name: "external_url", err: errors.New(`ent: missing required field "SupportTicketMapping.external_url"`)}
	}
	if _, ok := stmc.mutation.OperationID(); !ok {
		return &ValidationError{Name: "operation_id", err: errors.New(`ent: missing required field "SupportTicketMapping.operation_id"`)}
	}
	if _, ok := stmc.mutation.ResourceID(); !ok {
		return &ValidationError{Name: "resource_id", err: errors.New(`ent: missing required field "SupportTicketMapping.resource_id"`)}
	}
	if _, ok := stmc.mutation.ResourceKind(); !ok {
		return &ValidationError{Name: "resource_kind", err: errors.New(`ent: missing required field "SupportTicketMapping.resource_kind"`)}
	}
	if _, ok := stmc.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "SupportTicketMapping.title"`)}
	}
	if _, ok := stmc.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "SupportTicketMapping.category"`)}
	}
	if _, ok := stmc.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "SupportTicketMapping.priority"`)}
	}
	if _, ok := stmc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SupportTicketMapping.status"`)}
	}
	if _, ok := stmc.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "SupportTicketMapping.source"`)}
	}
	if _, ok := stmc.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "SupportTicketMapping.url"`)}
	}
	if _, ok := stmc.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`ent: missing required field "SupportTicketMapping.reason"`)}
	}
	if v, ok := stmc.mutation.ID(); ok {
		if err := supportticketmapping.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "SupportTicketMapping.id": %w`, err)}
		}
	}
	return nil
}

func (stmc *SupportTicketMappingCreate) sqlSave(ctx context.Context) (*SupportTicketMapping, error) {
	if err := stmc.check(); err != nil {
		return nil, err
	}
	_node, _spec := stmc.createSpec()
	if err := sqlgraph.CreateNode(ctx, stmc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected SupportTicketMapping.ID type: %T", _spec.ID.Value)
		}
	}
	stmc.mutation.id = &_node.ID
	stmc.mutation.done = true
	return _node, nil
}

func (stmc *SupportTicketMappingCreate) createSpec() (*SupportTicketMapping, *sqlgraph.CreateSpec) {
	var (
		_node = &SupportTicketMapping{config: stmc.config}
		_spec = sqlgraph.NewCreateSpec(supportticketmapping.Table, sqlgraph.NewFieldSpec(supportticketmapping.FieldID, field.TypeString))
	)
	if id, ok := stmc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := stmc.mutation.CreatedAt(); ok {
		_spec.SetField(supportticketmapping.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := stmc.mutation.UpdatedAt(); ok {
		_spec.SetField(supportticketmapping.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := stmc.mutation.AccountID(); ok {
		_spec.SetField(supportticketmapping.FieldAccountID, field.TypeString, value)
		_node.AccountID = value
	}
	if value, ok := stmc.mutation.UserID(); ok {
		_spec.SetField(supportticketmapping.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := stmc.mutation.WorkspaceID(); ok {
		_spec.SetField(supportticketmapping.FieldWorkspaceID, field.TypeString, value)
		_node.WorkspaceID = value
	}
	if value, ok := stmc.mutation.ExternalSystem(); ok {
		_spec.SetField(supportticketmapping.FieldExternalSystem, field.TypeString, value)
		_node.ExternalSystem = value
	}
	if value, ok := stmc.mutation.ExternalTicketID(); ok {
		_spec.SetField(supportticketmapping.FieldExternalTicketID, field.TypeString, value)
		_node.ExternalTicketID = value
	}
	if value, ok := stmc.mutation.ExternalURL(); ok {
		_spec.SetField(supportticketmapping.FieldExternalURL, field.TypeString, value)
		_node.ExternalURL = value
	}
	if value, ok := stmc.mutation.OperationID(); ok {
		_spec.SetField(supportticketmapping.FieldOperationID, field.TypeString, value)
		_node.OperationID = value
	}
	if value, ok := stmc.mutation.ResourceID(); ok {
		_spec.SetField(supportticketmapping.FieldResourceID, field.TypeString, value)
		_node.ResourceID = value
	}
	if value, ok := stmc.mutation.ResourceKind(); ok {
		_spec.SetField(supportticketmapping.FieldResourceKind, field.TypeString, value)
		_node.ResourceKind = value
	}
	if value, ok := stmc.mutation.Title(); ok {
		_spec.SetField(supportticketmapping.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := stmc.mutation.Category(); ok {
		_spec.SetField(supportticketmapping.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := stmc.mutation.Priority(); ok {
		_spec.SetField(supportticketmapping.FieldPriority, field.TypeString, value)
		_node.Priority = value
	}
	if value, ok := stmc.mutation.Status(); ok {
		_spec.SetField(supportticketmapping.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := stmc.mutation.Source(); ok {
		_spec.SetField(supportticketmapping.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := stmc.mutation.URL(); ok {
		_spec.SetField(supportticketmapping.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := stmc.mutation.Reason(); ok {
		_spec.SetField(supportticketmapping.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	return _node, _spec
}

// SupportTicketMappingCreateBulk is the builder for creating many SupportTicketMapping entities in bulk.
type SupportTicketMappingCreateBulk struct {
	config
	err      error
	builders []*SupportTicketMappingCreate
}

// Save creates the SupportTicketMapping entities in the database.
func (stmcb *SupportTicketMappingCreateBulk) Save(ctx context.Context) ([]*SupportTicketMapping, error) {
	if stmcb.err != nil {
		return nil, stmcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(stmcb.builders))
	nodes := make([]*SupportTicketMapping, len(stmcb.builders))
	mutators := make([]Mutator, len(stmcb.builders))
	for i := range stmcb.builders {
		func(i int, root context.Context) {
			builder := stmcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SupportTicketMappingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, stmcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, stmcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, stmcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (stmcb *SupportTicketMappingCreateBulk) SaveX(ctx context.Context) []*SupportTicketMapping {
	v, err := stmcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (stmcb *SupportTicketMappingCreateBulk) Exec(ctx context.Context) error {
	_, err := stmcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (stmcb *SupportTicketMappingCreateBulk) ExecX(ctx context.Context) {
	if err := stmcb.Exec(ctx); err != nil {
		panic(err)
	}
}
