// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"opl-cloud/services/control-plane/ent/predicate"
	"opl-cloud/services/control-plane/ent/workspacesyncevent"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WorkspaceSyncEventUpdate is the builder for updating WorkspaceSyncEvent entities.
type WorkspaceSyncEventUpdate struct {
	config
	hooks    []Hook
	mutation *WorkspaceSyncEventMutation
}

// Where appends a list predicates to the WorkspaceSyncEventUpdate builder.
func (wseu *WorkspaceSyncEventUpdate) Where(ps ...predicate.WorkspaceSyncEvent) *WorkspaceSyncEventUpdate {
	wseu.mutation.Where(ps...)
	return wseu
}

// SetCreatedAt sets the "created_at" field.
func (wseu *WorkspaceSyncEventUpdate) SetCreatedAt(t time.Time) *WorkspaceSyncEventUpdate {
	wseu.mutation.SetCreatedAt(t)
	return wseu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (wseu *WorkspaceSyncEventUpdate) SetNillableCreatedAt(t *time.Time) *WorkspaceSyncEventUpdate {
	if t != nil {
		wseu.SetCreatedAt(*t)
	}
	return wseu
}

// SetUpdatedAt sets the "updated_at" field.
func (wseu *WorkspaceSyncEventUpdate) SetUpdatedAt(t time.Time) *WorkspaceSyncEventUpdate {
	wseu.mutation.SetUpdatedAt(t)
	return wseu
}

// SetOperationID sets the "operation_id" field.
func (wseu *WorkspaceSyncEventUpdate) SetOperationID(s string) *WorkspaceSyncEventUpdate {
	wseu.mutation.SetOperationID(s)
	return wseu
}

// SetNillableOperationID sets the "operation_id" field if the given value is not nil.
func (wseu *WorkspaceSyncEventUpdate) SetNillableOperationID(s *string) *WorkspaceSyncEventUpdate {
	if s != nil {
		wseu.SetOperationID(*s)
	}
	return wseu
}

// SetWorkspaceID sets the "workspace_id" field.
func (wseu *WorkspaceSyncEventUpdate) SetWorkspaceID(s string) *WorkspaceSyncEventUpdate {
	wseu.mutation.SetWorkspaceID(s)
	return wseu
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (wseu *WorkspaceSyncEventUpdate) SetNillableWorkspaceID(s *string) *WorkspaceSyncEventUpdate {
	if s != nil {
		wseu.SetWorkspaceID(*s)
	}
	return wseu
}

// SetCursor sets the "cursor" field.
func (wseu *WorkspaceSyncEventUpdate) SetCursor(i int64) *WorkspaceSyncEventUpdate {
	wseu.mutation.ResetCursor()
	wseu.mutation.SetCursor(i)
	return wseu
}

// SetNillableCursor sets the "cursor" field if the given value is not nil.
func (wseu *WorkspaceSyncEventUpdate) SetNillableCursor(i *int64) *WorkspaceSyncEventUpdate {
	if i != nil {
		wseu.SetCursor(*i)
	}
	return wseu
}

// AddCursor adds i to the "cursor" field.
func (wseu *WorkspaceSyncEventUpdate) AddCursor(i int64) *WorkspaceSyncEventUpdate {
	wseu.mutation.AddCursor(i)
	return wseu
}

// SetEntityKind sets the "entity_kind" field.
func (wseu *WorkspaceSyncEventUpdate) SetEntityKind(s string) *WorkspaceSyncEventUpdate {
	wseu.mutation.SetEntityKind(s)
	return wseu
}

// SetNillableEntityKind sets the "entity_kind" field if the given value is not nil.
func (wseu *WorkspaceSyncEventUpdate) SetNillableEntityKind(s *string) *WorkspaceSyncEventUpdate {
	if s != nil {
		wseu.SetEntityKind(*s)
	}
	return wseu
}

// SetProjectID sets the "project_id" field.
func (wseu *WorkspaceSyncEventUpdate) SetProjectID(s string) *WorkspaceSyncEventUpdate {
	wseu.mutation.SetProjectID(s)
	return wseu
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (wseu *WorkspaceSyncEventUpdate) SetNillableProjectID(s *string) *WorkspaceSyncEventUpdate {
	if s != nil {
		wseu.SetProjectID(*s)
	}
	return wseu
}

// SetTaskID sets the "task_id" field.
func (wseu *WorkspaceSyncEventUpdate) SetTaskID(s string) *WorkspaceSyncEventUpdate {
	wseu.mutation.SetTaskID(s)
	return wseu
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (wseu *WorkspaceSyncEventUpdate) SetNillableTaskID(s *string) *WorkspaceSyncEventUpdate {
	if s != nil {
		wseu.SetTaskID(*s)
	}
	return wseu
}

// SetClientID sets the "client_id" field.
func (wseu *WorkspaceSyncEventUpdate) SetClientID(s string) *WorkspaceSyncEventUpdate {
	wseu.mutation.SetClientID(s)
	return wseu
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (wseu *WorkspaceSyncEventUpdate) SetNillableClientID(s *string) *WorkspaceSyncEventUpdate {
	if s != nil {
		wseu.SetClientID(*s)
	}
	return wseu
}

// SetActorUserID sets the "actor_user_id" field.
func (wseu *WorkspaceSyncEventUpdate) SetActorUserID(s string) *WorkspaceSyncEventUpdate {
	wseu.mutation.SetActorUserID(s)
	return wseu
}

// SetNillableActorUserID sets the "actor_user_id" field if the given value is not nil.
func (wseu *WorkspaceSyncEventUpdate) SetNillableActorUserID(s *string) *WorkspaceSyncEventUpdate {
	if s != nil {
		wseu.SetActorUserID(*s)
	}
	return wseu
}

// SetBaseVersion sets the "base_version" field.
func (wseu *WorkspaceSyncEventUpdate) SetBaseVersion(i int64) *WorkspaceSyncEventUpdate {
	wseu.mutation.ResetBaseVersion()
	wseu.mutation.SetBaseVersion(i)
	return wseu
}

// SetNillableBaseVersion sets the "base_version" field if the given value is not nil.
func (wseu *WorkspaceSyncEventUpdate) SetNillableBaseVersion(i *int64) *WorkspaceSyncEventUpdate {
	if i != nil {
		wseu.SetBaseVersion(*i)
	}
	return wseu
}

// AddBaseVersion adds i to the "base_version" field.
func (wseu *WorkspaceSyncEventUpdate) AddBaseVersion(i int64) *WorkspaceSyncEventUpdate {
	wseu.mutation.AddBaseVersion(i)
	return wseu
}

// SetServerVersion sets the "server_version" field.
func (wseu *WorkspaceSyncEventUpdate) SetServerVersion(i int64) *WorkspaceSyncEventUpdate {
	wseu.mutation.ResetServerVersion()
	wseu.mutation.SetServerVersion(i)
	return wseu
}

// SetNillableServerVersion sets the "server_version" field if the given value is not nil.
func (wseu *WorkspaceSyncEventUpdate) SetNillableServerVersion(i *int64) *WorkspaceSyncEventUpdate {
	if i != nil {
		wseu.SetServerVersion(*i)
	}
	return wseu
}

// AddServerVersion adds i to the "server_version" field.
func (wseu *WorkspaceSyncEventUpdate) AddServerVersion(i int64) *WorkspaceSyncEventUpdate {
	wseu.mutation.AddServerVersion(i)
	return wseu
}

// SetOperation sets the "operation" field.
func (wseu *WorkspaceSyncEventUpdate) SetOperation(s string) *WorkspaceSyncEventUpdate {
	wseu.mutation.SetOperation(s)
	return wseu
}

// SetNillableOperation sets the "operation" field if the given value is not nil.
func (wseu *WorkspaceSyncEventUpdate) SetNillableOperation(s *string) *WorkspaceSyncEventUpdate {
	if s != nil {
		wseu.SetOperation(*s)
	}
	return wseu
}

// SetStatus sets the "status" field.
func (wseu *WorkspaceSyncEventUpdate) SetStatus(s string) *WorkspaceSyncEventUpdate {
	wseu.mutation.SetStatus(s)
	return wseu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (wseu *WorkspaceSyncEventUpdate) SetNillableStatus(s *string) *WorkspaceSyncEventUpdate {
	if s != nil {
		wseu.SetStatus(*s)
	}
	return wseu
}

// SetPayloadJSON sets the "payload_json" field.
func (wseu *WorkspaceSyncEventUpdate) SetPayloadJSON(s string) *WorkspaceSyncEventUpdate {
	wseu.mutation.SetPayloadJSON(s)
	return wseu
}

// SetNillablePayloadJSON sets the "payload_json" field if the given value is not nil.
func (wseu *WorkspaceSyncEventUpdate) SetNillablePayloadJSON(s *string) *WorkspaceSyncEventUpdate {
	if s != nil {
		wseu.SetPayloadJSON(*s)
	}
	return wseu
}

// SetContentDigest sets the "content_digest" field.
func (wseu *WorkspaceSyncEventUpdate) SetContentDigest(s string) *WorkspaceSyncEventUpdate {
	wseu.mutation.SetContentDigest(s)
	return wseu
}

// SetNillableContentDigest sets the "content_digest" field if the given value is not nil.
func (wseu *WorkspaceSyncEventUpdate) SetNillableContentDigest(s *string) *WorkspaceSyncEventUpdate {
	if s != nil {
		wseu.SetContentDigest(*s)
	}
	return wseu
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (wseu *WorkspaceSyncEventUpdate) SetIdempotencyKey(s string) *WorkspaceSyncEventUpdate {
	wseu.mutation.SetIdempotencyKey(s)
	return wseu
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (wseu *WorkspaceSyncEventUpdate) SetNillableIdempotencyKey(s *string) *WorkspaceSyncEventUpdate {
	if s != nil {
		wseu.SetIdempotencyKey(*s)
	}
	return wseu
}

// SetRequestHash sets the "request_hash" field.
func (wseu *WorkspaceSyncEventUpdate) SetRequestHash(s string) *WorkspaceSyncEventUpdate {
	wseu.mutation.SetRequestHash(s)
	return wseu
}

// SetNillableRequestHash sets the "request_hash" field if the given value is not nil.
func (wseu *WorkspaceSyncEventUpdate) SetNillableRequestHash(s *string) *WorkspaceSyncEventUpdate {
	if s != nil {
		wseu.SetRequestHash(*s)
	}
	return wseu
}

// SetConflictID sets the "conflict_id" field.
func (wseu *WorkspaceSyncEventUpdate) SetConflictID(s string) *WorkspaceSyncEventUpdate {
	wseu.mutation.SetConflictID(s)
	return wseu
}

// SetNillableConflictID sets the "conflict_id" field if the given value is not nil.
func (wseu *WorkspaceSyncEventUpdate) SetNillableConflictID(s *string) *WorkspaceSyncEventUpdate {
	if s != nil {
		wseu.SetConflictID(*s)
	}
	return wseu
}

// SetOccurredAt sets the "occurred_at" field.
func (wseu *WorkspaceSyncEventUpdate) SetOccurredAt(t time.Time) *WorkspaceSyncEventUpdate {
	wseu.mutation.SetOccurredAt(t)
	return wseu
}

// SetNillableOccurredAt sets the "occurred_at" field if the given value is not nil.
func (wseu *WorkspaceSyncEventUpdate) SetNillableOccurredAt(t *time.Time) *WorkspaceSyncEventUpdate {
	if t != nil {
		wseu.SetOccurredAt(*t)
	}
	return wseu
}

// Mutation returns the WorkspaceSyncEventMutation object of the builder.
func (wseu *WorkspaceSyncEventUpdate) Mutation() *WorkspaceSyncEventMutation {
	return wseu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (wseu *WorkspaceSyncEventUpdate) Save(ctx context.Context) (int, error) {
	wseu.defaults()
	return withHooks(ctx, wseu.sqlSave, wseu.mutation, wseu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wseu *WorkspaceSyncEventUpdate) SaveX(ctx context.Context) int {
	affected, err := wseu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (wseu *WorkspaceSyncEventUpdate) Exec(ctx context.Context) error {
	_, err := wseu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wseu *WorkspaceSyncEventUpdate) ExecX(ctx context.Context) {
	if err := wseu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (wseu *WorkspaceSyncEventUpdate) defaults() {
	if _, ok := wseu.mutation.UpdatedAt(); !ok {
		v := workspacesyncevent.UpdateDefaultUpdatedAt()
		wseu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wseu *WorkspaceSyncEventUpdate) check() error {
	if v, ok := wseu.mutation.OperationID(); ok {
		if err := workspacesyncevent.OperationIDValidator(v); err != nil {
			return &ValidationError{Name: "operation_id", err: fmt.Errorf(`ent: validator failed for field "WorkspaceSyncEvent.operation_id": %w`, err)}
		}
	}
	if v, ok := wseu.mutation.WorkspaceID(); ok {
		if err := workspacesyncevent.WorkspaceIDValidator(v); err != nil {
			return &ValidationError{Name: "workspace_id", err: fmt.Errorf(`ent: validator failed for field "WorkspaceSyncEvent.workspace_id": %w`, err)}
		}
	}
	if v, ok := wseu.mutation.EntityKind(); ok {
		if err := workspacesyncevent.EntityKindValidator(v); err != nil {
			return &ValidationError{Name: "entity_kind", err: fmt.Errorf(`ent: validator failed for field "WorkspaceSyncEvent.entity_kind": %w`, err)}
		}
	}
	if v, ok := wseu.mutation.ProjectID(); ok {
		if err := workspacesyncevent.ProjectIDValidator(v); err != nil {
			return &ValidationError{Name: "project_id", err: fmt.Errorf(`ent: validator failed for field "WorkspaceSyncEvent.project_id": %w`, err)}
		}
	}
	if v, ok := wseu.mutation.ClientID(); ok {
		if err := workspacesyncevent.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "WorkspaceSyncEvent.client_id": %w`, err)}
		}
	}
	if v, ok := wseu.mutation.ActorUserID(); ok {
		if err := workspacesyncevent.ActorUserIDValidator(v); err != nil {
			return &ValidationError{Name: "actor_user_id", err: fmt.Errorf(`ent: validator failed for field "WorkspaceSyncEvent.actor_user_id": %w`, err)}
		}
	}
	if v, ok := wseu.mutation.Operation(); ok {
		if err := workspacesyncevent.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`ent: validator failed for field "WorkspaceSyncEvent.operation": %w`, err)}
		}
	}
	if v, ok := wseu.mutation.Status(); ok {
		if err := workspacesyncevent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "WorkspaceSyncEvent.status": %w`, err)}
		}
	}
	if v, ok := wseu.mutation.IdempotencyKey(); ok {
		if err := workspacesyncevent.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "WorkspaceSyncEvent.idempotency_key": %w`, err)}
		}
	}
	if v, ok := wseu.mutation.RequestHash(); ok {
		if err := workspacesyncevent.RequestHashValidator(v); err != nil {
			return &ValidationError{Name: "request_hash", err: fmt.Errorf(`ent: validator failed for field "WorkspaceSyncEvent.request_hash": %w`, err)}
		}
	}
	return nil
}

func (wseu *WorkspaceSyncEventUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := wseu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(workspacesyncevent.Table, workspacesyncevent.Columns, sqlgraph.NewFieldSpec(workspacesyncevent.FieldID, field.TypeString))
	if ps := wseu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wseu.mutation.CreatedAt(); ok {
		_spec.SetField(workspacesyncevent.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := wseu.mutation.UpdatedAt(); ok {
		_spec.SetField(workspacesyncevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := wseu.mutation.OperationID(); ok {
		_spec.SetField(workspacesyncevent.FieldOperationID, field.TypeString, value)
	}
	if value, ok := wseu.mutation.WorkspaceID(); ok {
		_spec.SetField(workspacesyncevent.FieldWorkspaceID, field.TypeString, value)
	}
	if value, ok := wseu.mutation.Cursor(); ok {
		_spec.SetField(workspacesyncevent.FieldCursor, field.TypeInt64, value)
	}
	if value, ok := wseu.mutation.AddedCursor(); ok {
		_spec.AddField(workspacesyncevent.FieldCursor, field.TypeInt64, value)
	}
	if value, ok := wseu.mutation.EntityKind(); ok {
		_spec.SetField(workspacesyncevent.FieldEntityKind, field.TypeString, value)
	}
	if value, ok := wseu.mutation.ProjectID(); ok {
		_spec.SetField(workspacesyncevent.FieldProjectID, field.TypeString, value)
	}
	if value, ok := wseu.mutation.TaskID(); ok {
		_spec.SetField(workspacesyncevent.FieldTaskID, field.TypeString, value)
	}
	if value, ok := wseu.mutation.ClientID(); ok {
		_spec.SetField(workspacesyncevent.FieldClientID, field.TypeString, value)
	}
	if value, ok := wseu.mutation.ActorUserID(); ok {
		_spec.SetField(workspacesyncevent.FieldActorUserID, field.TypeString, value)
	}
	if value, ok := wseu.mutation.BaseVersion(); ok {
		_spec.SetField(workspacesyncevent.FieldBaseVersion, field.TypeInt64, value)
	}
	if value, ok := wseu.mutation.AddedBaseVersion(); ok {
		_spec.AddField(workspacesyncevent.FieldBaseVersion, field.TypeInt64, value)
	}
	if value, ok := wseu.mutation.ServerVersion(); ok {
		_spec.SetField(workspacesyncevent.FieldServerVersion, field.TypeInt64, value)
	}
	if value, ok := wseu.mutation.AddedServerVersion(); ok {
		_spec.AddField(workspacesyncevent.FieldServerVersion, field.TypeInt64, value)
	}
	if value, ok := wseu.mutation.Operation(); ok {
		_spec.SetField(workspacesyncevent.FieldOperation, field.TypeString, value)
	}
	if value, ok := wseu.mutation.Status(); ok {
		_spec.SetField(workspacesyncevent.FieldStatus, field.TypeString, value)
	}
	if value, ok := wseu.mutation.PayloadJSON(); ok {
		_spec.SetField(workspacesyncevent.FieldPayloadJSON, field.TypeString, value)
	}
	if value, ok := wseu.mutation.ContentDigest(); ok {
		_spec.SetField(workspacesyncevent.FieldContentDigest, field.TypeString, value)
	}
	if value, ok := wseu.mutation.IdempotencyKey(); ok {
		_spec.SetField(workspacesyncevent.FieldIdempotencyKey, field.TypeString, value)
	}
	if value, ok := wseu.mutation.RequestHash(); ok {
		_spec.SetField(workspacesyncevent.FieldRequestHash, field.TypeString, value)
	}
	if value, ok := wseu.mutation.ConflictID(); ok {
		_spec.SetField(workspacesyncevent.FieldConflictID, field.TypeString, value)
	}
	if value, ok := wseu.mutation.OccurredAt(); ok {
		_spec.SetField(workspacesyncevent.FieldOccurredAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, wseu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workspacesyncevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	wseu.mutation.done = true
	return n, nil
}

// WorkspaceSyncEventUpdateOne is the builder for updating a single WorkspaceSyncEvent entity.
type WorkspaceSyncEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkspaceSyncEventMutation
}

// SetCreatedAt sets the "created_at" field.
func (wseuo *WorkspaceSyncEventUpdateOne) SetCreatedAt(t time.Time) *WorkspaceSyncEventUpdateOne {
	wseuo.mutation.SetCreatedAt(t)
	return wseuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (wseuo *WorkspaceSyncEventUpdateOne) SetNillableCreatedAt(t *time.Time) *WorkspaceSyncEventUpdateOne {
	if t != nil {
		wseuo.SetCreatedAt(*t)
	}
	return wseuo
}

// SetUpdatedAt sets the "updated_at" field.
func (wseuo *WorkspaceSyncEventUpdateOne) SetUpdatedAt(t time.Time) *WorkspaceSyncEventUpdateOne {
	wseuo.mutation.SetUpdatedAt(t)
	return wseuo
}

// SetOperationID sets the "operation_id" field.
func (wseuo *WorkspaceSyncEventUpdateOne) SetOperationID(s string) *WorkspaceSyncEventUpdateOne {
	wseuo.mutation.SetOperationID(s)
	return wseuo
}

// SetNillableOperationID sets the "operation_id" field if the given value is not nil.
func (wseuo *WorkspaceSyncEventUpdateOne) SetNillableOperationID(s *string) *WorkspaceSyncEventUpdateOne {
	if s != nil {
		wseuo.SetOperationID(*s)
	}
	return wseuo
}

// SetWorkspaceID sets the "workspace_id" field.
func (wseuo *WorkspaceSyncEventUpdateOne) SetWorkspaceID(s string) *WorkspaceSyncEventUpdateOne {
	wseuo.mutation.SetWorkspaceID(s)
	return wseuo
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (wseuo *WorkspaceSyncEventUpdateOne) SetNillableWorkspaceID(s *string) *WorkspaceSyncEventUpdateOne {
	if s != nil {
		wseuo.SetWorkspaceID(*s)
	}
	return wseuo
}

// SetCursor sets the "cursor" field.
func (wseuo *WorkspaceSyncEventUpdateOne) SetCursor(i int64) *WorkspaceSyncEventUpdateOne {
	wseuo.mutation.ResetCursor()
	wseuo.mutation.SetCursor(i)
	return wseuo
}

// SetNillableCursor sets the "cursor" field if the given value is not nil.
func (wseuo *WorkspaceSyncEventUpdateOne) SetNillableCursor(i *int64) *WorkspaceSyncEventUpdateOne {
	if i != nil {
		wseuo.SetCursor(*i)
	}
	return wseuo
}

// AddCursor adds i to the "cursor" field.
func (wseuo *WorkspaceSyncEventUpdateOne) AddCursor(i int64) *WorkspaceSyncEventUpdateOne {
	wseuo.mutation.AddCursor(i)
	return wseuo
}

// SetEntityKind sets the "entity_kind" field.
func (wseuo *WorkspaceSyncEventUpdateOne) SetEntityKind(s string) *WorkspaceSyncEventUpdateOne {
	wseuo.mutation.SetEntityKind(s)
	return wseuo
}

// SetNillableEntityKind sets the "entity_kind" field if the given value is not nil.
func (wseuo *WorkspaceSyncEventUpdateOne) SetNillableEntityKind(s *string) *WorkspaceSyncEventUpdateOne {
	if s != nil {
		wseuo.SetEntityKind(*s)
	}
	return wseuo
}

// SetProjectID sets the "project_id" field.
func (wseuo *WorkspaceSyncEventUpdateOne) SetProjectID(s string) *WorkspaceSyncEventUpdateOne {
	wseuo.mutation.SetProjectID(s)
	return wseuo
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (wseuo *WorkspaceSyncEventUpdateOne) SetNillableProjectID(s *string) *WorkspaceSyncEventUpdateOne {
	if s != nil {
		wseuo.SetProjectID(*s)
	}
	return wseuo
}

// SetTaskID sets the "task_id" field.
func (wseuo *WorkspaceSyncEventUpdateOne) SetTaskID(s string) *WorkspaceSyncEventUpdateOne {
	wseuo.mutation.SetTaskID(s)
	return wseuo
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (wseuo *WorkspaceSyncEventUpdateOne) SetNillableTaskID(s *string) *WorkspaceSyncEventUpdateOne {
	if s != nil {
		wseuo.SetTaskID(*s)
	}
	return wseuo
}

// SetClientID sets the "client_id" field.
func (wseuo *WorkspaceSyncEventUpdateOne) SetClientID(s string) *WorkspaceSyncEventUpdateOne {
	wseuo.mutation.SetClientID(s)
	return wseuo
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (wseuo *WorkspaceSyncEventUpdateOne) SetNillableClientID(s *string) *WorkspaceSyncEventUpdateOne {
	if s != nil {
		wseuo.SetClientID(*s)
	}
	return wseuo
}

// SetActorUserID sets the "actor_user_id" field.
func (wseuo *WorkspaceSyncEventUpdateOne) SetActorUserID(s string) *WorkspaceSyncEventUpdateOne {
	wseuo.mutation.SetActorUserID(s)
	return wseuo
}

// SetNillableActorUserID sets the "actor_user_id" field if the given value is not nil.
func (wseuo *WorkspaceSyncEventUpdateOne) SetNillableActorUserID(s *string) *WorkspaceSyncEventUpdateOne {
	if s != nil {
		wseuo.SetActorUserID(*s)
	}
	return wseuo
}

// SetBaseVersion sets the "base_version" field.
func (wseuo *WorkspaceSyncEventUpdateOne) SetBaseVersion(i int64) *WorkspaceSyncEventUpdateOne {
	wseuo.mutation.ResetBaseVersion()
	wseuo.mutation.SetBaseVersion(i)
	return wseuo
}

// SetNillableBaseVersion sets the "base_version" field if the given value is not nil.
func (wseuo *WorkspaceSyncEventUpdateOne) SetNillableBaseVersion(i *int64) *WorkspaceSyncEventUpdateOne {
	if i != nil {
		wseuo.SetBaseVersion(*i)
	}
	return wseuo
}

// AddBaseVersion adds i to the "base_version" field.
func (wseuo *WorkspaceSyncEventUpdateOne) AddBaseVersion(i int64) *WorkspaceSyncEventUpdateOne {
	wseuo.mutation.AddBaseVersion(i)
	return wseuo
}

// SetServerVersion sets the "server_version" field.
func (wseuo *WorkspaceSyncEventUpdateOne) SetServerVersion(i int64) *WorkspaceSyncEventUpdateOne {
	wseuo.mutation.ResetServerVersion()
	wseuo.mutation.SetServerVersion(i)
	return wseuo
}

// SetNillableServerVersion sets the "server_version" field if the given value is not nil.
func (wseuo *WorkspaceSyncEventUpdateOne) SetNillableServerVersion(i *int64) *WorkspaceSyncEventUpdateOne {
	if i != nil {
		wseuo.SetServerVersion(*i)
	}
	return wseuo
}

// AddServerVersion adds i to the "server_version" field.
func (wseuo *WorkspaceSyncEventUpdateOne) AddServerVersion(i int64) *WorkspaceSyncEventUpdateOne {
	wseuo.mutation.AddServerVersion(i)
	return wseuo
}

// SetOperation sets the "operation" field.
func (wseuo *WorkspaceSyncEventUpdateOne) SetOperation(s string) *WorkspaceSyncEventUpdateOne {
	wseuo.mutation.SetOperation(s)
	return wseuo
}

// SetNillableOperation sets the "operation" field if the given value is not nil.
func (wseuo *WorkspaceSyncEventUpdateOne) SetNillableOperation(s *string) *WorkspaceSyncEventUpdateOne {
	if s != nil {
		wseuo.SetOperation(*s)
	}
	return wseuo
}

// SetStatus sets the "status" field.
func (wseuo *WorkspaceSyncEventUpdateOne) SetStatus(s string) *WorkspaceSyncEventUpdateOne {
	wseuo.mutation.SetStatus(s)
	return wseuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (wseuo *WorkspaceSyncEventUpdateOne) SetNillableStatus(s *string) *WorkspaceSyncEventUpdateOne {
	if s != nil {
		wseuo.SetStatus(*s)
	}
	return wseuo
}

// SetPayloadJSON sets the "payload_json" field.
func (wseuo *WorkspaceSyncEventUpdateOne) SetPayloadJSON(s string) *WorkspaceSyncEventUpdateOne {
	wseuo.mutation.SetPayloadJSON(s)
	return wseuo
}

// SetNillablePayloadJSON sets the "payload_json" field if the given value is not nil.
func (wseuo *WorkspaceSyncEventUpdateOne) SetNillablePayloadJSON(s *string) *WorkspaceSyncEventUpdateOne {
	if s != nil {
		wseuo.SetPayloadJSON(*s)
	}
	return wseuo
}

// SetContentDigest sets the "content_digest" field.
func (wseuo *WorkspaceSyncEventUpdateOne) SetContentDigest(s string) *WorkspaceSyncEventUpdateOne {
	wseuo.mutation.SetContentDigest(s)
	return wseuo
}

// SetNillableContentDigest sets the "content_digest" field if the given value is not nil.
func (wseuo *WorkspaceSyncEventUpdateOne) SetNillableContentDigest(s *string) *WorkspaceSyncEventUpdateOne {
	if s != nil {
		wseuo.SetContentDigest(*s)
	}
	return wseuo
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (wseuo *WorkspaceSyncEventUpdateOne) SetIdempotencyKey(s string) *WorkspaceSyncEventUpdateOne {
	wseuo.mutation.SetIdempotencyKey(s)
	return wseuo
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (wseuo *WorkspaceSyncEventUpdateOne) SetNillableIdempotencyKey(s *string) *WorkspaceSyncEventUpdateOne {
	if s != nil {
		wseuo.SetIdempotencyKey(*s)
	}
	return wseuo
}

// SetRequestHash sets the "request_hash" field.
func (wseuo *WorkspaceSyncEventUpdateOne) SetRequestHash(s string) *WorkspaceSyncEventUpdateOne {
	wseuo.mutation.SetRequestHash(s)
	return wseuo
}

// SetNillableRequestHash sets the "request_hash" field if the given value is not nil.
func (wseuo *WorkspaceSyncEventUpdateOne) SetNillableRequestHash(s *string) *WorkspaceSyncEventUpdateOne {
	if s != nil {
		wseuo.SetRequestHash(*s)
	}
	return wseuo
}

// SetConflictID sets the "conflict_id" field.
func (wseuo *WorkspaceSyncEventUpdateOne) SetConflictID(s string) *WorkspaceSyncEventUpdateOne {
	wseuo.mutation.SetConflictID(s)
	return wseuo
}

// SetNillableConflictID sets the "conflict_id" field if the given value is not nil.
func (wseuo *WorkspaceSyncEventUpdateOne) SetNillableConflictID(s *string) *WorkspaceSyncEventUpdateOne {
	if s != nil {
		wseuo.SetConflictID(*s)
	}
	return wseuo
}

// SetOccurredAt sets the "occurred_at" field.
func (wseuo *WorkspaceSyncEventUpdateOne) SetOccurredAt(t time.Time) *WorkspaceSyncEventUpdateOne {
	wseuo.mutation.SetOccurredAt(t)
	return wseuo
}

// SetNillableOccurredAt sets the "occurred_at" field if the given value is not nil.
func (wseuo *WorkspaceSyncEventUpdateOne) SetNillableOccurredAt(t *time.Time) *WorkspaceSyncEventUpdateOne {
	if t != nil {
		wseuo.SetOccurredAt(*t)
	}
	return wseuo
}

// Mutation returns the WorkspaceSyncEventMutation object of the builder.
func (wseuo *WorkspaceSyncEventUpdateOne) Mutation() *WorkspaceSyncEventMutation {
	return wseuo.mutation
}

// Where appends a list predicates to the WorkspaceSyncEventUpdate builder.
func (wseuo *WorkspaceSyncEventUpdateOne) Where(ps ...predicate.WorkspaceSyncEvent) *WorkspaceSyncEventUpdateOne {
	wseuo.mutation.Where(ps...)
	return wseuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (wseuo *WorkspaceSyncEventUpdateOne) Select(field string, fields ...string) *WorkspaceSyncEventUpdateOne {
	wseuo.fields = append([]string{field}, fields...)
	return wseuo
}

// Save executes the query and returns the updated WorkspaceSyncEvent entity.
func (wseuo *WorkspaceSyncEventUpdateOne) Save(ctx context.Context) (*WorkspaceSyncEvent, error) {
	wseuo.defaults()
	return withHooks(ctx, wseuo.sqlSave, wseuo.mutation, wseuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wseuo *WorkspaceSyncEventUpdateOne) SaveX(ctx context.Context) *WorkspaceSyncEvent {
	node, err := wseuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (wseuo *WorkspaceSyncEventUpdateOne) Exec(ctx context.Context) error {
	_, err := wseuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wseuo *WorkspaceSyncEventUpdateOne) ExecX(ctx context.Context) {
	if err := wseuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (wseuo *WorkspaceSyncEventUpdateOne) defaults() {
	if _, ok := wseuo.mutation.UpdatedAt(); !ok {
		v := workspacesyncevent.UpdateDefaultUpdatedAt()
		wseuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wseuo *WorkspaceSyncEventUpdateOne) check() error {
	if v, ok := wseuo.mutation.OperationID(); ok {
		if err := workspacesyncevent.OperationIDValidator(v); err != nil {
			return &ValidationError{Name: "operation_id", err: fmt.Errorf(`ent: validator failed for field "WorkspaceSyncEvent.operation_id": %w`, err)}
		}
	}
	if v, ok := wseuo.mutation.WorkspaceID(); ok {
		if err := workspacesyncevent.WorkspaceIDValidator(v); err != nil {
			return &ValidationError{Name: "workspace_id", err: fmt.Errorf(`ent: validator failed for field "WorkspaceSyncEvent.workspace_id": %w`, err)}
		}
	}
	if v, ok := wseuo.mutation.EntityKind(); ok {
		if err := workspacesyncevent.EntityKindValidator(v); err != nil {
			return &ValidationError{Name: "entity_kind", err: fmt.Errorf(`ent: validator failed for field "WorkspaceSyncEvent.entity_kind": %w`, err)}
		}
	}
	if v, ok := wseuo.mutation.ProjectID(); ok {
		if err := workspacesyncevent.ProjectIDValidator(v); err != nil {
			return &ValidationError{Name: "project_id", err: fmt.Errorf(`ent: validator failed for field "WorkspaceSyncEvent.project_id": %w`, err)}
		}
	}
	if v, ok := wseuo.mutation.ClientID(); ok {
		if err := workspacesyncevent.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "WorkspaceSyncEvent.client_id": %w`, err)}
		}
	}
	if v, ok := wseuo.mutation.ActorUserID(); ok {
		if err := workspacesyncevent.ActorUserIDValidator(v); err != nil {
			return &ValidationError{Name: "actor_user_id", err: fmt.Errorf(`ent: validator failed for field "WorkspaceSyncEvent.actor_user_id": %w`, err)}
		}
	}
	if v, ok := wseuo.mutation.Operation(); ok {
		if err := workspacesyncevent.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`ent: validator failed for field "WorkspaceSyncEvent.operation": %w`, err)}
		}
	}
	if v, ok := wseuo.mutation.Status(); ok {
		if err := workspacesyncevent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "WorkspaceSyncEvent.status": %w`, err)}
		}
	}
	if v, ok := wseuo.mutation.IdempotencyKey(); ok {
		if err := workspacesyncevent.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "WorkspaceSyncEvent.idempotency_key": %w`, err)}
		}
	}
	if v, ok := wseuo.mutation.RequestHash(); ok {
		if err := workspacesyncevent.RequestHashValidator(v); err != nil {
			return &ValidationError{Name: "request_hash", err: fmt.Errorf(`ent: validator failed for field "WorkspaceSyncEvent.request_hash": %w`, err)}
		}
	}
	return nil
}

func (wseuo *WorkspaceSyncEventUpdateOne) sqlSave(ctx context.Context) (_node *WorkspaceSyncEvent, err error) {
	if err := wseuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workspacesyncevent.Table, workspacesyncevent.Columns, sqlgraph.NewFieldSpec(workspacesyncevent.FieldID, field.TypeString))
	id, ok := wseuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WorkspaceSyncEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := wseuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workspacesyncevent.FieldID)
		for _, f := range fields {
			if !workspacesyncevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workspacesyncevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := wseuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wseuo.mutation.CreatedAt(); ok {
		_spec.SetField(workspacesyncevent.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := wseuo.mutation.UpdatedAt(); ok {
		_spec.SetField(workspacesyncevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := wseuo.mutation.OperationID(); ok {
		_spec.SetField(workspacesyncevent.FieldOperationID, field.TypeString, value)
	}
	if value, ok := wseuo.mutation.WorkspaceID(); ok {
		_spec.SetField(workspacesyncevent.FieldWorkspaceID, field.TypeString, value)
	}
	if value, ok := wseuo.mutation.Cursor(); ok {
		_spec.SetField(workspacesyncevent.FieldCursor, field.TypeInt64, value)
	}
	if value, ok := wseuo.mutation.AddedCursor(); ok {
		_spec.AddField(workspacesyncevent.FieldCursor, field.TypeInt64, value)
	}
	if value, ok := wseuo.mutation.EntityKind(); ok {
		_spec.SetField(workspacesyncevent.FieldEntityKind, field.TypeString, value)
	}
	if value, ok := wseuo.mutation.ProjectID(); ok {
		_spec.SetField(workspacesyncevent.FieldProjectID, field.TypeString, value)
	}
	if value, ok := wseuo.mutation.TaskID(); ok {
		_spec.SetField(workspacesyncevent.FieldTaskID, field.TypeString, value)
	}
	if value, ok := wseuo.mutation.ClientID(); ok {
		_spec.SetField(workspacesyncevent.FieldClientID, field.TypeString, value)
	}
	if value, ok := wseuo.mutation.ActorUserID(); ok {
		_spec.SetField(workspacesyncevent.FieldActorUserID, field.TypeString, value)
	}
	if value, ok := wseuo.mutation.BaseVersion(); ok {
		_spec.SetField(workspacesyncevent.FieldBaseVersion, field.TypeInt64, value)
	}
	if value, ok := wseuo.mutation.AddedBaseVersion(); ok {
		_spec.AddField(workspacesyncevent.FieldBaseVersion, field.TypeInt64, value)
	}
	if value, ok := wseuo.mutation.ServerVersion(); ok {
		_spec.SetField(workspacesyncevent.FieldServerVersion, field.TypeInt64, value)
	}
	if value, ok := wseuo.mutation.AddedServerVersion(); ok {
		_spec.AddField(workspacesyncevent.FieldServerVersion, field.TypeInt64, value)
	}
	if value, ok := wseuo.mutation.Operation(); ok {
		_spec.SetField(workspacesyncevent.FieldOperation, field.TypeString, value)
	}
	if value, ok := wseuo.mutation.Status(); ok {
		_spec.SetField(workspacesyncevent.FieldStatus, field.TypeString, value)
	}
	if value, ok := wseuo.mutation.PayloadJSON(); ok {
		_spec.SetField(workspacesyncevent.FieldPayloadJSON, field.TypeString, value)
	}
	if value, ok := wseuo.mutation.ContentDigest(); ok {
		_spec.SetField(workspacesyncevent.FieldContentDigest, field.TypeString, value)
	}
	if value, ok := wseuo.mutation.IdempotencyKey(); ok {
		_spec.SetField(workspacesyncevent.FieldIdempotencyKey, field.TypeString, value)
	}
	if value, ok := wseuo.mutation.RequestHash(); ok {
		_spec.SetField(workspacesyncevent.FieldRequestHash, field.TypeString, value)
	}
	if value, ok := wseuo.mutation.ConflictID(); ok {
		_spec.SetField(workspacesyncevent.FieldConflictID, field.TypeString, value)
	}
	if value, ok := wseuo.mutation.OccurredAt(); ok {
		_spec.SetField(workspacesyncevent.FieldOccurredAt, field.TypeTime, value)
	}
	_node = &WorkspaceSyncEvent{config: wseuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, wseuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workspacesyncevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	wseuo.mutation.done = true
	return _node, nil
}
