// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"opl-cloud/services/control-plane/ent/workspacebackup"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// WorkspaceBackup is the model entity for the WorkspaceBackup schema.
type WorkspaceBackup struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID string `json:"account_id,omitempty"`
	// WorkspaceID holds the value of the "workspace_id" field.
	WorkspaceID string `json:"workspace_id,omitempty"`
	// StorageID holds the value of the "storage_id" field.
	StorageID string `json:"storage_id,omitempty"`
	// SnapshotID holds the value of the "snapshot_id" field.
	SnapshotID string `json:"snapshot_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// IdempotencyKey holds the value of the "idempotency_key" field.
	IdempotencyKey string `json:"idempotency_key,omitempty"`
	// RequestHash holds the value of the "request_hash" field.
	RequestHash string `json:"request_hash,omitempty"`
	// ManifestJSON holds the value of the "manifest_json" field.
	ManifestJSON string `json:"manifest_json,omitempty"`
	// RestoredStorageID holds the value of the "restored_storage_id" field.
	RestoredStorageID string `json:"restored_storage_id,omitempty"`
	selectValues      sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WorkspaceBackup) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case workspacebackup.FieldID, workspacebackup.FieldAccountID, workspacebackup.FieldWorkspaceID, workspacebackup.FieldStorageID, workspacebackup.FieldSnapshotID, workspacebackup.FieldStatus, workspacebackup.FieldIdempotencyKey, workspacebackup.FieldRequestHash, workspacebackup.FieldManifestJSON, workspacebackup.FieldRestoredStorageID:
			values[i] = new(sql.NullString)
		case workspacebackup.FieldCreatedAt, workspacebackup.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WorkspaceBackup fields.
func (wb *WorkspaceBackup) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case workspacebackup.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				wb.ID = value.String
			}
		case workspacebackup.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				wb.CreatedAt = value.Time
			}
		case workspacebackup.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				wb.UpdatedAt = value.Time
			}
		case workspacebackup.FieldAccountID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				wb.AccountID = value.String
			}
		case workspacebackup.FieldWorkspaceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field workspace_id", values[i])
			} else if value.Valid {
				wb.WorkspaceID = value.String
			}
		case workspacebackup.FieldStorageID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field storage_id", values[i])
			} else if value.Valid {
				wb.StorageID = value.String
			}
		case workspacebackup.FieldSnapshotID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field snapshot_id", values[i])
			} else if value.Valid {
				wb.SnapshotID = value.String
			}
		case workspacebackup.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				wb.Status = value.String
			}
		case workspacebackup.FieldIdempotencyKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idempotency_key", values[i])
			} else if value.Valid {
				wb.IdempotencyKey = value.String
			}
		case workspacebackup.FieldRequestHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_hash", values[i])
			} else if value.Valid {
				wb.RequestHash = value.String
			}
		case workspacebackup.FieldManifestJSON:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field manifest_json", values[i])
			} else if value.Valid {
				wb.ManifestJSON = value.String
			}
		case workspacebackup.FieldRestoredStorageID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field restored_storage_id", values[i])
			} else if value.Valid {
				wb.RestoredStorageID = value.String
			}
		default:
			wb.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WorkspaceBackup.
// This includes values selected through modifiers, order, etc.
func (wb *WorkspaceBackup) Value(name string) (ent.Value, error) {
	return wb.selectValues.Get(name)
}

// Update returns a builder for updating this WorkspaceBackup.
// Note that you need to call WorkspaceBackup.Unwrap() before calling this method if this WorkspaceBackup
// was returned from a transaction, and the transaction was committed or rolled back.
func (wb *WorkspaceBackup) Update() *WorkspaceBackupUpdateOne {
	return NewWorkspaceBackupClient(wb.config).UpdateOne(wb)
}

// Unwrap unwraps the WorkspaceBackup entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (wb *WorkspaceBackup) Unwrap() *WorkspaceBackup {
	_tx, ok := wb.config.driver.(*txDriver)
	if !ok {
		panic("ent: WorkspaceBackup is not a transactional entity")
	}
	wb.config.driver = _tx.drv
	return wb
}

// String implements the fmt.Stringer.
func (wb *WorkspaceBackup) String() string {
	var builder strings.Builder
	builder.WriteString("WorkspaceBackup(")
	builder.WriteString(fmt.Sprintf("id=%v, ", wb.ID))
	builder.WriteString("created_at=")
	builder.WriteString(wb.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(wb.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(wb.AccountID)
	builder.WriteString(", ")
	builder.WriteString("workspace_id=")
	builder.WriteString(wb.WorkspaceID)
	builder.WriteString(", ")
	builder.WriteString("storage_id=")
	builder.WriteString(wb.StorageID)
	builder.WriteString(", ")
	builder.WriteString("snapshot_id=")
	builder.WriteString(wb.SnapshotID)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(wb.Status)
	builder.WriteString(", ")
	builder.WriteString("idempotency_key=")
	builder.WriteString(wb.IdempotencyKey)
	builder.WriteString(", ")
	builder.WriteString("request_hash=")
	builder.WriteString(wb.RequestHash)
	builder.WriteString(", ")
	builder.WriteString("manifest_json=")
	builder.WriteString(wb.ManifestJSON)
	builder.WriteString(", ")
	builder.WriteString("restored_storage_id=")
	builder.WriteString(wb.RestoredStorageID)
	builder.WriteByte(')')
	return builder.String()
}

// WorkspaceBackups is a parsable slice of WorkspaceBackup.
type WorkspaceBackups []*WorkspaceBackup
