// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// EvidenceReceipt is the predicate function for evidencereceipt builders.
type EvidenceReceipt func(*sql.Selector)

// IdempotencyKey is the predicate function for idempotencykey builders.
type IdempotencyKey func(*sql.Selector)

// ReconciliationReport is the predicate function for reconciliationreport builders.
type ReconciliationReport func(*sql.Selector)

// ReviewPolicy is the predicate function for reviewpolicy builders.
type ReviewPolicy func(*sql.Selector)
