// Code generated by ent, DO NOT EDIT.

package archivedadminauditevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the archivedadminauditevent type in the database.
	Label = "archived_admin_audit_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldActorUserID holds the string denoting the actor_user_id field in the database.
	FieldActorUserID = "actor_user_id"
	// FieldActorRole holds the string denoting the actor_role field in the database.
	FieldActorRole = "actor_role"
	// FieldActorAccountID holds the string denoting the actor_account_id field in the database.
	FieldActorAccountID = "actor_account_id"
	// FieldTargetAccountID holds the string denoting the target_account_id field in the database.
	FieldTargetAccountID = "target_account_id"
	// FieldAction holds the string denoting the action field in the database.
	FieldAction = "action"
	// FieldResourceKind holds the string denoting the resource_kind field in the database.
	FieldResourceKind = "resource_kind"
	// FieldResourceID holds the string denoting the resource_id field in the database.
	FieldResourceID = "resource_id"
	// FieldIPAddress holds the string denoting the ip_address field in the database.
	FieldIPAddress = "ip_address"
	// FieldUserAgent holds the string denoting the user_agent field in the database.
	FieldUserAgent = "user_agent"
	// FieldResult holds the string denoting the result field in the database.
	FieldResult = "result"
	// Table holds the table name of the archivedadminauditevent in the database.
	Table = "control_plane_archived_admin_audit_events"
)

// Columns holds all SQL columns for archivedadminauditevent fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldActorUserID,
	FieldActorRole,
	FieldActorAccountID,
	FieldTargetAccountID,
	FieldAction,
	FieldResourceKind,
	FieldResourceID,
	FieldIPAddress,
	FieldUserAgent,
	FieldResult,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultActorUserID holds the default value on creation for the "actor_user_id" field.
	DefaultActorUserID string
	// DefaultActorRole holds the default value on creation for the "actor_role" field.
	DefaultActorRole string
	// DefaultActorAccountID holds the default value on creation for the "actor_account_id" field.
	DefaultActorAccountID string
	// DefaultTargetAccountID holds the default value on creation for the "target_account_id" field.
	DefaultTargetAccountID string
	// DefaultAction holds the default value on creation for the "action" field.
	DefaultAction string
	// DefaultResourceKind holds the default value on creation for the "resource_kind" field.
	DefaultResourceKind string
	// DefaultResourceID holds the default value on creation for the "resource_id" field.
	DefaultResourceID string
	// DefaultIPAddress holds the default value on creation for the "ip_address" field.
	DefaultIPAddress string
	// DefaultUserAgent holds the default value on creation for the "user_agent" field.
	DefaultUserAgent string
	// DefaultResult holds the default value on creation for the "result" field.
	DefaultResult string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the ArchivedAdminAuditEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByActorUserID orders the results by the actor_user_id field.
func ByActorUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActorUserID, opts...).ToFunc()
}

// ByActorRole orders the results by the actor_role field.
func ByActorRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActorRole, opts...).ToFunc()
}

// ByActorAccountID orders the results by the actor_account_id field.
func ByActorAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActorAccountID, opts...).ToFunc()
}

// ByTargetAccountID orders the results by the target_account_id field.
func ByTargetAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetAccountID, opts...).ToFunc()
}

// ByAction orders the results by the action field.
func ByAction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAction, opts...).ToFunc()
}

// ByResourceKind orders the results by the resource_kind field.
func ByResourceKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceKind, opts...).ToFunc()
}

// ByResourceID orders the results by the resource_id field.
func ByResourceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceID, opts...).ToFunc()
}

// ByIPAddress orders the results by the ip_address field.
func ByIPAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIPAddress, opts...).ToFunc()
}

// ByUserAgent orders the results by the user_agent field.
func ByUserAgent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserAgent, opts...).ToFunc()
}

// ByResult orders the results by the result field.
func ByResult(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResult, opts...).ToFunc()
}
