// Code generated by ent, DO NOT EDIT.

package wallettransactionprojection

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the wallettransactionprojection type in the database.
	Label = "wallet_transaction_projection"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldLedgerEntryID holds the string denoting the ledger_entry_id field in the database.
	FieldLedgerEntryID = "ledger_entry_id"
	// FieldResourceID holds the string denoting the resource_id field in the database.
	FieldResourceID = "resource_id"
	// FieldWorkspaceID holds the string denoting the workspace_id field in the database.
	FieldWorkspaceID = "workspace_id"
	// FieldComputeAllocationID holds the string denoting the compute_allocation_id field in the database.
	FieldComputeAllocationID = "compute_allocation_id"
	// FieldStorageID holds the string denoting the storage_id field in the database.
	FieldStorageID = "storage_id"
	// FieldSettlementID holds the string denoting the settlement_id field in the database.
	FieldSettlementID = "settlement_id"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldAmountCents holds the string denoting the amount_cents field in the database.
	FieldAmountCents = "amount_cents"
	// FieldMetadataWorkspaceID holds the string denoting the metadata_workspace_id field in the database.
	FieldMetadataWorkspaceID = "metadata_workspace_id"
	// FieldMetadataResourceID holds the string denoting the metadata_resource_id field in the database.
	FieldMetadataResourceID = "metadata_resource_id"
	// FieldMetadataSettlementID holds the string denoting the metadata_settlement_id field in the database.
	FieldMetadataSettlementID = "metadata_settlement_id"
	// FieldMetadataLedgerEntryID holds the string denoting the metadata_ledger_entry_id field in the database.
	FieldMetadataLedgerEntryID = "metadata_ledger_entry_id"
	// FieldMetadataComputeAllocationID holds the string denoting the metadata_compute_allocation_id field in the database.
	FieldMetadataComputeAllocationID = "metadata_compute_allocation_id"
	// FieldMetadataStorageID holds the string denoting the metadata_storage_id field in the database.
	FieldMetadataStorageID = "metadata_storage_id"
	// Table holds the table name of the wallettransactionprojection in the database.
	Table = "control_plane_wallet_transaction_projections"
)

// Columns holds all SQL columns for wallettransactionprojection fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldAccountID,
	FieldType,
	FieldLedgerEntryID,
	FieldResourceID,
	FieldWorkspaceID,
	FieldComputeAllocationID,
	FieldStorageID,
	FieldSettlementID,
	FieldCurrency,
	FieldAmountCents,
	FieldMetadataWorkspaceID,
	FieldMetadataResourceID,
	FieldMetadataSettlementID,
	FieldMetadataLedgerEntryID,
	FieldMetadataComputeAllocationID,
	FieldMetadataStorageID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// AccountIDValidator is a validator for the "account_id" field. It is called by the builders before save.
	AccountIDValidator func(string) error
	// DefaultType holds the default value on creation for the "type" field.
	DefaultType string
	// DefaultLedgerEntryID holds the default value on creation for the "ledger_entry_id" field.
	DefaultLedgerEntryID string
	// DefaultResourceID holds the default value on creation for the "resource_id" field.
	DefaultResourceID string
	// DefaultWorkspaceID holds the default value on creation for the "workspace_id" field.
	DefaultWorkspaceID string
	// DefaultComputeAllocationID holds the default value on creation for the "compute_allocation_id" field.
	DefaultComputeAllocationID string
	// DefaultStorageID holds the default value on creation for the "storage_id" field.
	DefaultStorageID string
	// DefaultSettlementID holds the default value on creation for the "settlement_id" field.
	DefaultSettlementID string
	// DefaultCurrency holds the default value on creation for the "currency" field.
	DefaultCurrency string
	// DefaultAmountCents holds the default value on creation for the "amount_cents" field.
	DefaultAmountCents int64
	// DefaultMetadataWorkspaceID holds the default value on creation for the "metadata_workspace_id" field.
	DefaultMetadataWorkspaceID string
	// DefaultMetadataResourceID holds the default value on creation for the "metadata_resource_id" field.
	DefaultMetadataResourceID string
	// DefaultMetadataSettlementID holds the default value on creation for the "metadata_settlement_id" field.
	DefaultMetadataSettlementID string
	// DefaultMetadataLedgerEntryID holds the default value on creation for the "metadata_ledger_entry_id" field.
	DefaultMetadataLedgerEntryID string
	// DefaultMetadataComputeAllocationID holds the default value on creation for the "metadata_compute_allocation_id" field.
	DefaultMetadataComputeAllocationID string
	// DefaultMetadataStorageID holds the default value on creation for the "metadata_storage_id" field.
	DefaultMetadataStorageID string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the WalletTransactionProjection queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByLedgerEntryID orders the results by the ledger_entry_id field.
func ByLedgerEntryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLedgerEntryID, opts...).ToFunc()
}

// ByResourceID orders the results by the resource_id field.
func ByResourceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceID, opts...).ToFunc()
}

// ByWorkspaceID orders the results by the workspace_id field.
func ByWorkspaceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkspaceID, opts...).ToFunc()
}

// ByComputeAllocationID orders the results by the compute_allocation_id field.
func ByComputeAllocationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldComputeAllocationID, opts...).ToFunc()
}

// ByStorageID orders the results by the storage_id field.
func ByStorageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStorageID, opts...).ToFunc()
}

// BySettlementID orders the results by the settlement_id field.
func BySettlementID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettlementID, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByAmountCents orders the results by the amount_cents field.
func ByAmountCents(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmountCents, opts...).ToFunc()
}

// ByMetadataWorkspaceID orders the results by the metadata_workspace_id field.
func ByMetadataWorkspaceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetadataWorkspaceID, opts...).ToFunc()
}

// ByMetadataResourceID orders the results by the metadata_resource_id field.
func ByMetadataResourceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetadataResourceID, opts...).ToFunc()
}

// ByMetadataSettlementID orders the results by the metadata_settlement_id field.
func ByMetadataSettlementID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetadataSettlementID, opts...).ToFunc()
}

// ByMetadataLedgerEntryID orders the results by the metadata_ledger_entry_id field.
func ByMetadataLedgerEntryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetadataLedgerEntryID, opts...).ToFunc()
}

// ByMetadataComputeAllocationID orders the results by the metadata_compute_allocation_id field.
func ByMetadataComputeAllocationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetadataComputeAllocationID, opts...).ToFunc()
}

// ByMetadataStorageID orders the results by the metadata_storage_id field.
func ByMetadataStorageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetadataStorageID, opts...).ToFunc()
}
