// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ContentTransfer is the predicate function for contenttransfer builders.
type ContentTransfer func(*sql.Selector)

// ContentTransferChunk is the predicate function for contenttransferchunk builders.
type ContentTransferChunk func(*sql.Selector)

// FabricOperation is the predicate function for fabricoperation builders.
type FabricOperation func(*sql.Selector)

// MachineOwnership is the predicate function for machineownership builders.
type MachineOwnership func(*sql.Selector)
