// Code generated by ent, DO NOT EDIT.

package billingreconciliation

import (
	"opl-cloud/services/control-plane/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldEQ(FieldUpdatedAt, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldEQ(FieldStatus, v))
}

// GuardStatus applies equality check predicate on the "guard_status" field. It's identical to GuardStatusEQ.
func GuardStatus(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldEQ(FieldGuardStatus, v))
}

// GuardReason applies equality check predicate on the "guard_reason" field. It's identical to GuardReasonEQ.
func GuardReason(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldEQ(FieldGuardReason, v))
}

// MessageAuthor applies equality check predicate on the "message_author" field. It's identical to MessageAuthorEQ.
func MessageAuthor(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldEQ(FieldMessageAuthor, v))
}

// MessageText applies equality check predicate on the "message_text" field. It's identical to MessageTextEQ.
func MessageText(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldEQ(FieldMessageText, v))
}

// MessageCreatedAt applies equality check predicate on the "message_created_at" field. It's identical to MessageCreatedAtEQ.
func MessageCreatedAt(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldEQ(FieldMessageCreatedAt, v))
}

// GuardBlockNewWorkspaces applies equality check predicate on the "guard_block_new_workspaces" field. It's identical to GuardBlockNewWorkspacesEQ.
func GuardBlockNewWorkspaces(v bool) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldEQ(FieldGuardBlockNewWorkspaces, v))
}

// Reports applies equality check predicate on the "reports" field. It's identical to ReportsEQ.
func Reports(v int64) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldEQ(FieldReports, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldLTE(FieldUpdatedAt, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldContainsFold(FieldStatus, v))
}

// GuardStatusEQ applies the EQ predicate on the "guard_status" field.
func GuardStatusEQ(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldEQ(FieldGuardStatus, v))
}

// GuardStatusNEQ applies the NEQ predicate on the "guard_status" field.
func GuardStatusNEQ(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldNEQ(FieldGuardStatus, v))
}

// GuardStatusIn applies the In predicate on the "guard_status" field.
func GuardStatusIn(vs ...string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldIn(FieldGuardStatus, vs...))
}

// GuardStatusNotIn applies the NotIn predicate on the "guard_status" field.
func GuardStatusNotIn(vs ...string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldNotIn(FieldGuardStatus, vs...))
}

// GuardStatusGT applies the GT predicate on the "guard_status" field.
func GuardStatusGT(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldGT(FieldGuardStatus, v))
}

// GuardStatusGTE applies the GTE predicate on the "guard_status" field.
func GuardStatusGTE(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldGTE(FieldGuardStatus, v))
}

// GuardStatusLT applies the LT predicate on the "guard_status" field.
func GuardStatusLT(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldLT(FieldGuardStatus, v))
}

// GuardStatusLTE applies the LTE predicate on the "guard_status" field.
func GuardStatusLTE(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldLTE(FieldGuardStatus, v))
}

// GuardStatusContains applies the Contains predicate on the "guard_status" field.
func GuardStatusContains(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldContains(FieldGuardStatus, v))
}

// GuardStatusHasPrefix applies the HasPrefix predicate on the "guard_status" field.
func GuardStatusHasPrefix(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldHasPrefix(FieldGuardStatus, v))
}

// GuardStatusHasSuffix applies the HasSuffix predicate on the "guard_status" field.
func GuardStatusHasSuffix(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldHasSuffix(FieldGuardStatus, v))
}

// GuardStatusEqualFold applies the EqualFold predicate on the "guard_status" field.
func GuardStatusEqualFold(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldEqualFold(FieldGuardStatus, v))
}

// GuardStatusContainsFold applies the ContainsFold predicate on the "guard_status" field.
func GuardStatusContainsFold(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldContainsFold(FieldGuardStatus, v))
}

// GuardReasonEQ applies the EQ predicate on the "guard_reason" field.
func GuardReasonEQ(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldEQ(FieldGuardReason, v))
}

// GuardReasonNEQ applies the NEQ predicate on the "guard_reason" field.
func GuardReasonNEQ(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldNEQ(FieldGuardReason, v))
}

// GuardReasonIn applies the In predicate on the "guard_reason" field.
func GuardReasonIn(vs ...string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldIn(FieldGuardReason, vs...))
}

// GuardReasonNotIn applies the NotIn predicate on the "guard_reason" field.
func GuardReasonNotIn(vs ...string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldNotIn(FieldGuardReason, vs...))
}

// GuardReasonGT applies the GT predicate on the "guard_reason" field.
func GuardReasonGT(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldGT(FieldGuardReason, v))
}

// GuardReasonGTE applies the GTE predicate on the "guard_reason" field.
func GuardReasonGTE(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldGTE(FieldGuardReason, v))
}

// GuardReasonLT applies the LT predicate on the "guard_reason" field.
func GuardReasonLT(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldLT(FieldGuardReason, v))
}

// GuardReasonLTE applies the LTE predicate on the "guard_reason" field.
func GuardReasonLTE(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldLTE(FieldGuardReason, v))
}

// GuardReasonContains applies the Contains predicate on the "guard_reason" field.
func GuardReasonContains(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldContains(FieldGuardReason, v))
}

// GuardReasonHasPrefix applies the HasPrefix predicate on the "guard_reason" field.
func GuardReasonHasPrefix(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldHasPrefix(FieldGuardReason, v))
}

// GuardReasonHasSuffix applies the HasSuffix predicate on the "guard_reason" field.
func GuardReasonHasSuffix(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldHasSuffix(FieldGuardReason, v))
}

// GuardReasonEqualFold applies the EqualFold predicate on the "guard_reason" field.
func GuardReasonEqualFold(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldEqualFold(FieldGuardReason, v))
}

// GuardReasonContainsFold applies the ContainsFold predicate on the "guard_reason" field.
func GuardReasonContainsFold(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldContainsFold(FieldGuardReason, v))
}

// MessageAuthorEQ applies the EQ predicate on the "message_author" field.
func MessageAuthorEQ(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldEQ(FieldMessageAuthor, v))
}

// MessageAuthorNEQ applies the NEQ predicate on the "message_author" field.
func MessageAuthorNEQ(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldNEQ(FieldMessageAuthor, v))
}

// MessageAuthorIn applies the In predicate on the "message_author" field.
func MessageAuthorIn(vs ...string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldIn(FieldMessageAuthor, vs...))
}

// MessageAuthorNotIn applies the NotIn predicate on the "message_author" field.
func MessageAuthorNotIn(vs ...string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldNotIn(FieldMessageAuthor, vs...))
}

// MessageAuthorGT applies the GT predicate on the "message_author" field.
func MessageAuthorGT(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldGT(FieldMessageAuthor, v))
}

// MessageAuthorGTE applies the GTE predicate on the "message_author" field.
func MessageAuthorGTE(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldGTE(FieldMessageAuthor, v))
}

// MessageAuthorLT applies the LT predicate on the "message_author" field.
func MessageAuthorLT(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldLT(FieldMessageAuthor, v))
}

// MessageAuthorLTE applies the LTE predicate on the "message_author" field.
func MessageAuthorLTE(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldLTE(FieldMessageAuthor, v))
}

// MessageAuthorContains applies the Contains predicate on the "message_author" field.
func MessageAuthorContains(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldContains(FieldMessageAuthor, v))
}

// MessageAuthorHasPrefix applies the HasPrefix predicate on the "message_author" field.
func MessageAuthorHasPrefix(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldHasPrefix(FieldMessageAuthor, v))
}

// MessageAuthorHasSuffix applies the HasSuffix predicate on the "message_author" field.
func MessageAuthorHasSuffix(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldHasSuffix(FieldMessageAuthor, v))
}

// MessageAuthorEqualFold applies the EqualFold predicate on the "message_author" field.
func MessageAuthorEqualFold(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldEqualFold(FieldMessageAuthor, v))
}

// MessageAuthorContainsFold applies the ContainsFold predicate on the "message_author" field.
func MessageAuthorContainsFold(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldContainsFold(FieldMessageAuthor, v))
}

// MessageTextEQ applies the EQ predicate on the "message_text" field.
func MessageTextEQ(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldEQ(FieldMessageText, v))
}

// MessageTextNEQ applies the NEQ predicate on the "message_text" field.
func MessageTextNEQ(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldNEQ(FieldMessageText, v))
}

// MessageTextIn applies the In predicate on the "message_text" field.
func MessageTextIn(vs ...string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldIn(FieldMessageText, vs...))
}

// MessageTextNotIn applies the NotIn predicate on the "message_text" field.
func MessageTextNotIn(vs ...string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldNotIn(FieldMessageText, vs...))
}

// MessageTextGT applies the GT predicate on the "message_text" field.
func MessageTextGT(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldGT(FieldMessageText, v))
}

// MessageTextGTE applies the GTE predicate on the "message_text" field.
func MessageTextGTE(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldGTE(FieldMessageText, v))
}

// MessageTextLT applies the LT predicate on the "message_text" field.
func MessageTextLT(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldLT(FieldMessageText, v))
}

// MessageTextLTE applies the LTE predicate on the "message_text" field.
func MessageTextLTE(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldLTE(FieldMessageText, v))
}

// MessageTextContains applies the Contains predicate on the "message_text" field.
func MessageTextContains(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldContains(FieldMessageText, v))
}

// MessageTextHasPrefix applies the HasPrefix predicate on the "message_text" field.
func MessageTextHasPrefix(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldHasPrefix(FieldMessageText, v))
}

// MessageTextHasSuffix applies the HasSuffix predicate on the "message_text" field.
func MessageTextHasSuffix(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldHasSuffix(FieldMessageText, v))
}

// MessageTextEqualFold applies the EqualFold predicate on the "message_text" field.
func MessageTextEqualFold(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldEqualFold(FieldMessageText, v))
}

// MessageTextContainsFold applies the ContainsFold predicate on the "message_text" field.
func MessageTextContainsFold(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldContainsFold(FieldMessageText, v))
}

// MessageCreatedAtEQ applies the EQ predicate on the "message_created_at" field.
func MessageCreatedAtEQ(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldEQ(FieldMessageCreatedAt, v))
}

// MessageCreatedAtNEQ applies the NEQ predicate on the "message_created_at" field.
func MessageCreatedAtNEQ(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldNEQ(FieldMessageCreatedAt, v))
}

// MessageCreatedAtIn applies the In predicate on the "message_created_at" field.
func MessageCreatedAtIn(vs ...string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldIn(FieldMessageCreatedAt, vs...))
}

// MessageCreatedAtNotIn applies the NotIn predicate on the "message_created_at" field.
func MessageCreatedAtNotIn(vs ...string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldNotIn(FieldMessageCreatedAt, vs...))
}

// MessageCreatedAtGT applies the GT predicate on the "message_created_at" field.
func MessageCreatedAtGT(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldGT(FieldMessageCreatedAt, v))
}

// MessageCreatedAtGTE applies the GTE predicate on the "message_created_at" field.
func MessageCreatedAtGTE(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldGTE(FieldMessageCreatedAt, v))
}

// MessageCreatedAtLT applies the LT predicate on the "message_created_at" field.
func MessageCreatedAtLT(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldLT(FieldMessageCreatedAt, v))
}

// MessageCreatedAtLTE applies the LTE predicate on the "message_created_at" field.
func MessageCreatedAtLTE(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldLTE(FieldMessageCreatedAt, v))
}

// MessageCreatedAtContains applies the Contains predicate on the "message_created_at" field.
func MessageCreatedAtContains(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldContains(FieldMessageCreatedAt, v))
}

// MessageCreatedAtHasPrefix applies the HasPrefix predicate on the "message_created_at" field.
func MessageCreatedAtHasPrefix(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldHasPrefix(FieldMessageCreatedAt, v))
}

// MessageCreatedAtHasSuffix applies the HasSuffix predicate on the "message_created_at" field.
func MessageCreatedAtHasSuffix(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldHasSuffix(FieldMessageCreatedAt, v))
}

// MessageCreatedAtEqualFold applies the EqualFold predicate on the "message_created_at" field.
func MessageCreatedAtEqualFold(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldEqualFold(FieldMessageCreatedAt, v))
}

// MessageCreatedAtContainsFold applies the ContainsFold predicate on the "message_created_at" field.
func MessageCreatedAtContainsFold(v string) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldContainsFold(FieldMessageCreatedAt, v))
}

// GuardBlockNewWorkspacesEQ applies the EQ predicate on the "guard_block_new_workspaces" field.
func GuardBlockNewWorkspacesEQ(v bool) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldEQ(FieldGuardBlockNewWorkspaces, v))
}

// GuardBlockNewWorkspacesNEQ applies the NEQ predicate on the "guard_block_new_workspaces" field.
func GuardBlockNewWorkspacesNEQ(v bool) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldNEQ(FieldGuardBlockNewWorkspaces, v))
}

// ReportsEQ applies the EQ predicate on the "reports" field.
func ReportsEQ(v int64) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldEQ(FieldReports, v))
}

// ReportsNEQ applies the NEQ predicate on the "reports" field.
func ReportsNEQ(v int64) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldNEQ(FieldReports, v))
}

// ReportsIn applies the In predicate on the "reports" field.
func ReportsIn(vs ...int64) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldIn(FieldReports, vs...))
}

// ReportsNotIn applies the NotIn predicate on the "reports" field.
func ReportsNotIn(vs ...int64) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldNotIn(FieldReports, vs...))
}

// ReportsGT applies the GT predicate on the "reports" field.
func ReportsGT(v int64) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldGT(FieldReports, v))
}

// ReportsGTE applies the GTE predicate on the "reports" field.
func ReportsGTE(v int64) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldGTE(FieldReports, v))
}

// ReportsLT applies the LT predicate on the "reports" field.
func ReportsLT(v int64) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldLT(FieldReports, v))
}

// ReportsLTE applies the LTE predicate on the "reports" field.
func ReportsLTE(v int64) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.FieldLTE(FieldReports, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BillingReconciliation) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BillingReconciliation) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BillingReconciliation) predicate.BillingReconciliation {
	return predicate.BillingReconciliation(sql.NotPredicates(p))
}
