// Code generated by ent, DO NOT EDIT.

package pricingcatalog

import (
	"opl-cloud/services/control-plane/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldEQ(FieldUpdatedAt, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldEQ(FieldVersion, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldEQ(FieldCurrency, v))
}

// HoldDays applies equality check predicate on the "hold_days" field. It's identical to HoldDaysEQ.
func HoldDays(v int) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldEQ(FieldHoldDays, v))
}

// EffectiveFrom applies equality check predicate on the "effective_from" field. It's identical to EffectiveFromEQ.
func EffectiveFrom(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldEQ(FieldEffectiveFrom, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldEQ(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldLTE(FieldUpdatedAt, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldLTE(FieldVersion, v))
}

// VersionContains applies the Contains predicate on the "version" field.
func VersionContains(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldContains(FieldVersion, v))
}

// VersionHasPrefix applies the HasPrefix predicate on the "version" field.
func VersionHasPrefix(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldHasPrefix(FieldVersion, v))
}

// VersionHasSuffix applies the HasSuffix predicate on the "version" field.
func VersionHasSuffix(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldHasSuffix(FieldVersion, v))
}

// VersionEqualFold applies the EqualFold predicate on the "version" field.
func VersionEqualFold(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldEqualFold(FieldVersion, v))
}

// VersionContainsFold applies the ContainsFold predicate on the "version" field.
func VersionContainsFold(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldContainsFold(FieldVersion, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldContainsFold(FieldCurrency, v))
}

// HoldDaysEQ applies the EQ predicate on the "hold_days" field.
func HoldDaysEQ(v int) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldEQ(FieldHoldDays, v))
}

// HoldDaysNEQ applies the NEQ predicate on the "hold_days" field.
func HoldDaysNEQ(v int) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldNEQ(FieldHoldDays, v))
}

// HoldDaysIn applies the In predicate on the "hold_days" field.
func HoldDaysIn(vs ...int) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldIn(FieldHoldDays, vs...))
}

// HoldDaysNotIn applies the NotIn predicate on the "hold_days" field.
func HoldDaysNotIn(vs ...int) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldNotIn(FieldHoldDays, vs...))
}

// HoldDaysGT applies the GT predicate on the "hold_days" field.
func HoldDaysGT(v int) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldGT(FieldHoldDays, v))
}

// HoldDaysGTE applies the GTE predicate on the "hold_days" field.
func HoldDaysGTE(v int) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldGTE(FieldHoldDays, v))
}

// HoldDaysLT applies the LT predicate on the "hold_days" field.
func HoldDaysLT(v int) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldLT(FieldHoldDays, v))
}

// HoldDaysLTE applies the LTE predicate on the "hold_days" field.
func HoldDaysLTE(v int) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldLTE(FieldHoldDays, v))
}

// EffectiveFromEQ applies the EQ predicate on the "effective_from" field.
func EffectiveFromEQ(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldEQ(FieldEffectiveFrom, v))
}

// EffectiveFromNEQ applies the NEQ predicate on the "effective_from" field.
func EffectiveFromNEQ(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldNEQ(FieldEffectiveFrom, v))
}

// EffectiveFromIn applies the In predicate on the "effective_from" field.
func EffectiveFromIn(vs ...string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldIn(FieldEffectiveFrom, vs...))
}

// EffectiveFromNotIn applies the NotIn predicate on the "effective_from" field.
func EffectiveFromNotIn(vs ...string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldNotIn(FieldEffectiveFrom, vs...))
}

// EffectiveFromGT applies the GT predicate on the "effective_from" field.
func EffectiveFromGT(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldGT(FieldEffectiveFrom, v))
}

// EffectiveFromGTE applies the GTE predicate on the "effective_from" field.
func EffectiveFromGTE(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldGTE(FieldEffectiveFrom, v))
}

// EffectiveFromLT applies the LT predicate on the "effective_from" field.
func EffectiveFromLT(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldLT(FieldEffectiveFrom, v))
}

// EffectiveFromLTE applies the LTE predicate on the "effective_from" field.
func EffectiveFromLTE(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldLTE(FieldEffectiveFrom, v))
}

// EffectiveFromContains applies the Contains predicate on the "effective_from" field.
func EffectiveFromContains(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldContains(FieldEffectiveFrom, v))
}

// EffectiveFromHasPrefix applies the HasPrefix predicate on the "effective_from" field.
func EffectiveFromHasPrefix(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldHasPrefix(FieldEffectiveFrom, v))
}

// EffectiveFromHasSuffix applies the HasSuffix predicate on the "effective_from" field.
func EffectiveFromHasSuffix(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldHasSuffix(FieldEffectiveFrom, v))
}

// EffectiveFromEqualFold applies the EqualFold predicate on the "effective_from" field.
func EffectiveFromEqualFold(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldEqualFold(FieldEffectiveFrom, v))
}

// EffectiveFromContainsFold applies the ContainsFold predicate on the "effective_from" field.
func EffectiveFromContainsFold(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldContainsFold(FieldEffectiveFrom, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.FieldContainsFold(FieldStatus, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PricingCatalog) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PricingCatalog) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PricingCatalog) predicate.PricingCatalog {
	return predicate.PricingCatalog(sql.NotPredicates(p))
}
