// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"opl-cloud/services/fabric/ent/machineownership"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MachineOwnershipCreate is the builder for creating a MachineOwnership entity.
type MachineOwnershipCreate struct {
	config
	mutation *MachineOwnershipMutation
	hooks    []Hook
}

// SetResourceID sets the "resource_id" field.
func (moc *MachineOwnershipCreate) SetResourceID(s string) *MachineOwnershipCreate {
	moc.mutation.SetResourceID(s)
	return moc
}

// SetAccountID sets the "account_id" field.
func (moc *MachineOwnershipCreate) SetAccountID(s string) *MachineOwnershipCreate {
	moc.mutation.SetAccountID(s)
	return moc
}

// SetWorkspaceID sets the "workspace_id" field.
func (moc *MachineOwnershipCreate) SetWorkspaceID(s string) *MachineOwnershipCreate {
	moc.mutation.SetWorkspaceID(s)
	return moc
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (moc *MachineOwnershipCreate) SetNillableWorkspaceID(s *string) *MachineOwnershipCreate {
	if s != nil {
		moc.SetWorkspaceID(*s)
	}
	return moc
}

// SetPackageID sets the "package_id" field.
func (moc *MachineOwnershipCreate) SetPackageID(s string) *MachineOwnershipCreate {
	moc.mutation.SetPackageID(s)
	return moc
}

// SetNodePoolID sets the "node_pool_id" field.
func (moc *MachineOwnershipCreate) SetNodePoolID(s string) *MachineOwnershipCreate {
	moc.mutation.SetNodePoolID(s)
	return moc
}

// SetMachineID sets the "machine_id" field.
func (moc *MachineOwnershipCreate) SetMachineID(s string) *MachineOwnershipCreate {
	moc.mutation.SetMachineID(s)
	return moc
}

// SetInstanceID sets the "instance_id" field.
func (moc *MachineOwnershipCreate) SetInstanceID(s string) *MachineOwnershipCreate {
	moc.mutation.SetInstanceID(s)
	return moc
}

// SetNillableInstanceID sets the "instance_id" field if the given value is not nil.
func (moc *MachineOwnershipCreate) SetNillableInstanceID(s *string) *MachineOwnershipCreate {
	if s != nil {
		moc.SetInstanceID(*s)
	}
	return moc
}

// SetNodeName sets the "node_name" field.
func (moc *MachineOwnershipCreate) SetNodeName(s string) *MachineOwnershipCreate {
	moc.mutation.SetNodeName(s)
	return moc
}

// SetNillableNodeName sets the "node_name" field if the given value is not nil.
func (moc *MachineOwnershipCreate) SetNillableNodeName(s *string) *MachineOwnershipCreate {
	if s != nil {
		moc.SetNodeName(*s)
	}
	return moc
}

// SetStatus sets the "status" field.
func (moc *MachineOwnershipCreate) SetStatus(s string) *MachineOwnershipCreate {
	moc.mutation.SetStatus(s)
	return moc
}

// SetProviderRequestID sets the "provider_request_id" field.
func (moc *MachineOwnershipCreate) SetProviderRequestID(s string) *MachineOwnershipCreate {
	moc.mutation.SetProviderRequestID(s)
	return moc
}

// SetNillableProviderRequestID sets the "provider_request_id" field if the given value is not nil.
func (moc *MachineOwnershipCreate) SetNillableProviderRequestID(s *string) *MachineOwnershipCreate {
	if s != nil {
		moc.SetProviderRequestID(*s)
	}
	return moc
}

// SetClaimedAt sets the "claimed_at" field.
func (moc *MachineOwnershipCreate) SetClaimedAt(t time.Time) *MachineOwnershipCreate {
	moc.mutation.SetClaimedAt(t)
	return moc
}

// SetReleasedAt sets the "released_at" field.
func (moc *MachineOwnershipCreate) SetReleasedAt(t time.Time) *MachineOwnershipCreate {
	moc.mutation.SetReleasedAt(t)
	return moc
}

// SetNillableReleasedAt sets the "released_at" field if the given value is not nil.
func (moc *MachineOwnershipCreate) SetNillableReleasedAt(t *time.Time) *MachineOwnershipCreate {
	if t != nil {
		moc.SetReleasedAt(*t)
	}
	return moc
}

// SetID sets the "id" field.
func (moc *MachineOwnershipCreate) SetID(s string) *MachineOwnershipCreate {
	moc.mutation.SetID(s)
	return moc
}

// Mutation returns the MachineOwnershipMutation object of the builder.
func (moc *MachineOwnershipCreate) Mutation() *MachineOwnershipMutation {
	return moc.mutation
}

// Save creates the MachineOwnership in the database.
func (moc *MachineOwnershipCreate) Save(ctx context.Context) (*MachineOwnership, error) {
	moc.defaults()
	return withHooks(ctx, moc.sqlSave, moc.mutation, moc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (moc *MachineOwnershipCreate) SaveX(ctx context.Context) *MachineOwnership {
	v, err := moc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (moc *MachineOwnershipCreate) Exec(ctx context.Context) error {
	_, err := moc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (moc *MachineOwnershipCreate) ExecX(ctx context.Context) {
	if err := moc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (moc *MachineOwnershipCreate) defaults() {
	if _, ok := moc.mutation.WorkspaceID(); !ok {
		v := machineownership.DefaultWorkspaceID
		moc.mutation.SetWorkspaceID(v)
	}
	if _, ok := moc.mutation.NodeName(); !ok {
		v := machineownership.DefaultNodeName
		moc.mutation.SetNodeName(v)
	}
	if _, ok := moc.mutation.ProviderRequestID(); !ok {
		v := machineownership.DefaultProviderRequestID
		moc.mutation.SetProviderRequestID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (moc *MachineOwnershipCreate) check() error {
	if _, ok := moc.mutation.ResourceID(); !ok {
		return &ValidationError{Name: "resource_id", err: errors.New(`ent: missing required field "MachineOwnership.resource_id"`)}
	}
	if v, ok := moc.mutation.ResourceID(); ok {
		if err := machineownership.ResourceIDValidator(v); err != nil {
			return &ValidationError{Name: "resource_id", err: fmt.Errorf(`ent: validator failed for field "MachineOwnership.resource_id": %w`, err)}
		}
	}
	if _, ok := moc.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "MachineOwnership.account_id"`)}
	}
	if v, ok := moc.mutation.AccountID(); ok {
		if err := machineownership.AccountIDValidator(v); err != nil {
			return &ValidationError{Name: "account_id", err: fmt.Errorf(`ent: validator failed for field "MachineOwnership.account_id": %w`, err)}
		}
	}
	if _, ok := moc.mutation.WorkspaceID(); !ok {
		return &ValidationError{Name: "workspace_id", err: errors.New(`ent: missing required field "MachineOwnership.workspace_id"`)}
	}
	if _, ok := moc.mutation.PackageID(); !ok {
		return &ValidationError{Name: "package_id", err: errors.New(`ent: missing required field "MachineOwnership.package_id"`)}
	}
	if v, ok := moc.mutation.PackageID(); ok {
		if err := machineownership.PackageIDValidator(v); err != nil {
			return &ValidationError{Name: "package_id", err: fmt.Errorf(`ent: validator failed for field "MachineOwnership.package_id": %w`, err)}
		}
	}
	if _, ok := moc.mutation.NodePoolID(); !ok {
		return &ValidationError{Name: "node_pool_id", err: errors.New(`ent: missing required field "MachineOwnership.node_pool_id"`)}
	}
	if v, ok := moc.mutation.NodePoolID(); ok {
		if err := machineownership.NodePoolIDValidator(v); err != nil {
			return &ValidationError{Name: "node_pool_id", err: fmt.Errorf(`ent: validator failed for field "MachineOwnership.node_pool_id": %w`, err)}
		}
	}
	if _, ok := moc.mutation.MachineID(); !ok {
		return &ValidationError{Name: "machine_id", err: errors.New(`ent: missing required field "MachineOwnership.machine_id"`)}
	}
	if v, ok := moc.mutation.MachineID(); ok {
		if err := machineownership.MachineIDValidator(v); err != nil {
			return &ValidationError{Name: "machine_id", err: fmt.Errorf(`ent: validator failed for field "MachineOwnership.machine_id": %w`, err)}
		}
	}
	if _, ok := moc.mutation.NodeName(); !ok {
		return &ValidationError{Name: "node_name", err: errors.New(`ent: missing required field "MachineOwnership.node_name"`)}
	}
	if _, ok := moc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "MachineOwnership.status"`)}
	}
	if v, ok := moc.mutation.Status(); ok {
		if err := machineownership.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MachineOwnership.status": %w`, err)}
		}
	}
	if _, ok := moc.mutation.ProviderRequestID(); !ok {
		return &ValidationError{Name: "provider_request_id", err: errors.New(`ent: missing required field "MachineOwnership.provider_request_id"`)}
	}
	if _, ok := moc.mutation.ClaimedAt(); !ok {
		return &ValidationError{Name: "claimed_at", err: errors.New(`ent: missing required field "MachineOwnership.claimed_at"`)}
	}
	if v, ok := moc.mutation.ID(); ok {
		if err := machineownership.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "MachineOwnership.id": %w`, err)}
		}
	}
	return nil
}

func (moc *MachineOwnershipCreate) sqlSave(ctx context.Context) (*MachineOwnership, error) {
	if err := moc.check(); err != nil {
		return nil, err
	}
	_node, _spec := moc.createSpec()
	if err := sqlgraph.CreateNode(ctx, moc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected MachineOwnership.ID type: %T", _spec.ID.Value)
		}
	}
	moc.mutation.id = &_node.ID
	moc.mutation.done = true
	return _node, nil
}

func (moc *MachineOwnershipCreate) createSpec() (*MachineOwnership, *sqlgraph.CreateSpec) {
	var (
		_node = &MachineOwnership{config: moc.config}
		_spec = sqlgraph.NewCreateSpec(machineownership.Table, sqlgraph.NewFieldSpec(machineownership.FieldID, field.TypeString))
	)
	if id, ok := moc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := moc.mutation.ResourceID(); ok {
		_spec.SetField(machineownership.FieldResourceID, field.TypeString, value)
		_node.ResourceID = value
	}
	if value, ok := moc.mutation.AccountID(); ok {
		_spec.SetField(machineownership.FieldAccountID, field.TypeString, value)
		_node.AccountID = value
	}
	if value, ok := moc.mutation.WorkspaceID(); ok {
		_spec.SetField(machineownership.FieldWorkspaceID, field.TypeString, value)
		_node.WorkspaceID = value
	}
	if value, ok := moc.mutation.PackageID(); ok {
		_spec.SetField(machineownership.FieldPackageID, field.TypeString, value)
		_node.PackageID = value
	}
	if value, ok := moc.mutation.NodePoolID(); ok {
		_spec.SetField(machineownership.FieldNodePoolID, field.TypeString, value)
		_node.NodePoolID = value
	}
	if value, ok := moc.mutation.MachineID(); ok {
		_spec.SetField(machineownership.FieldMachineID, field.TypeString, value)
		_node.MachineID = value
	}
	if value, ok := moc.mutation.InstanceID(); ok {
		_spec.SetField(machineownership.FieldInstanceID, field.TypeString, value)
		_node.InstanceID = value
	}
	if value, ok := moc.mutation.NodeName(); ok {
		_spec.SetField(machineownership.FieldNodeName, field.TypeString, value)
		_node.NodeName = value
	}
	if value, ok := moc.mutation.Status(); ok {
		_spec.SetField(machineownership.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := moc.mutation.ProviderRequestID(); ok {
		_spec.SetField(machineownership.FieldProviderRequestID, field.TypeString, value)
		_node.ProviderRequestID = value
	}
	if value, ok := moc.mutation.ClaimedAt(); ok {
		_spec.SetField(machineownership.FieldClaimedAt, field.TypeTime, value)
		_node.ClaimedAt = value
	}
	if value, ok := moc.mutation.ReleasedAt(); ok {
		_spec.SetField(machineownership.FieldReleasedAt, field.TypeTime, value)
		_node.ReleasedAt = &value
	}
	return _node, _spec
}

// MachineOwnershipCreateBulk is the builder for creating many MachineOwnership entities in bulk.
type MachineOwnershipCreateBulk struct {
	config
	err      error
	builders []*MachineOwnershipCreate
}

// Save creates the MachineOwnership entities in the database.
func (mocb *MachineOwnershipCreateBulk) Save(ctx context.Context) ([]*MachineOwnership, error) {
	if mocb.err != nil {
		return nil, mocb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(mocb.builders))
	nodes := make([]*MachineOwnership, len(mocb.builders))
	mutators := make([]Mutator, len(mocb.builders))
	for i := range mocb.builders {
		func(i int, root context.Context) {
			builder := mocb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MachineOwnershipMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mocb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mocb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mocb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mocb *MachineOwnershipCreateBulk) SaveX(ctx context.Context) []*MachineOwnership {
	v, err := mocb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mocb *MachineOwnershipCreateBulk) Exec(ctx context.Context) error {
	_, err := mocb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mocb *MachineOwnershipCreateBulk) ExecX(ctx context.Context) {
	if err := mocb.Exec(ctx); err != nil {
		panic(err)
	}
}
