// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"opl-cloud/services/fabric/ent/machineownership"
	"opl-cloud/services/fabric/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MachineOwnershipQuery is the builder for querying MachineOwnership entities.
type MachineOwnershipQuery struct {
	config
	ctx        *QueryContext
	order      []machineownership.OrderOption
	inters     []Interceptor
	predicates []predicate.MachineOwnership
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MachineOwnershipQuery builder.
func (moq *MachineOwnershipQuery) Where(ps ...predicate.MachineOwnership) *MachineOwnershipQuery {
	moq.predicates = append(moq.predicates, ps...)
	return moq
}

// Limit the number of records to be returned by this query.
func (moq *MachineOwnershipQuery) Limit(limit int) *MachineOwnershipQuery {
	moq.ctx.Limit = &limit
	return moq
}

// Offset to start from.
func (moq *MachineOwnershipQuery) Offset(offset int) *MachineOwnershipQuery {
	moq.ctx.Offset = &offset
	return moq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (moq *MachineOwnershipQuery) Unique(unique bool) *MachineOwnershipQuery {
	moq.ctx.Unique = &unique
	return moq
}

// Order specifies how the records should be ordered.
func (moq *MachineOwnershipQuery) Order(o ...machineownership.OrderOption) *MachineOwnershipQuery {
	moq.order = append(moq.order, o...)
	return moq
}

// First returns the first MachineOwnership entity from the query.
// Returns a *NotFoundError when no MachineOwnership was found.
func (moq *MachineOwnershipQuery) First(ctx context.Context) (*MachineOwnership, error) {
	nodes, err := moq.Limit(1).All(setContextOp(ctx, moq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{machineownership.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (moq *MachineOwnershipQuery) FirstX(ctx context.Context) *MachineOwnership {
	node, err := moq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MachineOwnership ID from the query.
// Returns a *NotFoundError when no MachineOwnership ID was found.
func (moq *MachineOwnershipQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = moq.Limit(1).IDs(setContextOp(ctx, moq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{machineownership.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (moq *MachineOwnershipQuery) FirstIDX(ctx context.Context) string {
	id, err := moq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MachineOwnership entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MachineOwnership entity is found.
// Returns a *NotFoundError when no MachineOwnership entities are found.
func (moq *MachineOwnershipQuery) Only(ctx context.Context) (*MachineOwnership, error) {
	nodes, err := moq.Limit(2).All(setContextOp(ctx, moq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{machineownership.Label}
	default:
		return nil, &NotSingularError{machineownership.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (moq *MachineOwnershipQuery) OnlyX(ctx context.Context) *MachineOwnership {
	node, err := moq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MachineOwnership ID in the query.
// Returns a *NotSingularError when more than one MachineOwnership ID is found.
// Returns a *NotFoundError when no entities are found.
func (moq *MachineOwnershipQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = moq.Limit(2).IDs(setContextOp(ctx, moq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{machineownership.Label}
	default:
		err = &NotSingularError{machineownership.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (moq *MachineOwnershipQuery) OnlyIDX(ctx context.Context) string {
	id, err := moq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MachineOwnerships.
func (moq *MachineOwnershipQuery) All(ctx context.Context) ([]*MachineOwnership, error) {
	ctx = setContextOp(ctx, moq.ctx, "All")
	if err := moq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MachineOwnership, *MachineOwnershipQuery]()
	return withInterceptors[[]*MachineOwnership](ctx, moq, qr, moq.inters)
}

// AllX is like All, but panics if an error occurs.
func (moq *MachineOwnershipQuery) AllX(ctx context.Context) []*MachineOwnership {
	nodes, err := moq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MachineOwnership IDs.
func (moq *MachineOwnershipQuery) IDs(ctx context.Context) (ids []string, err error) {
	if moq.ctx.Unique == nil && moq.path != nil {
		moq.Unique(true)
	}
	ctx = setContextOp(ctx, moq.ctx, "IDs")
	if err = moq.Select(machineownership.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (moq *MachineOwnershipQuery) IDsX(ctx context.Context) []string {
	ids, err := moq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (moq *MachineOwnershipQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, moq.ctx, "Count")
	if err := moq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, moq, querierCount[*MachineOwnershipQuery](), moq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (moq *MachineOwnershipQuery) CountX(ctx context.Context) int {
	count, err := moq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (moq *MachineOwnershipQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, moq.ctx, "Exist")
	switch _, err := moq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (moq *MachineOwnershipQuery) ExistX(ctx context.Context) bool {
	exist, err := moq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MachineOwnershipQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (moq *MachineOwnershipQuery) Clone() *MachineOwnershipQuery {
	if moq == nil {
		return nil
	}
	return &MachineOwnershipQuery{
		config:     moq.config,
		ctx:        moq.ctx.Clone(),
		order:      append([]machineownership.OrderOption{}, moq.order...),
		inters:     append([]Interceptor{}, moq.inters...),
		predicates: append([]predicate.MachineOwnership{}, moq.predicates...),
		// clone intermediate query.
		sql:  moq.sql.Clone(),
		path: moq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ResourceID string `json:"resource_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MachineOwnership.Query().
//		GroupBy(machineownership.FieldResourceID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (moq *MachineOwnershipQuery) GroupBy(field string, fields ...string) *MachineOwnershipGroupBy {
	moq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MachineOwnershipGroupBy{build: moq}
	grbuild.flds = &moq.ctx.Fields
	grbuild.label = machineownership.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ResourceID string `json:"resource_id,omitempty"`
//	}
//
//	client.MachineOwnership.Query().
//		Select(machineownership.FieldResourceID).
//		Scan(ctx, &v)
func (moq *MachineOwnershipQuery) Select(fields ...string) *MachineOwnershipSelect {
	moq.ctx.Fields = append(moq.ctx.Fields, fields...)
	sbuild := &MachineOwnershipSelect{MachineOwnershipQuery: moq}
	sbuild.label = machineownership.Label
	sbuild.flds, sbuild.scan = &moq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MachineOwnershipSelect configured with the given aggregations.
func (moq *MachineOwnershipQuery) Aggregate(fns ...AggregateFunc) *MachineOwnershipSelect {
	return moq.Select().Aggregate(fns...)
}

func (moq *MachineOwnershipQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range moq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, moq); err != nil {
				return err
			}
		}
	}
	for _, f := range moq.ctx.Fields {
		if !machineownership.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if moq.path != nil {
		prev, err := moq.path(ctx)
		if err != nil {
			return err
		}
		moq.sql = prev
	}
	return nil
}

func (moq *MachineOwnershipQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MachineOwnership, error) {
	var (
		nodes = []*MachineOwnership{}
		_spec = moq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MachineOwnership).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MachineOwnership{config: moq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, moq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (moq *MachineOwnershipQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := moq.querySpec()
	_spec.Node.Columns = moq.ctx.Fields
	if len(moq.ctx.Fields) > 0 {
		_spec.Unique = moq.ctx.Unique != nil && *moq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, moq.driver, _spec)
}

func (moq *MachineOwnershipQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(machineownership.Table, machineownership.Columns, sqlgraph.NewFieldSpec(machineownership.FieldID, field.TypeString))
	_spec.From = moq.sql
	if unique := moq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if moq.path != nil {
		_spec.Unique = true
	}
	if fields := moq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, machineownership.FieldID)
		for i := range fields {
			if fields[i] != machineownership.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := moq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := moq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := moq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := moq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (moq *MachineOwnershipQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(moq.driver.Dialect())
	t1 := builder.Table(machineownership.Table)
	columns := moq.ctx.Fields
	if len(columns) == 0 {
		columns = machineownership.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if moq.sql != nil {
		selector = moq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if moq.ctx.Unique != nil && *moq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range moq.predicates {
		p(selector)
	}
	for _, p := range moq.order {
		p(selector)
	}
	if offset := moq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := moq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MachineOwnershipGroupBy is the group-by builder for MachineOwnership entities.
type MachineOwnershipGroupBy struct {
	selector
	build *MachineOwnershipQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mogb *MachineOwnershipGroupBy) Aggregate(fns ...AggregateFunc) *MachineOwnershipGroupBy {
	mogb.fns = append(mogb.fns, fns...)
	return mogb
}

// Scan applies the selector query and scans the result into the given value.
func (mogb *MachineOwnershipGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mogb.build.ctx, "GroupBy")
	if err := mogb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MachineOwnershipQuery, *MachineOwnershipGroupBy](ctx, mogb.build, mogb, mogb.build.inters, v)
}

func (mogb *MachineOwnershipGroupBy) sqlScan(ctx context.Context, root *MachineOwnershipQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(mogb.fns))
	for _, fn := range mogb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*mogb.flds)+len(mogb.fns))
		for _, f := range *mogb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*mogb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mogb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MachineOwnershipSelect is the builder for selecting fields of MachineOwnership entities.
type MachineOwnershipSelect struct {
	*MachineOwnershipQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mos *MachineOwnershipSelect) Aggregate(fns ...AggregateFunc) *MachineOwnershipSelect {
	mos.fns = append(mos.fns, fns...)
	return mos
}

// Scan applies the selector query and scans the result into the given value.
func (mos *MachineOwnershipSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mos.ctx, "Select")
	if err := mos.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MachineOwnershipQuery, *MachineOwnershipSelect](ctx, mos.MachineOwnershipQuery, mos, mos.inters, v)
}

func (mos *MachineOwnershipSelect) sqlScan(ctx context.Context, root *MachineOwnershipQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(mos.fns))
	for _, fn := range mos.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*mos.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mos.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
