CREATE TABLE IF NOT EXISTS wallets (account_id TEXT PRIMARY KEY, balance_cents BIGINT NOT NULL DEFAULT 0, frozen_cents BIGINT NOT NULL DEFAULT 0, available_cents BIGINT NOT NULL DEFAULT 0, total_spent_cents BIGINT NOT NULL DEFAULT 0, currency TEXT NOT NULL DEFAULT 'CNY', updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
ALTER TABLE wallets ADD COLUMN IF NOT EXISTS available_cents BIGINT;
UPDATE wallets SET available_cents = COALESCE(balance_cents, 0) - COALESCE(frozen_cents, 0) WHERE available_cents IS NULL;
ALTER TABLE wallets ALTER COLUMN available_cents SET DEFAULT 0;
ALTER TABLE wallets ALTER COLUMN available_cents SET NOT NULL;
CREATE TABLE IF NOT EXISTS ledger_entries (id TEXT PRIMARY KEY, account_id TEXT NOT NULL, amount_cents BIGINT NOT NULL, currency TEXT NOT NULL, direction TEXT NOT NULL, source TEXT NOT NULL, operator_user_id TEXT NOT NULL DEFAULT '', reason TEXT NOT NULL DEFAULT '', created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS wallet_transactions (id TEXT PRIMARY KEY, account_id TEXT NOT NULL, ledger_entry_id TEXT NOT NULL, amount_cents BIGINT NOT NULL, balance_cents BIGINT NOT NULL, frozen_cents BIGINT NOT NULL, available_cents BIGINT NOT NULL, total_spent_cents BIGINT NOT NULL, currency TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS manual_topups (id TEXT PRIMARY KEY, account_id TEXT NOT NULL, amount_cents BIGINT NOT NULL, currency TEXT NOT NULL, operator_user_id TEXT NOT NULL, ledger_entry_id TEXT NOT NULL, wallet_transaction_id TEXT NOT NULL, idempotency_key TEXT NOT NULL UNIQUE, request_hash TEXT NOT NULL, reason TEXT NOT NULL DEFAULT '', created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS holds (id TEXT PRIMARY KEY, account_id TEXT NOT NULL, workspace_id TEXT NOT NULL, resource_type TEXT NOT NULL, resource_id TEXT NOT NULL, amount_cents BIGINT NOT NULL, currency TEXT NOT NULL, status TEXT NOT NULL, ledger_entry_id TEXT NOT NULL, wallet_transaction_id TEXT NOT NULL, idempotency_key TEXT NOT NULL UNIQUE, request_hash TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS hold_releases (id TEXT PRIMARY KEY, account_id TEXT NOT NULL, workspace_id TEXT NOT NULL, resource_type TEXT NOT NULL, resource_id TEXT NOT NULL, hold_id TEXT NOT NULL, amount_cents BIGINT NOT NULL, currency TEXT NOT NULL, status TEXT NOT NULL, ledger_entry_id TEXT NOT NULL, wallet_transaction_id TEXT NOT NULL, idempotency_key TEXT NOT NULL UNIQUE, request_hash TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS evidence_receipts (id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL, provider_request_id TEXT NOT NULL, redacted_url TEXT NOT NULL, token_version TEXT NOT NULL, idempotency_key TEXT NOT NULL UNIQUE, request_hash TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS resource_settlements (id TEXT PRIMARY KEY, account_id TEXT NOT NULL, workspace_id TEXT NOT NULL, resource_type TEXT NOT NULL, resource_id TEXT NOT NULL, amount_cents BIGINT NOT NULL, currency TEXT NOT NULL, status TEXT NOT NULL, ledger_entry_id TEXT NOT NULL, wallet_transaction_id TEXT NOT NULL, pricing_version TEXT NOT NULL DEFAULT '', price_snapshot_json TEXT NOT NULL DEFAULT '{}', usage_period_start TEXT NOT NULL DEFAULT '', usage_period_end TEXT NOT NULL DEFAULT '', quantity DOUBLE PRECISION NOT NULL DEFAULT 0, unit TEXT NOT NULL DEFAULT '', provider_cost_evidence_ref TEXT NOT NULL DEFAULT '', idempotency_key TEXT NOT NULL UNIQUE, request_hash TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS reconciliation_reports (id TEXT PRIMARY KEY, status TEXT NOT NULL, report_json TEXT NOT NULL DEFAULT '{}', block_new_workspaces BOOLEAN NOT NULL DEFAULT false, reason TEXT NOT NULL DEFAULT '', idempotency_key TEXT NOT NULL UNIQUE, request_hash TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS idempotency_keys (id TEXT PRIMARY KEY, service TEXT NOT NULL, idempotency_key TEXT NOT NULL, request_hash TEXT NOT NULL, response_ref TEXT NOT NULL DEFAULT '', created_at TIMESTAMPTZ NOT NULL DEFAULT now());

CREATE INDEX IF NOT EXISTS ledger_entries_account_idx ON ledger_entries(account_id);
CREATE INDEX IF NOT EXISTS wallet_transactions_account_idx ON wallet_transactions(account_id);
CREATE INDEX IF NOT EXISTS resource_settlements_account_idx ON resource_settlements(account_id);
