DO $$
DECLARE
  target_schema text;
  target_table text;
  target_column text;
  target_type text;
BEGIN
  FOR target_schema, target_table IN
    SELECT table_schema, table_name
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_name LIKE 'control_plane_%'
      AND table_type = 'BASE TABLE'
  LOOP
    EXECUTE format('ALTER TABLE %I.%I ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ', target_schema, target_table);
    EXECUTE format('ALTER TABLE %I.%I ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ', target_schema, target_table);
    EXECUTE format(
      'UPDATE %I.%I SET created_at = COALESCE(created_at, NOW()), updated_at = COALESCE(updated_at, created_at, NOW()) WHERE created_at IS NULL OR updated_at IS NULL',
      target_schema,
      target_table
    );
  END LOOP;

  FOR target_schema, target_table, target_column, target_type IN
    SELECT c.table_schema, c.table_name, c.column_name, c.data_type
    FROM information_schema.columns c
    JOIN information_schema.tables t
      ON t.table_schema = c.table_schema
      AND t.table_name = c.table_name
      AND t.table_type = 'BASE TABLE'
    WHERE c.table_schema = 'public'
      AND c.table_name LIKE 'control_plane_%'
      AND c.column_name NOT IN ('id', 'created_at', 'updated_at')
      AND c.data_type IN ('text', 'character varying', 'character', 'boolean', 'bigint', 'integer', 'double precision', 'numeric', 'real')
  LOOP
    IF target_type IN ('text', 'character varying', 'character') THEN
      EXECUTE format('UPDATE %I.%I SET %I = '''' WHERE %I IS NULL', target_schema, target_table, target_column, target_column);
    ELSIF target_type = 'boolean' THEN
      EXECUTE format('UPDATE %I.%I SET %I = false WHERE %I IS NULL', target_schema, target_table, target_column, target_column);
    ELSE
      EXECUTE format('UPDATE %I.%I SET %I = 0 WHERE %I IS NULL', target_schema, target_table, target_column, target_column);
    END IF;
  END LOOP;
END $$;

CREATE TABLE IF NOT EXISTS control_plane_accounts (id TEXT NOT NULL PRIMARY KEY, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL, owner_user_id TEXT NOT NULL DEFAULT '', name TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'active');
CREATE TABLE IF NOT EXISTS control_plane_admin_audit_events (id TEXT NOT NULL PRIMARY KEY, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL, actor_user_id TEXT NOT NULL DEFAULT '', actor_role TEXT NOT NULL DEFAULT '', actor_account_id TEXT NOT NULL DEFAULT '', target_account_id TEXT NOT NULL DEFAULT '', action TEXT NOT NULL DEFAULT '', resource_kind TEXT NOT NULL DEFAULT '', resource_id TEXT NOT NULL DEFAULT '', ip_address TEXT NOT NULL DEFAULT '', user_agent TEXT NOT NULL DEFAULT '', result TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS control_plane_archive_jobs (id TEXT NOT NULL PRIMARY KEY, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL, resource_kind TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT '', reason TEXT NOT NULL DEFAULT '', amount_cents BIGINT NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS control_plane_archived_admin_audit_events (id TEXT NOT NULL PRIMARY KEY, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL, actor_user_id TEXT NOT NULL DEFAULT '', actor_role TEXT NOT NULL DEFAULT '', actor_account_id TEXT NOT NULL DEFAULT '', target_account_id TEXT NOT NULL DEFAULT '', action TEXT NOT NULL DEFAULT '', resource_kind TEXT NOT NULL DEFAULT '', resource_id TEXT NOT NULL DEFAULT '', ip_address TEXT NOT NULL DEFAULT '', user_agent TEXT NOT NULL DEFAULT '', result TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS control_plane_archived_compute_allocations (id TEXT NOT NULL PRIMARY KEY, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL, account_id TEXT NOT NULL DEFAULT '', workspace_id TEXT NOT NULL DEFAULT '', resource_id TEXT NOT NULL DEFAULT '', resource_kind TEXT NOT NULL DEFAULT '', name TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT '', reason TEXT NOT NULL DEFAULT '', archived_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS control_plane_archived_storage_attachments (id TEXT NOT NULL PRIMARY KEY, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL, account_id TEXT NOT NULL DEFAULT '', workspace_id TEXT NOT NULL DEFAULT '', resource_id TEXT NOT NULL DEFAULT '', resource_kind TEXT NOT NULL DEFAULT '', name TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT '', reason TEXT NOT NULL DEFAULT '', archived_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS control_plane_archived_storage_volumes (id TEXT NOT NULL PRIMARY KEY, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL, account_id TEXT NOT NULL DEFAULT '', workspace_id TEXT NOT NULL DEFAULT '', resource_id TEXT NOT NULL DEFAULT '', resource_kind TEXT NOT NULL DEFAULT '', name TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT '', reason TEXT NOT NULL DEFAULT '', archived_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS control_plane_archived_workspaces (id TEXT NOT NULL PRIMARY KEY, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL, account_id TEXT NOT NULL DEFAULT '', workspace_id TEXT NOT NULL DEFAULT '', resource_id TEXT NOT NULL DEFAULT '', resource_kind TEXT NOT NULL DEFAULT '', name TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT '', reason TEXT NOT NULL DEFAULT '', archived_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS control_plane_auth_attempts (id TEXT NOT NULL PRIMARY KEY, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL, email TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT '', reason TEXT NOT NULL DEFAULT '', ip_address TEXT NOT NULL DEFAULT '', user_agent TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS control_plane_billing_reconciliation (id TEXT NOT NULL PRIMARY KEY, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL, status TEXT NOT NULL DEFAULT '', guard_status TEXT NOT NULL DEFAULT '', guard_reason TEXT NOT NULL DEFAULT '', message_author TEXT NOT NULL DEFAULT '', message_text TEXT NOT NULL DEFAULT '', message_created_at TEXT NOT NULL DEFAULT '', guard_block_new_workspaces BOOLEAN NOT NULL DEFAULT false, reports BIGINT NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS control_plane_compute_allocations (id TEXT NOT NULL PRIMARY KEY, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL, account_id TEXT NOT NULL, owner_user_id TEXT NOT NULL DEFAULT '', workspace_id TEXT NOT NULL DEFAULT '', name TEXT NOT NULL DEFAULT '', package_id TEXT NOT NULL DEFAULT '', provider TEXT NOT NULL DEFAULT '', provider_resource_id TEXT NOT NULL DEFAULT '', provider_request_id TEXT NOT NULL DEFAULT '', operation_id TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT '', billing_status TEXT NOT NULL DEFAULT '', hold_id TEXT NOT NULL DEFAULT '', hold_release_id TEXT NOT NULL DEFAULT '', settlement_id TEXT NOT NULL DEFAULT '', ledger_entry_id TEXT NOT NULL DEFAULT '', wallet_transaction_id TEXT NOT NULL DEFAULT '', pricing_version TEXT NOT NULL DEFAULT '', usage_period_end TEXT NOT NULL DEFAULT '', evidence_id TEXT NOT NULL DEFAULT '', cvm_instance_id TEXT NOT NULL DEFAULT '', instance_id TEXT NOT NULL DEFAULT '', node_name TEXT NOT NULL DEFAULT '', machine_name TEXT NOT NULL DEFAULT '', hold_amount_cents BIGINT NOT NULL DEFAULT 0, hold_amount DOUBLE PRECISION NOT NULL DEFAULT 0, cpu DOUBLE PRECISION NOT NULL DEFAULT 0, memory_gb DOUBLE PRECISION NOT NULL DEFAULT 0, disk_gb DOUBLE PRECISION NOT NULL DEFAULT 0, price_snapshot_package_id TEXT NOT NULL DEFAULT '', price_snapshot_resource_type TEXT NOT NULL DEFAULT '', price_snapshot_currency TEXT NOT NULL DEFAULT '', price_snapshot_source TEXT NOT NULL DEFAULT '', price_snapshot_sku TEXT NOT NULL DEFAULT '', price_snapshot_unit_price_cents BIGINT NOT NULL DEFAULT 0, price_snapshot_compute_hourly DOUBLE PRECISION NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS control_plane_ledger_projections (id TEXT NOT NULL PRIMARY KEY, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL, account_id TEXT NOT NULL, type TEXT NOT NULL DEFAULT '', resource_id TEXT NOT NULL DEFAULT '', resource_kind TEXT NOT NULL DEFAULT '', workspace_id TEXT NOT NULL DEFAULT '', compute_allocation_id TEXT NOT NULL DEFAULT '', storage_id TEXT NOT NULL DEFAULT '', settlement_id TEXT NOT NULL DEFAULT '', pricing_version TEXT NOT NULL DEFAULT '', usage_period_start TEXT NOT NULL DEFAULT '', usage_period_end TEXT NOT NULL DEFAULT '', unit TEXT NOT NULL DEFAULT '', provider_cost_evidence_ref TEXT NOT NULL DEFAULT '', currency TEXT NOT NULL DEFAULT 'CNY', amount_cents BIGINT NOT NULL DEFAULT 0, quantity DOUBLE PRECISION NOT NULL DEFAULT 0, direction TEXT NOT NULL DEFAULT '', price_snapshot_package_id TEXT NOT NULL DEFAULT '', price_snapshot_resource_type TEXT NOT NULL DEFAULT '', price_snapshot_currency TEXT NOT NULL DEFAULT '', price_snapshot_source TEXT NOT NULL DEFAULT '', price_snapshot_sku TEXT NOT NULL DEFAULT '', price_snapshot_unit_price_cents BIGINT NOT NULL DEFAULT 0, price_snapshot_compute_hourly DOUBLE PRECISION NOT NULL DEFAULT 0, price_snapshot_storage_gb_month DOUBLE PRECISION NOT NULL DEFAULT 0, price_snapshot_size_gb DOUBLE PRECISION NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS control_plane_manual_topup_projections (id TEXT NOT NULL PRIMARY KEY, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL, account_id TEXT NOT NULL, operator_user_id TEXT NOT NULL DEFAULT '', currency TEXT NOT NULL DEFAULT 'CNY', source TEXT NOT NULL DEFAULT 'manual', reason TEXT NOT NULL DEFAULT '', amount_cents BIGINT NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS control_plane_memberships (id TEXT NOT NULL PRIMARY KEY, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL, account_id TEXT NOT NULL, organization_id TEXT NOT NULL DEFAULT '', user_id TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'member', status TEXT NOT NULL DEFAULT 'active');
CREATE TABLE IF NOT EXISTS control_plane_organizations (id TEXT NOT NULL PRIMARY KEY, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL, billing_account_id TEXT NOT NULL DEFAULT '', name TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'active');
CREATE TABLE IF NOT EXISTS control_plane_production_e2e_records (id TEXT NOT NULL PRIMARY KEY, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL, account_id TEXT NOT NULL DEFAULT '', workspace_id TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT '', result TEXT NOT NULL DEFAULT '', reason TEXT NOT NULL DEFAULT '', url TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS control_plane_runtime_operations (id TEXT NOT NULL PRIMARY KEY, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL, operation_id TEXT NOT NULL DEFAULT '', account_id TEXT NOT NULL DEFAULT '', workspace_id TEXT NOT NULL DEFAULT '', resource_id TEXT NOT NULL DEFAULT '', resource_kind TEXT NOT NULL DEFAULT '', action TEXT NOT NULL DEFAULT '', provider TEXT NOT NULL DEFAULT '', provider_request_id TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT '', result TEXT NOT NULL DEFAULT '', compute_allocation_id TEXT NOT NULL DEFAULT '', storage_id TEXT NOT NULL DEFAULT '', attachment_id TEXT NOT NULL DEFAULT '', runtime_service_name TEXT NOT NULL DEFAULT '', cvm_instance_id TEXT NOT NULL DEFAULT '', instance_id TEXT NOT NULL DEFAULT '', node_name TEXT NOT NULL DEFAULT '', machine_name TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS control_plane_sessions (id TEXT NOT NULL PRIMARY KEY, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL, user_id TEXT NOT NULL, csrf TEXT NOT NULL, expires_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS control_plane_storage_attachments (id TEXT NOT NULL PRIMARY KEY, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL, account_id TEXT NOT NULL, workspace_id TEXT NOT NULL DEFAULT '', compute_allocation_id TEXT NOT NULL DEFAULT '', storage_id TEXT NOT NULL DEFAULT '', volume_id TEXT NOT NULL DEFAULT '', operation_id TEXT NOT NULL DEFAULT '', provider TEXT NOT NULL DEFAULT '', provider_request_id TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT '', mount_path TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS control_plane_storage_volumes (id TEXT NOT NULL PRIMARY KEY, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL, account_id TEXT NOT NULL, owner_user_id TEXT NOT NULL DEFAULT '', workspace_id TEXT NOT NULL DEFAULT '', name TEXT NOT NULL DEFAULT '', provider TEXT NOT NULL DEFAULT '', provider_resource_id TEXT NOT NULL DEFAULT '', provider_request_id TEXT NOT NULL DEFAULT '', operation_id TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT '', billing_status TEXT NOT NULL DEFAULT '', hold_id TEXT NOT NULL DEFAULT '', hold_release_id TEXT NOT NULL DEFAULT '', settlement_id TEXT NOT NULL DEFAULT '', ledger_entry_id TEXT NOT NULL DEFAULT '', wallet_transaction_id TEXT NOT NULL DEFAULT '', pricing_version TEXT NOT NULL DEFAULT '', usage_period_end TEXT NOT NULL DEFAULT '', mount_path TEXT NOT NULL DEFAULT '', hold_amount_cents BIGINT NOT NULL DEFAULT 0, hold_amount DOUBLE PRECISION NOT NULL DEFAULT 0, size_gb DOUBLE PRECISION NOT NULL DEFAULT 0, price_snapshot_resource_type TEXT NOT NULL DEFAULT '', price_snapshot_currency TEXT NOT NULL DEFAULT '', price_snapshot_source TEXT NOT NULL DEFAULT '', price_snapshot_unit_price_cents BIGINT NOT NULL DEFAULT 0, price_snapshot_storage_gb_month DOUBLE PRECISION NOT NULL DEFAULT 0, price_snapshot_size_gb DOUBLE PRECISION NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS control_plane_support_ticket_mappings (id TEXT NOT NULL PRIMARY KEY, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL, account_id TEXT NOT NULL DEFAULT '', user_id TEXT NOT NULL DEFAULT '', workspace_id TEXT NOT NULL DEFAULT '', resource_id TEXT NOT NULL DEFAULT '', resource_kind TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT '', source TEXT NOT NULL DEFAULT '', url TEXT NOT NULL DEFAULT '', reason TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS control_plane_users (id TEXT NOT NULL PRIMARY KEY, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL, account_id TEXT NOT NULL, email TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'owner', status TEXT NOT NULL DEFAULT 'active', password_hash TEXT NOT NULL DEFAULT '', disabled_at TEXT NOT NULL DEFAULT '', disabled_by TEXT NOT NULL DEFAULT '', disabled_reason TEXT NOT NULL DEFAULT '', deleted_at TEXT NOT NULL DEFAULT '', deleted_by TEXT NOT NULL DEFAULT '', delete_reason TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS control_plane_wallet_projections (id TEXT NOT NULL PRIMARY KEY, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL, account_id TEXT NOT NULL, currency TEXT NOT NULL DEFAULT 'CNY', balance_cents BIGINT NOT NULL DEFAULT 0, frozen_cents BIGINT NOT NULL DEFAULT 0, available_cents BIGINT NOT NULL DEFAULT 0, total_spent_cents BIGINT NOT NULL DEFAULT 0, balance DOUBLE PRECISION NOT NULL DEFAULT 0, frozen DOUBLE PRECISION NOT NULL DEFAULT 0, available DOUBLE PRECISION NOT NULL DEFAULT 0, total_spent DOUBLE PRECISION NOT NULL DEFAULT 0, total_recharged DOUBLE PRECISION NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS control_plane_wallet_transaction_projections (id TEXT NOT NULL PRIMARY KEY, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL, account_id TEXT NOT NULL, type TEXT NOT NULL DEFAULT '', ledger_entry_id TEXT NOT NULL DEFAULT '', resource_id TEXT NOT NULL DEFAULT '', workspace_id TEXT NOT NULL DEFAULT '', compute_allocation_id TEXT NOT NULL DEFAULT '', storage_id TEXT NOT NULL DEFAULT '', settlement_id TEXT NOT NULL DEFAULT '', currency TEXT NOT NULL DEFAULT 'CNY', amount_cents BIGINT NOT NULL DEFAULT 0, metadata_workspace_id TEXT NOT NULL DEFAULT '', metadata_resource_id TEXT NOT NULL DEFAULT '', metadata_settlement_id TEXT NOT NULL DEFAULT '', metadata_ledger_entry_id TEXT NOT NULL DEFAULT '', metadata_compute_allocation_id TEXT NOT NULL DEFAULT '', metadata_storage_id TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS control_plane_workspaces (id TEXT NOT NULL PRIMARY KEY, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL, account_id TEXT NOT NULL DEFAULT '', owner_account_id TEXT NOT NULL DEFAULT '', owner_user_id TEXT NOT NULL DEFAULT '', user_id TEXT NOT NULL DEFAULT '', name TEXT NOT NULL DEFAULT '', url TEXT NOT NULL DEFAULT '', state TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT '', storage_id TEXT NOT NULL DEFAULT '', current_compute_allocation_id TEXT NOT NULL DEFAULT '', current_attachment_id TEXT NOT NULL DEFAULT '', runtime_id TEXT NOT NULL DEFAULT '', runtime_service_name TEXT NOT NULL DEFAULT '', runtime_service_name_root TEXT NOT NULL DEFAULT '', service_name TEXT NOT NULL DEFAULT '', access_token_status TEXT NOT NULL DEFAULT '', access_account TEXT NOT NULL DEFAULT '', access_username TEXT NOT NULL DEFAULT '', access_password TEXT NOT NULL DEFAULT '', credential_status TEXT NOT NULL DEFAULT '', credential_version TEXT NOT NULL DEFAULT '', credential_secret_ref TEXT NOT NULL DEFAULT '', access_requires_login BOOLEAN NOT NULL DEFAULT false);
ALTER TABLE control_plane_compute_allocations ADD COLUMN IF NOT EXISTS desired_status TEXT NOT NULL DEFAULT '';
ALTER TABLE control_plane_compute_allocations ADD COLUMN IF NOT EXISTS provider_status TEXT NOT NULL DEFAULT '';
ALTER TABLE control_plane_compute_allocations ADD COLUMN IF NOT EXISTS last_provider_sync_at TEXT NOT NULL DEFAULT '';
ALTER TABLE control_plane_compute_allocations ADD COLUMN IF NOT EXISTS last_provider_sync_error TEXT NOT NULL DEFAULT '';
ALTER TABLE control_plane_compute_allocations ADD COLUMN IF NOT EXISTS external_deleted_at TEXT NOT NULL DEFAULT '';
ALTER TABLE control_plane_storage_volumes ADD COLUMN IF NOT EXISTS package_id TEXT NOT NULL DEFAULT '';
ALTER TABLE control_plane_storage_volumes ADD COLUMN IF NOT EXISTS desired_status TEXT NOT NULL DEFAULT '';
ALTER TABLE control_plane_storage_volumes ADD COLUMN IF NOT EXISTS provider_status TEXT NOT NULL DEFAULT '';
ALTER TABLE control_plane_storage_volumes ADD COLUMN IF NOT EXISTS last_provider_sync_at TEXT NOT NULL DEFAULT '';
ALTER TABLE control_plane_storage_volumes ADD COLUMN IF NOT EXISTS last_provider_sync_error TEXT NOT NULL DEFAULT '';
ALTER TABLE control_plane_storage_volumes ADD COLUMN IF NOT EXISTS external_deleted_at TEXT NOT NULL DEFAULT '';
CREATE TABLE IF NOT EXISTS control_plane_pricing_catalogs (id TEXT NOT NULL PRIMARY KEY, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL, version TEXT NOT NULL UNIQUE, currency TEXT NOT NULL DEFAULT 'CNY', hold_days BIGINT NOT NULL DEFAULT 7, effective_from TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'current');
CREATE TABLE IF NOT EXISTS control_plane_pricing_items (id TEXT NOT NULL PRIMARY KEY, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL, catalog_version TEXT NOT NULL, package_id TEXT NOT NULL, resource_type TEXT NOT NULL, unit TEXT NOT NULL, unit_price DOUBLE PRECISION NOT NULL DEFAULT 0, unit_price_cents BIGINT NOT NULL DEFAULT 0, available BOOLEAN NOT NULL DEFAULT true, name TEXT NOT NULL DEFAULT '', server TEXT NOT NULL DEFAULT '', cpu DOUBLE PRECISION NOT NULL DEFAULT 0, memory_gb DOUBLE PRECISION NOT NULL DEFAULT 0, disk_gb DOUBLE PRECISION NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS control_plane_workspace_sync_events (id TEXT NOT NULL PRIMARY KEY, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL, operation_id TEXT NOT NULL, workspace_id TEXT NOT NULL, cursor BIGINT NOT NULL, entity_kind TEXT NOT NULL, project_id TEXT NOT NULL, task_id TEXT NOT NULL DEFAULT '', client_id TEXT NOT NULL, actor_user_id TEXT NOT NULL, base_version BIGINT NOT NULL, server_version BIGINT NOT NULL, operation TEXT NOT NULL, status TEXT NOT NULL, payload_json TEXT NOT NULL DEFAULT '{}', content_digest TEXT NOT NULL DEFAULT '', idempotency_key TEXT NOT NULL UNIQUE, request_hash TEXT NOT NULL, conflict_id TEXT NOT NULL DEFAULT '', occurred_at TIMESTAMPTZ NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS workspace_sync_events_workspace_cursor ON control_plane_workspace_sync_events (workspace_id, cursor);
CREATE UNIQUE INDEX IF NOT EXISTS workspace_sync_events_workspace_operation ON control_plane_workspace_sync_events (workspace_id, operation_id);
CREATE INDEX IF NOT EXISTS workspace_sync_events_entity_cursor ON control_plane_workspace_sync_events (workspace_id, entity_kind, project_id, task_id, cursor);
CREATE INDEX IF NOT EXISTS workspace_sync_events_conflict ON control_plane_workspace_sync_events (workspace_id, conflict_id);
