// Code generated by ent, DO NOT EDIT.

package connector

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the connector type in the database.
	Label = "connector"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldConnectorID holds the string denoting the connector_id field in the database.
	FieldConnectorID = "connector_id"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldVersionIdentity holds the string denoting the version_identity field in the database.
	FieldVersionIdentity = "version_identity"
	// FieldDigest holds the string denoting the digest field in the database.
	FieldDigest = "digest"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldReadOnly holds the string denoting the read_only field in the database.
	FieldReadOnly = "read_only"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldResourceMetadata holds the string denoting the resource_metadata field in the database.
	FieldResourceMetadata = "resource_metadata"
	// FieldRuntimeMetadata holds the string denoting the runtime_metadata field in the database.
	FieldRuntimeMetadata = "runtime_metadata"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the connector in the database.
	Table = "fabric_connectors"
)

// Columns holds all SQL columns for connector fields.
var Columns = []string{
	FieldID,
	FieldConnectorID,
	FieldVersion,
	FieldVersionIdentity,
	FieldDigest,
	FieldName,
	FieldStatus,
	FieldReadOnly,
	FieldProvider,
	FieldResourceMetadata,
	FieldRuntimeMetadata,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ConnectorIDValidator is a validator for the "connector_id" field. It is called by the builders before save.
	ConnectorIDValidator func(string) error
	// VersionValidator is a validator for the "version" field. It is called by the builders before save.
	VersionValidator func(string) error
	// VersionIdentityValidator is a validator for the "version_identity" field. It is called by the builders before save.
	VersionIdentityValidator func(string) error
	// DigestValidator is a validator for the "digest" field. It is called by the builders before save.
	DigestValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultReadOnly holds the default value on creation for the "read_only" field.
	DefaultReadOnly bool
	// ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	ProviderValidator func(string) error
	// ResourceMetadataValidator is a validator for the "resource_metadata" field. It is called by the builders before save.
	ResourceMetadataValidator func(string) error
	// RuntimeMetadataValidator is a validator for the "runtime_metadata" field. It is called by the builders before save.
	RuntimeMetadataValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the Connector queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByConnectorID orders the results by the connector_id field.
func ByConnectorID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConnectorID, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByVersionIdentity orders the results by the version_identity field.
func ByVersionIdentity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersionIdentity, opts...).ToFunc()
}

// ByDigest orders the results by the digest field.
func ByDigest(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDigest, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByReadOnly orders the results by the read_only field.
func ByReadOnly(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReadOnly, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByResourceMetadata orders the results by the resource_metadata field.
func ByResourceMetadata(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceMetadata, opts...).ToFunc()
}

// ByRuntimeMetadata orders the results by the runtime_metadata field.
func ByRuntimeMetadata(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRuntimeMetadata, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
